<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/admin/includes/documents_helpers.php';
require_admin(); documents_ensure_structure();
$isDebug = safe_text($_GET['debug'] ?? '') === '1';
$id = safe_text($_GET['id'] ?? ''); $doc = $id !== '' ? documents_get_invoice($id) : null; $rows = [];
foreach (glob(documents_invoices_dir() . '/*.json') ?: [] as $file) { $row = json_load((string)$file, []); if (is_array($row)) $rows[] = array_merge(documents_invoice_defaults(), $row); }
usort($rows, static fn(array $a,array $b): int => strcmp((string)($b['updated_at']??$b['created_at']??''),(string)($a['updated_at']??$a['created_at']??'')));
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Invoices</title><link rel="stylesheet" href="assets/css/admin-unified.css"></head><body class="admin-shell commercial-admin"><main class="commercial-shell">
<header class="card commercial-header"><div><p class="admin-kicker">Commercial workspace</p><h1>Invoices</h1><p>Review invoice drafts and continue payment tracking through customer receipts.</p></div><nav class="commercial-header__actions"><a class="btn secondary" href="admin-dashboard.php">Dashboard</a><a class="btn secondary" href="admin-documents.php">Document Center</a><a class="btn commercial-header__primary" href="admin-documents.php?tab=accepted_customers">Open Receipts</a></nav></header>
<nav class="commercial-flow-strip" aria-label="Commercial lifecycle"><a href="admin-quotations.php">Quotation</a><span>→</span><a href="admin-agreements.php">Agreement</a><span>→</span><a href="admin-dispatch-advices.php">Dispatch Advice</a><span>→</span><a href="admin-challans.php">Challan</a><span>→</span><a class="active" href="admin-invoices.php">Invoice</a><span>→</span><a href="admin-documents.php?tab=accepted_customers">Receipt</a></nav>
<section class="card"><div class="commercial-toolbar"><div><h2>Invoices</h2><p class="muted-helper">Invoice creation and finalization remain in the secure document-pack workflow.</p></div></div><div class="responsive-table"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Linked quotation</th><th>Status</th><th>Amount</th><th>Updated</th><th>Actions</th></tr></thead><tbody>
<?php foreach($rows as $row): $quote=documents_get_quote((string)($row['linked_quote_id']??'')); $snap=array_merge(documents_customer_snapshot_defaults(),(array)($row['customer_snapshot']??[])); $amount=(float)($row['calc']['grand_total']??$row['calc']['gross_payable']??$row['input_total_gst_inclusive']??0); ?><tr><td><strong><?=htmlspecialchars((string)($row['invoice_no']?:$row['id']),ENT_QUOTES)?></strong></td><td><span class="quote-customer"><?=htmlspecialchars((string)($snap['name']??$quote['customer_name']??''),ENT_QUOTES)?></span><br><span class="muted-helper"><?=htmlspecialchars((string)($row['customer_mobile']??$snap['mobile']??''),ENT_QUOTES)?></span></td><td><?=htmlspecialchars((string)($quote['quote_no']??$row['linked_quote_id']??''),ENT_QUOTES)?></td><td><span class="status-badge status-badge--<?=strtolower(htmlspecialchars((string)($row['status']??''),ENT_QUOTES))?>"><?=htmlspecialchars((string)($row['status']??''),ENT_QUOTES)?></span></td><td class="quote-amount">₹<?=number_format($amount,2)?></td><td><?=htmlspecialchars((string)($row['updated_at']??$row['created_at']??''),ENT_QUOTES)?></td><td><div class="row-action-group"><a class="btn" href="admin-documents.php?tab=accepted_customers&amp;view=<?=urlencode((string)($row['linked_quote_id']??''))?>">Open</a><details class="more-actions"><summary class="btn secondary">More</summary><div class="more-actions__menu"><a class="btn secondary" href="admin-documents.php?tab=accepted_customers&amp;view=<?=urlencode((string)($row['linked_quote_id']??''))?>">Document Pack / Receipts</a><a class="btn secondary" href="?id=<?=urlencode((string)($row['id']??''))?>&amp;debug=1">Admin debug record</a></div></details></div></td></tr><?php endforeach; if($rows===[]):?><tr><td colspan="7" class="empty-state">No invoices found. Create one from an accepted customer's document pack.</td></tr><?php endif;?></tbody></table></div></section>
<?php if($isDebug && $doc!==null):?><details class="card advanced-fields" open><summary>Admin-only raw invoice debug record</summary><pre class="debug-record"><?=htmlspecialchars(json_encode($doc,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)?:'',ENT_QUOTES)?></pre></details><?php endif;?></main></body></html>
