<?php declare(strict_types=1);
require_once __DIR__.'/includes/public_document_security.php'; protect_customer_document_response();
require_once __DIR__.'/admin/includes/documents_helpers.php'; require_once __DIR__.'/includes/customer_document_acceptance.php';
$type=(string)($_GET['type']??'');$share=(string)($_GET['token']??'');$doc=null;$save=null;
if($type==='quotation'){$doc=documents_get_quote_by_public_share_token($share);$save='documents_save_quote';}
elseif($type==='dispatch_advice'){foreach(documents_list_dispatch_advices() as $x)if($share!==''&&hash_equals((string)$x['public_token'],$share)){$doc=$x;break;}$save='documents_save_dispatch_advice';}
elseif($type==='challan'){foreach(documents_list_challans() as $x)if($share!==''&&hash_equals((string)($x['public_token']??''),$share)){$doc=$x;break;}$save='documents_save_challan';}
$status=(string)($doc['status']??'');$quotationEligible=$type!=='quotation'||($status==='approved'&&(!array_key_exists('is_current_version',$doc)||!empty($doc['is_current_version']))&&!in_array($status,['archived','cancelled','superseded'],true));$eligible=$doc&&!empty($doc['public_share_enabled'])&&$quotationEligible&&(($type==='quotation'&&$status==='approved')||($type==='dispatch_advice'&&in_array($status,['finalized','shared'],true))||($type==='challan'&&in_array($status,['approved','issued'],true)))&&!($doc['archived_flag']??false);
if(!$eligible&&!empty($doc['customer_acceptance']['confirmed_at']))$eligible=true;if(!$eligible){http_response_code(404);exit('Link unavailable');}
if(empty($doc['customer_acceptance_request']['token_hash'])){$acceptToken=customer_acceptance_issue_token($doc,$type);$save($doc);}else{$acceptToken=(string)($_POST['acceptance_token']??'');}
$error='';$success=!empty($doc['customer_acceptance']['confirmed_at']);
if(isset($_GET['open_whatsapp'])&&$success&&$type==='dispatch_advice'){$settings=json_load(documents_dispatch_advice_settings_path(),[]);$company=load_company_profile();$publicLink=strtok((((isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https://':'http://').($_SERVER['HTTP_HOST']??'localhost').($_SERVER['REQUEST_URI']??'')),'?').'?token='.rawurlencode($share);$template=(string)($settings['whatsapp_template']??'Customer {customer_name} confirmed Dispatch Advice {dispatch_advice_no} v{dispatch_advice_version}.\nItems: {item_summary}\nAcceptance: {acceptance_ref}\n{public_link}');$built=customer_acceptance_dispatch_template($doc,(array)$doc['customer_acceptance'],$company,$publicLink,$template);customer_acceptance_mark_whatsapp_opened($doc,$built['message']);$save($doc);header('Location: https://wa.me/'.CUSTOMER_ACCEPTANCE_WHATSAPP_TARGET.'?text='.rawurlencode($built['message']));exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&!$success){$result=customer_acceptance_check_submission($doc,$type,$_POST,$acceptToken,['ip'=>$_SERVER['REMOTE_ADDR']??'','user_agent'=>$_SERVER['HTTP_USER_AGENT']??'','salt'=>(string)($doc['id']??'')]);if(!empty($result['ok'])){if($type==='quotation'){$doc['status']='accepted';$doc['accepted_at']=$doc['customer_acceptance']['confirmed_at'];$doc['locked_flag']=true;$doc['locked_at']=$doc['accepted_at'];}elseif($type==='dispatch_advice'){$doc['status']='acknowledged';$doc['acknowledged_at']=$doc['customer_acceptance']['confirmed_at'];}else{$doc['customer_receipt_status']='customer_received';}$saved=$save($doc);$success=(bool)($saved['ok']??false);if($success&&$type==='dispatch_advice')documents_create_draft_challan_from_dispatch_advice($doc);if(!$success)$error='Unable to record confirmation. Please try again.';}else{if(!empty($result['save']))$save($doc);$error=(string)$result['message'];}}
$e=(array)($doc['customer_acceptance']??[]);$self=((isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https://':'http://').($_SERVER['HTTP_HOST']??'localhost').($_SERVER['REQUEST_URI']??'');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="viewport" content="width=device-width"><title>Customer confirmation</title><style>body{font:16px Arial;background:#f4f7f6;color:#16332e;margin:0}.card{max-width:650px;margin:40px auto;background:#fff;padding:28px;border-radius:14px;box-shadow:0 8px 30px #0002}label{display:block;margin:14px 0}input,textarea{box-sizing:border-box;width:100%;padding:10px;margin-top:5px}input[type=checkbox]{width:auto}.btn{display:inline-block;background:#087b61;color:#fff;border:0;border-radius:8px;padding:12px 18px;text-decoration:none}.error{color:#a21b1b}.muted{color:#58716c}</style></head><body><main class="card"><?php if($success):?><h1>Confirmation recorded</h1><p><b><?=htmlspecialchars((string)$e['document_no'])?></b> · Reference <?=htmlspecialchars((string)$e['acceptance_ref'])?></p><p><?=htmlspecialchars((string)$e['confirmed_at'])?></p><p class="muted">Customer confirmed through a secure document link and registered-mobile verification. WhatsApp is additional evidence and is not sent until you choose the button below.</p><a class="btn" href="<?=htmlspecialchars($type==='dispatch_advice'?('?type=dispatch_advice&amp;token='.rawurlencode($share).'&amp;open_whatsapp=1'):customer_acceptance_whatsapp_url($e,$self))?>" target="_blank" rel="noopener">Open WhatsApp to send confirmation</a><?php else:?><h1>Confirm <?=htmlspecialchars(str_replace('_',' ',$type))?></h1><p><?=htmlspecialchars(customer_acceptance_confirmation_text($type))?></p><p class="muted">Saved mobile: <?=htmlspecialchars(customer_acceptance_mask_mobile((string)($doc['customer_mobile']??$doc['customer_snapshot']['mobile']??'')))?>. This secure-link confirmation attributes the response to the customer details entered; it is not absolute proof of identity.</p><?php if($error):?><p class="error"><?=htmlspecialchars($error)?></p><?php endif;?><form method="post"><input type="hidden" name="acceptance_token" value="<?=htmlspecialchars($acceptToken)?>"><label>First 6 digits of registered mobile<input name="mobile_first6" inputmode="numeric" pattern="[0-9]{6}" autocomplete="off" required></label><?php if($type==='challan'):?><label>Receipt remarks (optional)<textarea name="remarks"></textarea></label><?php endif;?><label><input type="checkbox" name="confirmed" value="1" required> <?=htmlspecialchars(customer_acceptance_confirmation_text($type))?></label><button class="btn">Record confirmation</button></form><?php endif;?></main></body></html>
