<?php
declare(strict_types=1);
require_once __DIR__.'/includes/employee_portal.php';
$store=new EmployeeFsStore();employee_portal_require_login();$employee=employee_portal_current_employee($store);if(!$employee){header('Location: login.php?login_type=employee');exit;}
function eas(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="csrf-token" content="<?=eas(csrf_token())?>"><title>Dakshayani Work — App</title><?php require __DIR__.'/includes/pwa_head.php';?></head>
<body data-employee-pwa><div class="employee-network" data-network-status role="status">Online</div><main class="employee-app-shell"><header class="employee-app-hero"><p class="eyebrow">SECURE EMPLOYEE WORKSPACE</p><h1>Dakshayani Work</h1><p>Hello <?=eas((string)($employee['name']??'Employee'))?>. Install your official work, deadlines, and operational alerts as a focused web app.</p><p class="app-state" data-app-status>Checking install state…</p><div class="employee-app-actions"><button type="button" data-employee-install hidden>Install Dakshayani Work</button><a href="employee-tasks.php">Open My Work</a><a href="employee-dashboard.php">Open Employee Dashboard</a></div></header>
<section class="employee-app-grid"><article><h2>Current work</h2><p>Open live assignments without storing private task data offline.</p></article><article><h2>Optional alerts</h2><p>Enable privacy-safe task alerts on browsers you choose.</p></article><article><h2>Secure access</h2><p>Every page and notification click still requires your authenticated employee session.</p></article></section>
<section class="employee-app-card"><h2>Browser notifications</h2><p>Push is optional. Alerts contain only a safe title and short operational message; in-app notifications remain authoritative.</p><p data-push-state role="status">Checking availability…</p><div class="employee-app-actions"><button type="button" data-enable-push>Enable Notifications</button><button type="button" class="secondary" data-revoke-all>Disable all my devices</button></div><h3>Registered browsers</h3><ul data-push-devices><li>Loading…</li></ul></section>
<section class="employee-app-card"><h2>Installation help</h2><div class="instruction-grid"><article><h3>Android Chrome</h3><p>Menu ⋮ → Install app. If offered above, use the Install button.</p></article><article><h3>Android Edge</h3><p>Menu → Add to phone → Install.</p></article><article><h3>Desktop Chrome</h3><p>Use the install icon in the address bar or menu → Cast, save and share → Install.</p></article><article><h3>Desktop Edge</h3><p>Menu … → Apps → Install Dakshayani Work.</p></article><article><h3>iPhone Safari</h3><p>Share → Add to Home Screen → Add. Push requires a supported iOS version and the installed Home Screen app.</p></article><article><h3>iPad Safari</h3><p>Share → Add to Home Screen. Open the installed app before enabling notifications.</p></article></div><h3>Prompt missing?</h3><p>Use HTTPS, open this employee page in the named browser, check that the app is not already installed, and reload after the service worker finishes installing.</p><p><strong>Internet required:</strong> current work, forms, tasks, and notifications are never available from an offline private cache.</p></section></main><?php require __DIR__.'/includes/mobile_app_nav.php';?><script defer src="assets/js/employee-pwa.js"></script></body></html>
