<?php
declare(strict_types=1);
require_once __DIR__.'/includes/public_document_security.php'; protect_customer_document_response();
require_once __DIR__.'/admin/includes/documents_helpers.php'; require_once __DIR__.'/includes/customer_document_acceptance.php';
$share=safe_text((string)($_GET['token']??''));$doc=$share!==''?documents_get_quote_by_public_share_token($share):null;$status=documents_quote_normalize_status((string)($doc['status']??''));
if(!$doc||empty($doc['public_share_enabled'])||!in_array($status,['approved','accepted'],true)||documents_is_archived($doc)){http_response_code(404);exit('Link unavailable');}
$rateFile=__DIR__.'/storage/customer-change-request-rate-limits.json';$rateKey=hash('sha256',(string)$doc['id'].'|'.($_SERVER['REMOTE_ADDR']??''));$rates=is_file($rateFile)?(json_decode((string)file_get_contents($rateFile),true)?:[]):[];$attempts=array_values(array_filter((array)($rates[$rateKey]??[]),static fn($t)=>$t>time()-900));$error='';$request=(array)($doc['customer_change_request']??[]);
if($_SERVER['REQUEST_METHOD']==='POST'&&$request===[]){try{
 if(count($attempts)>=5)throw new RuntimeException();$mobile=customer_acceptance_normalize_mobile((string)($doc['customer_mobile']??$doc['customer_snapshot']['mobile']??''));$first6=preg_replace('/\D+/','',(string)($_POST['mobile_first6']??''))??'';$changes=trim((string)($_POST['requested_changes']??''));
 if(strlen($mobile)!==10||!hash_equals(substr($mobile,0,6),$first6)||$changes===''||empty($_POST['confirmed']))throw new RuntimeException();
 $lock=fopen(documents_quotations_dir().'/.change-request-'.safe_filename((string)$doc['id']).'.lock','c');if(!$lock||!flock($lock,LOCK_EX))throw new RuntimeException();$doc=documents_get_quote((string)$doc['id'])??$doc;$request=(array)($doc['customer_change_request']??[]);
 if($request===[]){$now=date('c');$ref=customer_change_request_reference();$result=documents_create_quote_revision($doc,'Customer requested changes',$ref);if(!($result['ok']??false))throw new RuntimeException();$draft=(array)$result['quote'];$doc=(array)$result['source'];$draft['created_by_type']='customer_change_request';$draft['created_by_name']='Customer';if(!documents_save_quote($draft)['ok'])throw new RuntimeException();
 $request=['request_ref'=>$ref,'quotation_id'=>(string)$doc['id'],'quotation_no'=>(string)($doc['quote_no']??''),'requested_changes'=>$changes,'requested_at'=>$now,'generated_draft_revision_id'=>(string)$draft['id'],'generated_draft_revision_no'=>(string)$draft['quote_no'],'mobile_verified'=>'first_six','ip_hash'=>hash_hmac('sha256',(string)($_SERVER['REMOTE_ADDR']??''),(string)$doc['id'])];$doc['customer_change_request']=$request;if(!documents_save_quote($doc)['ok'])throw new RuntimeException();}
 flock($lock,LOCK_UN);fclose($lock);
}catch(Throwable $e){$attempts[]=time();$rates[$rateKey]=$attempts;file_put_contents($rateFile,json_encode($rates),LOCK_EX);$error='Unable to record your request. Please verify the details and try again.';}}
$self=((isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https://':'http://').($_SERVER['HTTP_HOST']??'localhost').'/quotation-public.php?t='.rawurlencode($share);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><meta name="viewport" content="width=device-width"><title>Request quotation changes</title><style>body{font:16px Arial;background:#f4f7f6;color:#16332e;margin:0}.card{max-width:650px;margin:40px auto;background:#fff;padding:28px;border-radius:14px;box-shadow:0 8px 30px #0002}label{display:block;margin:14px 0}input,textarea{box-sizing:border-box;width:100%;padding:10px;margin-top:5px}input[type=checkbox]{width:auto}.btn{display:inline-block;background:#087b61;color:#fff;border:0;border-radius:8px;padding:12px 18px;text-decoration:none}.error{color:#a21b1b}.muted{color:#58716c}</style></head><body><main class="card"><?php if($request!==[]):?><h1>Your requested changes have been recorded.</h1><p>Dakshayani Enterprises will review them and send you a revised quotation.</p><p class="muted">Request reference: <?=htmlspecialchars((string)$request['request_ref'])?></p><a class="btn" target="_blank" rel="noopener" href="<?=htmlspecialchars(customer_change_request_whatsapp_url($request,$self),ENT_QUOTES)?>">Open WhatsApp to notify us</a><?php else:?><h1>Request Changes</h1><p class="muted">Registered mobile: <?=htmlspecialchars(customer_acceptance_mask_mobile((string)($doc['customer_mobile']??'')))?></p><?php if($error):?><p class="error"><?=htmlspecialchars($error)?></p><?php endif;?><form method="post"><label>First 6 digits of registered mobile<input name="mobile_first6" inputmode="numeric" pattern="[0-9]{6}" autocomplete="off" required></label><label>What changes do you need?<textarea name="requested_changes" required></textarea></label><label><input type="checkbox" name="confirmed" value="1" required> I confirm that I want Dakshayani Enterprises to prepare a revised quotation.</label><button class="btn">Submit Request</button></form><?php endif;?></main></body></html>
