<?php
declare(strict_types=1);
require_once __DIR__ . '/admin/includes/documents_helpers.php';
documents_ensure_structure();
$token = safe_text($_GET['token'] ?? '');
$quote = null;
foreach (documents_list_quotes() as $q) {
    if ((string)($q['share']['public_token'] ?? '') === $token && !empty($q['share']['public_enabled'])) { $quote = $q; break; }
}
if ($token === '' || $quote === null) { http_response_code(404); echo '<h1>Link invalid or expired.</h1>'; exit; }
$quoteDefaults = documents_get_quote_defaults_settings();
$company = documents_get_company_profile_for_quotes();
$segment = (string)($quote['segment'] ?? 'RES');
$segmentDefaults = is_array($quoteDefaults['segments'][$segment] ?? null) ? $quoteDefaults['segments'][$segment] : [];
$brand = $quoteDefaults['global']['branding'] ?? [];
$theme = [
 'primary'=>$brand['primary_color'] ?? '#0f766e','secondary'=>$brand['secondary_color'] ?? '#22c55e','accent'=>$brand['accent_color'] ?? '#f59e0b',
 'header_bg'=>$brand['header_bg'] ?? '#0f766e','header_text'=>$brand['header_text'] ?? '#ecfeff','footer_bg'=>$brand['footer_bg'] ?? '#0f172a','footer_text'=>$brand['footer_text'] ?? '#e2e8f0',
 'chip_bg'=>$brand['chip_bg'] ?? '#ccfbf1','chip_text'=>$brand['chip_text'] ?? '#134e4a',
];
$preparedBy = (string)($quote['created_by_name'] ?? 'Team');
$snapshot = documents_quote_resolve_snapshot($quote);
$transport = (float)($quote['calc']['transportation_rs'] ?? $quote['finance_inputs']['transportation_rs'] ?? 0);
$subsidy = (float)($quote['calc']['subsidy_expected_rs'] ?? $quote['finance_inputs']['subsidy_expected_rs'] ?? 0);
if ($subsidy <= 0 && $segment === 'RES') { $cap=(float)($quote['capacity_kwp'] ?? 0); $subsidy = $cap>=3?(float)($segmentDefaults['subsidy']['cap_3kw_plus'] ?? 78000):($cap>=2?(float)($segmentDefaults['subsidy']['cap_2kw'] ?? 60000):0); }
$calc = documents_calc_pricing_from_items((array)($quote['items'] ?? []), (string)($quote['pricing_mode'] ?? 'solar_split_70_30'), (string)($quote['tax_type'] ?? 'CGST_SGST'), $transport, $subsidy);
$ann = is_array($quote['annexures_overrides'] ?? null) ? $quote['annexures_overrides'] : [];
$coverNote = trim((string)($quote['cover_note_text'] ?? '')) ?: trim((string)($quoteDefaults['defaults']['cover_note_template'] ?? ''));
$specialReq = trim((string)($quote['special_requests_text'] ?? $quote['special_requests_inclusive'] ?? ''));
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quotation</title>
<style>
body{font-family:Inter,Arial,sans-serif;background:#eef3f9;margin:0;color:#0f172a}.wrap{max-width:1100px;margin:0 auto;padding:12px}.card{background:#fff;border:1px solid #dbe1ea;border-radius:14px;padding:14px;margin-bottom:12px}.h{font-weight:700}.sec{border-bottom:2px solid <?= htmlspecialchars($theme['primary']) ?>;padding-bottom:5px;margin-bottom:8px}.grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.metric{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:8px}.chip{background:<?= htmlspecialchars($theme['chip_bg']) ?>;color:<?= htmlspecialchars($theme['chip_text']) ?>;border-radius:99px;padding:4px 8px;font-size:12px;display:inline-block;margin:2px}.tbl{width:100%;border-collapse:collapse}.tbl th,.tbl td{border:1px solid #dbe1ea;padding:6px;font-size:12px}.footer{background:<?= htmlspecialchars($theme['footer_bg']) ?>;color:<?= htmlspecialchars($theme['footer_text']) ?>}@media(max-width:800px){.grid2{grid-template-columns:1fr}}
</style></head><body><main class="wrap">
<section class="card" style="background:<?= htmlspecialchars($theme['header_bg']) ?>;color:<?= htmlspecialchars($theme['header_text']) ?>"><div class="h">Dakshayani Enterprises</div><div><?= htmlspecialchars((string)($company['address_line'] ?? '')) ?>, <?= htmlspecialchars((string)($company['city'] ?? '')) ?></div><div>☎ <?= htmlspecialchars((string)($company['phone_primary'] ?? '')) ?> <?= htmlspecialchars((string)($company['phone_secondary'] ?? '')) ?> · ✉ <?= htmlspecialchars((string)($company['email_primary'] ?? '')) ?> · 🌐 <?= htmlspecialchars((string)($company['website'] ?? '')) ?></div><div>GSTIN <?= htmlspecialchars((string)($company['gstin'] ?? '')) ?> · Udyam <?= htmlspecialchars((string)($company['udyam'] ?? '')) ?> · Licenses <?= htmlspecialchars((string)($company['jreda_license'] ?? '')) ?></div><div>Quote No <b><?= htmlspecialchars((string)$quote['quote_no']) ?></b> · Date <?= htmlspecialchars(substr((string)($quote['created_at'] ?? ''),0,10)) ?> · Valid till <?= htmlspecialchars((string)($quote['valid_until'] ?: '-')) ?> · Prepared by <?= htmlspecialchars($preparedBy) ?></div></section>
<section class="card"><div class="h sec">Customer Details</div><div class="grid2"><?php foreach([
'Name'=>$snapshot['name'] ?? $quote['customer_name'],'Mobile'=>$snapshot['mobile'] ?? $quote['customer_mobile'],'Site Address'=>$quote['site_address'] ?? $snapshot['address'],'City'=>$snapshot['city'] ?? $quote['city'],'District'=>$snapshot['district'] ?? $quote['district'],'PIN'=>$snapshot['pin_code'] ?? $quote['pin'],'State'=>$snapshot['state'] ?? $quote['state'],'Consumer Account No (JBVNL)'=>$snapshot['consumer_account_no'] ?? $quote['consumer_account_no'],'Meter no'=>$snapshot['meter_number'] ?? $quote['meter_number'],'Meter serial'=>$snapshot['meter_serial_number'] ?? $quote['meter_serial_number'],'Application ID'=>$snapshot['application_id'] ?? $quote['application_id'],'Application submitted date'=>$snapshot['application_submitted_date'] ?? $quote['application_submitted_date'],'Circle'=>$snapshot['circle_name'] ?? $quote['circle_name'],'Division'=>$snapshot['division_name'] ?? $quote['division_name'],'Sub Division'=>$snapshot['sub_division_name'] ?? $quote['sub_division_name'],'Sanction load'=>$snapshot['sanction_load_kwp'] ?? $quote['sanction_load_kwp'],'Installed capacity'=>$snapshot['installed_pv_module_capacity_kwp'] ?? $quote['installed_pv_module_capacity_kwp']] as $k=>$v): if(trim((string)$v)==='') continue; ?><div><b><?= htmlspecialchars($k) ?>:</b> <?= htmlspecialchars((string)$v) ?></div><?php endforeach; ?></div></section>
<?php if($coverNote!==''): ?><section class="card">🌞 <?= nl2br(htmlspecialchars($coverNote)) ?></section><?php endif; ?>
<section class="card"><div class="h sec">Items Table</div><table class="tbl"><thead><tr><th>Sr</th><th>Item name</th><th>Description/specs</th><th>HSN</th><th>Qty</th><th>Unit</th><th>GST slab</th><th>Amount (basic)</th></tr></thead><tbody><?php foreach(($quote['items'] ?? []) as $i=>$it): ?><tr><td><?= $i+1 ?></td><td><?= htmlspecialchars((string)($it['name'] ?? '')) ?></td><td><?= htmlspecialchars((string)($it['description'] ?? '')) ?></td><td><?= htmlspecialchars((string)($it['hsn'] ?? '')) ?></td><td><?= htmlspecialchars((string)($it['qty'] ?? '')) ?></td><td><?= htmlspecialchars((string)($it['unit'] ?? '')) ?></td><td><?= htmlspecialchars((string)($it['gst_slab'] ?? '')) ?></td><td>₹<?= number_format((float)($it['basic_amount'] ?? 0),2) ?></td></tr><?php endforeach; ?></tbody></table></section>
<section class="card"><div class="h sec">Pricing Summary</div><div class="grid2"><div class="metric">Final price (including GST): <b>₹<?= number_format((float)$calc['final_price_incl_gst'],2) ?></b></div><div class="metric">Transportation: <b>₹<?= number_format((float)$calc['transportation_rs'],2) ?></b></div><div class="metric">Gross (incl GST) payable: <b>₹<?= number_format((float)$calc['gross_payable'],2) ?></b></div><div class="metric">Subsidy (expected): <b>₹<?= number_format((float)$calc['subsidy_expected_rs'],2) ?></b></div><div class="metric">Net after subsidy: <b>₹<?= number_format((float)$calc['net_after_subsidy'],2) ?></b></div></div><div class="metric">GST breakup: base_5 ₹<?= number_format((float)$calc['bucket_5_basic'],2) ?>, gst_5 ₹<?= number_format((float)$calc['bucket_5_gst'],2) ?>, base_18 ₹<?= number_format((float)$calc['bucket_18_basic'],2) ?>, gst_18 ₹<?= number_format((float)$calc['bucket_18_gst'],2) ?>.</div><p>PM Surya Ghar: customer pays full amount; subsidy credited later after commissioning (as per scheme).</p></section>
<section class="card"><div class="h sec">Finance Clarity</div><div class="grid2"><div class="metric">Bank Loan Snapshot<br>1. Margin money: <b id="margin"></b><br>2. Initial loan amount: <b id="loan"></b><br>3. Loan after discounting subsidy: <b id="loanEff"></b><br>4. EMI on discounted loan: <b id="emi"></b><br>5. Residual bill: <b id="residual"></b><br>6. Total monthly outflow: <b id="outflow"></b></div><div class="metric">Self Financed Snapshot<br>1. Upfront investment: <b id="upfront"></b><br>2. Investment minus subsidy: <b id="upfrontNet"></b><br>3. Residual bill: <b id="selfResidual"></b></div><div class="metric">No Solar Snapshot<br><b id="noSolar"></b></div></div><p>For loans above ₹2L up to ₹6L: interest ~8.15%+ and margin ~20% (varies).</p></section>
<section class="card"><div class="h sec">Charts & Graphics</div><canvas id="c1" width="900" height="220"></canvas><canvas id="c2" width="900" height="220"></canvas><div id="payback"></div></section>
<section class="card"><div class="h sec">Environmental Impact</div><div class="grid2"><div class="metric">🌿 CO2 saved / year: <b id="co2y"></b></div><div class="metric">🌳 Trees planted / year: <b id="treey"></b></div><div class="metric">♻️ CO2 saved / 25 years: <b id="co225"></b></div><div class="metric">🌲 Trees planted / 25 years: <b id="tree25"></b></div></div></section>
<?php if($specialReq!==''): ?><section class="card"><div class="h sec">Special Requests From Consumer (Inclusive in the rate)</div><div><?= nl2br(htmlspecialchars($specialReq)) ?></div><div><i>In case of conflict between annexures and special requests, special requests will be prioritized.</i></div></section><?php endif; ?>
<section class="card"><div class="h sec">Annexures</div><?php foreach(['warranty'=>'Warranty','system_inclusions'=>'System inclusions','pm_subsidy_info'=>'PM subsidy info','completion_milestones'=>'Completion milestones','payment_terms'=>'Payment terms','system_type_explainer'=>'System Type explainer (ongrid vs hybrid vs offgrid)','transportation'=>'Transportation','terms_conditions'=>'Terms and conditions'] as $k=>$label): ?><details><summary><?= htmlspecialchars($label) ?></summary><div><?= nl2br(htmlspecialchars((string)($ann[$k] ?? ''))) ?></div></details><?php endforeach; ?></section>
<section class="card"><div class="h sec">Next Steps</div><?php foreach(['Confirm quotation','Book survey','Sign agreement','Install & net meter','Subsidy processing'] as $s): ?><span class="chip"><?= htmlspecialchars($s) ?></span><?php endforeach; ?></section>
<section class="card footer"><div class="h">Dakshayani Enterprises</div><div><?= htmlspecialchars((string)($company['address_line'] ?? '')) ?> · <?= htmlspecialchars((string)($company['phone_primary'] ?? '')) ?> · <?= htmlspecialchars((string)($company['email_primary'] ?? '')) ?> · <?= htmlspecialchars((string)($company['website'] ?? '')) ?></div></section>
</main>
<script>
const q={gross:<?= json_encode((float)$calc['gross_payable']) ?>,subsidy:<?= json_encode((float)$calc['subsidy_expected_rs']) ?>,monthly:<?= json_encode((float)($quote['finance_inputs']['monthly_bill_rs'] ?? 0)) ?>,unit:<?= json_encode((float)($quote['finance_inputs']['unit_rate_rs_per_kwh'] ?: $segmentDefaults['unit_rate_rs_per_kwh'] ?? 8)) ?>,cap:<?= json_encode((float)($quote['capacity_kwp'] ?? 0)) ?>,gen:<?= json_encode((float)($quote['finance_inputs']['annual_generation_per_kw'] ?: $segmentDefaults['annual_generation_per_kw'] ?? $quoteDefaults['global']['energy_defaults']['annual_generation_per_kw'] ?? 1450)) ?>};
const r=x=>'₹'+Number(x).toLocaleString('en-IN',{maximumFractionDigits:0});
const minMargin=q.gross*0.10,loan=Math.min(q.gross-minMargin,200000),margin=q.gross-loan,loanEff=Math.max(0,loan-q.subsidy),rr=0.06/12,n=120,emi=loanEff>0?(loanEff*rr*Math.pow(1+rr,n))/((Math.pow(1+rr,n))-1):0,mUnits=q.monthly/Math.max(0.1,q.unit),solar=(q.cap*q.gen)/12,res=Math.max(0,mUnits-solar)*q.unit,out=emi+res;
document.getElementById('margin').textContent=r(margin);document.getElementById('loan').textContent=r(loan);document.getElementById('loanEff').textContent=r(loanEff);document.getElementById('emi').textContent=r(emi);document.getElementById('residual').textContent=r(res);document.getElementById('outflow').textContent=r(out);document.getElementById('upfront').textContent=r(q.gross);document.getElementById('upfrontNet').textContent=r(q.gross-q.subsidy);document.getElementById('selfResidual').textContent=r(res);document.getElementById('noSolar').textContent='Monthly bill: '+r(q.monthly);
function bars(){const c=document.getElementById('c1').getContext('2d'),v=[q.monthly,out,res],cl=['#ef4444','#2563eb','#16a34a'];c.clearRect(0,0,900,220);const m=Math.max(...v,1);v.forEach((x,i)=>{c.fillStyle=cl[i];c.fillRect(40+i*250,180-(x/m*140),80,x/m*140);});}bars();
function lines(){const c=document.getElementById('c2').getContext('2d');c.clearRect(0,0,900,220);const pts=[];for(let y=0;y<=10;y++){pts.push([y,q.monthly*y*12,out*y*12,q.gross+res*y*12]);}const m=Math.max(...pts.map(p=>Math.max(p[1],p[2],p[3])));[['#ef4444',1],['#2563eb',2],['#16a34a',3]].forEach(a=>{c.strokeStyle=a[0];c.beginPath();pts.forEach((p,i)=>{const x=40+p[0]*80,yy=190-(p[a[1]]/m*150);if(i===0)c.moveTo(x,yy);else c.lineTo(x,yy)});c.stroke();});}lines();
const sav=(q.monthly-res)*12;document.getElementById('payback').textContent='Payback meter: ~'+(q.gross/Math.max(1,sav)).toFixed(1)+' years';
const yearly=q.cap*q.gen,co2=yearly*0.82,tree=co2/20;document.getElementById('co2y').textContent=co2.toFixed(0)+' kg';document.getElementById('treey').textContent=tree.toFixed(1);document.getElementById('co225').textContent=(co2*25).toFixed(0)+' kg';document.getElementById('tree25').textContent=(tree*25).toFixed(1);
</script>
</body></html>
