<?php declare(strict_types=1);
require_once __DIR__.'/../includes/customer_document_acceptance.php';
function ok($v,$m){if(!$v)throw new RuntimeException($m);}
$d=['id'=>'q1','quote_no'=>'Q-1','status'=>'approved','version_no'=>2,'customer_name'=>'Asha Devi','customer_mobile'=>'9876548178','items'=>[['name'=>'Panel','qty'=>2]]];
$t=customer_acceptance_issue_token($d,'quotation');ok(strlen($t)===64,'token entropy');ok(customer_acceptance_validate_token($d,'quotation',$t),'valid token');ok(!customer_acceptance_validate_token($d,'quotation','bad'),'invalid token');
customer_acceptance_record($d,'quotation',['mobile_first6'=>'987654','confirmed'=>'1'],['ip'=>'127.0.0.1','user_agent'=>'test','salt'=>'x']);$first=$d['customer_acceptance'];ok($first['identity_method']==='secure_link','identity method');ok(str_contains(customer_acceptance_whatsapp_url($first),'917070278178'),'WhatsApp target');customer_acceptance_record($d,'quotation',['mobile_first6'=>'000000','confirmed'=>'1']);ok($d['customer_acceptance']===$first,'idempotent evidence');ok(customer_acceptance_validate_token($d,'quotation',$t),'token remains idempotent');
$c=['id'=>'c1','challan_no'=>'DC-1','customer_name_snapshot'=>'Asha Devi','customer_mobile'=>'9876548178'];customer_acceptance_record($c,'challan',['mobile_first6'=>'987654','confirmed'=>'1','remarks'=>'One box damaged']);ok($c['customer_acceptance']['review_required']===true,'remarks review flag');
ok(customer_acceptance_normalize_mobile('+91 98765-48178')==='9876548178','91-prefixed formatted mobile normalized');ok(customer_acceptance_mask_mobile('919876548178')==='******8178','mobile mask');
echo "customer acceptance tests passed\n";
$r=['id'=>'r1','customer_mobile'=>'9876543210'];$rt=customer_acceptance_issue_token($r,'quotation');
foreach(['000000','111111'] as $wrong){$x=customer_acceptance_check_submission($r,'quotation',['mobile_first6'=>$wrong,'confirmed'=>'1'],$rt);ok(empty($x['ok']),'wrong prefix rejected');}
ok(($r['customer_acceptance_request']['incorrect_mobile_attempts']??0)===2,'only wrong prefixes counted');
$x=customer_acceptance_check_submission($r,'quotation',['mobile_first6'=>'987654','confirmed'=>'1'],$rt);ok(!empty($x['ok']),'correct prefix succeeds after wrong attempts');
foreach([['mobile_first6'=>'000000'],['mobile_first6'=>'000000','confirmed'=>'1']] as $input){$z=['id'=>'z','customer_mobile'=>'9876543210'];$zt=customer_acceptance_issue_token($z,'quotation');$before=(int)$z['customer_acceptance_request']['incorrect_mobile_attempts'];customer_acceptance_check_submission($z,'quotation',$input,$input['confirmed']??'' ? 'bad' : $zt);ok((int)$z['customer_acceptance_request']['incorrect_mobile_attempts']===$before,'non-prefix failure does not count');}
$l=['id'=>'l','customer_mobile'=>'9876543210'];$lt=customer_acceptance_issue_token($l,'challan');for($i=0;$i<3;$i++)customer_acceptance_check_submission($l,'challan',['mobile_first6'=>'000000','confirmed'=>'1'],$lt);ok(customer_acceptance_is_locked($l),'third wrong prefix locks');$fresh=customer_acceptance_issue_token($l,'challan');ok(!customer_acceptance_is_locked($l)&&customer_acceptance_validate_token($l,'challan',$fresh),'reissue resets lock');
