<?php
declare(strict_types=1);
$tmp=sys_get_temp_dir().'/dentweb_discom_'.bin2hex(random_bytes(4));define('DISCOM_STORAGE_DIR',$tmp);
require_once __DIR__.'/../includes/discom_requests.php';
$n=0;function d905(bool $ok,string $message):void{global $n;$n++;if(!$ok){fwrite(STDERR,"FAIL: $message\n");exit(1);}}
$profile=__DIR__.'/../data/documents/settings/company_profile.json';$before=is_file($profile)?file_get_contents($profile):null;
$projects=[];for($i=1;$i<=240;$i++)$projects[]=['quotation_id'=>'q'.$i,'quotation_reference'=>'Q-'.$i,'customer_name'=>'Customer with a deliberately long readable name '.$i,'application_id'=>'APP-'.$i,'division_name'=>$i%2?'Ranchi':'Khunti','sub_division_name'=>$i%3?'Main':'East','jbvnl_account_number'=>'ACC-'.$i,'solar_plant_installation_date'=>'2026-07-01','registered_mobile'=>'9876543210','installed_capacity'=>'3','address'=>'Address '.$i];
d905(count(array_slice($projects,0,120))===120,'120 Accepted fixtures');d905(count(array_slice($projects,120))===120,'120 Completed fixtures');
$validated=[];foreach($projects as $p)$validated[$p['quotation_id']]=['complete'=>true,'data'=>$p];$groups=discom_group_projects($validated);d905(count($groups)===4,'normalised division and subdivision grouping');d905(count(discom_group_projects($validated,true))===1,'explicit combination');
$html=discom_html_table(array_slice($projects,0,2));$csv=discom_csv(array_slice($projects,0,2));$pdf=discom_pdf(['snapshot'=>array_slice($projects,0,2),'subject'=>'Test','display_number'=>'DR-T']);d905(str_contains($html,'discom-table-wrap')&&str_contains($html,'Customer with'),'responsive escaped HTML projection');d905(str_starts_with($csv,"\xEF\xBB\xBF")&&str_contains($csv,'Application ID'),'CSV projection');d905(str_starts_with($pdf,'%PDF-1.4'),'PDF projection');
$actor=['id'=>'a1','role_name'=>'admin'];$r=['id'=>'r1','status'=>'Ready','subject'=>'Subject','email_body'=>'Body','snapshot'=>array_slice($projects,0,1),'columns'=>discom_default_columns(),'artifacts'=>['pdf'=>'missing.pdf'],'contact'=>['email_to'=>['sdo@example.test'],'email_cc'=>[]],'channels'=>['email'=>['status'=>'Not sent','attempts'=>[]],'whatsapp'=>['status'=>'Not shared']],'audit'=>[]];
$failed=discom_send_email($r,$actor,fn()=>['ok'=>false,'error'=>'provider down']);d905(!$failed['ok']&&$failed['request']['channels']['email']['status']==='Failed'&&$failed['request']['status']==='Ready','failed email remains retryable and not Sent');$sent=discom_send_email($r,$actor,fn()=>['ok'=>true,'message_id'=>'m1']);d905($sent['ok']&&$sent['request']['status']==='Sent'&&$sent['request']['channels']['email']['attempts'][0]['provider_id']==='m1','successful email provider id');
$opened=$r;d905($opened['channels']['whatsapp']['status']==='Not shared','opening does not share');$shared=discom_mark_whatsapp_shared($r,$actor);d905($shared['request']['channels']['whatsapp']['status']==='Shared','explicit WhatsApp confirmation');d905(!str_contains(discom_whatsapp_message($r),'9876543210'),'message excludes raw selected customer details');
$transition=discom_transition(array_merge($r,['status'=>'Sent']), 'Acknowledged',$actor);d905($transition['ok'],'valid status transition');d905(!discom_transition($r,'Closed',$actor)['ok'],'close requires reason and valid transition');d905(!discom_authorized(['role_name'=>'customer']),'permissions');d905(discom_email_list('good@example.test,bad')['invalid']===['bad'],'email validation');
$snapshot=$projects[0];$copy=$snapshot;$copy['customer_name']='Corrected';d905($snapshot['customer_name']!==$copy['customer_name'],'immutable value snapshot');$replacement=['revision_of'=>'r1'];d905($replacement['revision_of']==='r1','replacement linkage');
$source=file_get_contents(__DIR__.'/../admin-documents.php');d905(str_contains($source,'sessionStorage')&&str_contains($source,'dentweb.discom.selection.v1'),'cross-tab/filter/pagination selection persistence');d905(str_contains($source,'csrf_token'),'CSRF field');d905(($before===null&&!is_file($profile))||file_get_contents($profile)===$before,'company profile byte-for-byte unchanged');
foreach(glob($tmp.'/records/*.json')?:[] as $f)@unlink($f);foreach(glob($tmp.'/artifacts/*')?:[] as $f)@unlink($f);@unlink($tmp.'/contacts.json');@rmdir($tmp.'/records');@rmdir($tmp.'/artifacts');@rmdir($tmp);
echo "discom_inspection_net_metering_workflow_test passed ($n assertions)\n";
