<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/project_customer_account.php';

$n=0; function pcok(bool $v,string $m):void{global $n;$n++;if(!$v)throw new RuntimeException("FAIL: $m");}
function pcquote(string $id,string $mobile,bool $completed=false):array{return ['id'=>$id,'quote_no'=>'Q-'.$id,'status'=>'Accepted','segment'=>'RES','customer_name'=>'Fallback','customer_mobile'=>$mobile,'calc'=>['grand_total'=>123], 'customer_snapshot'=>['mobile'=>$mobile,'name'=>'Snapshot Name','address'=>'Road 1','city'=>'Ranchi','district'=>'Ranchi','state'=>'Jharkhand','pin_code'=>'834001','meter_number'=>'M1','meter_serial_number'=>'MS1','consumer_account_no'=>'A1','application_id'=>'APP1'], 'project_completion'=>$completed?['state'=>'completed','completed_at'=>'2026-01-01']:[]];}
$root=sys_get_temp_dir().'/pcacct_'.bin2hex(random_bytes(4));mkdir($root,0775,true);$store=new CustomerFsStore($root.'/customers');$saved=[];$events=[];
$save=function(array $q)use(&$saved):array{$saved[$q['id']]=$q;return ['ok'=>true];};$audit=function(string $e,string $id,array $d)use(&$events):void{$events[]=compact('e','id','d');};$actor=['id'=>'1','name'=>'Admin','role'=>'admin'];
$r=project_create_customer_account(pcquote('a','+91 98765-43210'),false,$actor,$store,$save,$audit,$root.'/locks');pcok(!empty($r['ok'])&&!empty($r['created']),'accepted created');$c=$store->findByMobile('9876543210');pcok($c['status']==='Installation Pending','accepted active installation status');pcok($c['name']==='Snapshot Name'&&$c['address']==='Road 1'&&$c['city']==='Ranchi'&&$c['district']==='Ranchi'&&$c['state']==='Jharkhand'&&$c['pin_code']==='834001','snapshot identity mapped');pcok($c['meter_number']==='M1'&&$c['meter_serial_number']==='MS1'&&$c['jbvnl_account_number']==='A1'&&$c['created_from_quote_id']==='a','meter/account/project mapped');pcok(password_get_info((string)$c['password_hash'])['algo']!==null&&$c['welcome_sent_via']==='none','secure hash and no automatic welcome');pcok(isset($saved['a']['customer_account_link']['linked_by'],$saved['a']['customer_account_link']['linked_at']),'actor timestamp link persisted');pcok($r['url']==='admin-users.php?tab=customers&view=9876543210','direct url');
$r2=project_create_customer_account($saved['a'],false,$actor,$store,$save,$audit,$root.'/locks');pcok(!empty($r2['ok'])&&empty($r2['created'])&&count($store->listCustomers())===1,'idempotent duplicate prevention');pcok($r2['link']['linked_at']===$r['link']['linked_at'],'idempotent link timestamp');
$r3=project_create_customer_account(pcquote('b','8765432109',true),true,$actor,$store,$save,$audit,$root.'/locks');pcok($store->findByMobile('8765432109')['status']==='Completed','completed status');
$bad=project_create_customer_account(pcquote('bad','12345'),false,$actor,$store,$save,$audit,$root.'/locks');pcok(empty($bad['ok'])&&str_contains($bad['error'],'invalid'),'invalid mobile rejected');
$store->archiveCustomer('9876543210','test');$arch=project_create_customer_account(pcquote('arch','9876543210'),false,$actor,$store,$save,$audit,$root.'/locks');pcok(!empty($arch['ok'])&&empty($arch['created'])&&!empty($arch['customer']['archived'])&&count($store->listCustomers())===2,'archived detected without duplicate');
$fail=project_create_customer_account(pcquote('fail','7654321098'),false,$actor,$store,fn(array $q):array=>['ok'=>false],$audit,$root.'/locks');pcok(empty($fail['ok'])&&$store->findByMobile('7654321098')!==null&&str_contains($fail['error'],'Customer was saved'),'customer saved before link failure');
pcok(count($events)>=4&&$events[0]['e']==='project_customer_account_created','audit emitted');
$source=file_get_contents(__DIR__.'/../admin-documents.php');pcok(str_contains($source,'verify_csrf_token')&&str_contains($source,"\$action === 'create_project_customer_account'")&&str_contains($source,"'role' => 'admin'"),'csrf authorization wiring');pcok(!str_contains(file_get_contents(__DIR__.'/../includes/project_customer_account.php'),'password123'),'no shared plaintext password');pcok(!isset($saved['a']['status'])||$saved['a']['status']==='Accepted','quotation status unchanged');pcok(($saved['a']['calc']['grand_total']??null)===123,'pricing unchanged');
echo "project_create_customer_account_test passed ($n assertions)\n";
