<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/bootstrap.php';require_once __DIR__.'/../includes/push_legacy_migration.php';
function jm(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
if(!function_exists('sodium_crypto_secretbox')){echo "push JSON migration tests skipped: PHP sodium unavailable\n";exit(0);}
$root=sys_get_temp_dir().'/push-migrate-'.bin2hex(random_bytes(5));mkdir($root,0770,true);$db=new PDO('sqlite:'.$root.'/db.sqlite',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);initialize_schema($db);seed_defaults($db);canonical_work_initialize_schema($db);task_notification_initialize_schema($db);push_initialize_schema($db);putenv('PUSH_SUBSCRIPTION_ENCRYPTION_KEY='.base64_encode(str_repeat('m',32)));
$role=(int)$db->query("SELECT id FROM roles WHERE name='employee'")->fetchColumn();$add=$db->prepare("INSERT INTO users(full_name,email,username,password_hash,role_id,status) VALUES(?,?,?,?,?,'active')");foreach([1,2] as $n)$add->execute(['Employee '.$n,"m$n@test","m$n",'x',$role]);$u1=(int)$db->query("SELECT id FROM users WHERE username='m1'")->fetchColumn();$u2=(int)$db->query("SELECT id FROM users WHERE username='m2'")->fetchColumn();$now=gmdate('Y-m-d H:i:s');$db->prepare("INSERT INTO portal_notifications(audience,tone,title,message,created_at,notification_type) VALUES('employee','info','T','M',?,'assigned')")->execute([$now]);$nid=(int)$db->lastInsertId();
$endpoint='https://8.8.8.8/push/a';$hash=hash('sha256',$endpoint);$legacy=static fn(int $id,int $uid,string $endpoint,string $hash)=>['id'=>$id,'user_id'=>$uid,'endpoint_hash'=>$hash,'endpoint'=>push_encrypt($endpoint),'p256dh'=>push_encrypt(str_repeat('A',44)),'auth'=>push_encrypt(str_repeat('B',22)),'status'=>'active'];
file_put_contents($root.'/subscriptions.json',json_encode([$legacy(10,$u1,$endpoint,$hash)],JSON_THROW_ON_ERROR));file_put_contents($root.'/deliveries.json',json_encode([['notification_id'=>$nid,'subscription_id'=>10],['notification_id'=>$nid,'subscription_id'=>10]],JSON_THROW_ON_ERROR));
$dbBefore=hash_file('sha256',$root.'/db.sqlite');$filesBefore=[];foreach(glob($root.'/*') as $f)$filesBefore[basename($f)]=[hash_file('sha256',$f),fileperms($f)&0777];$dry=push_migrate_legacy($db,$root,false);jm($dry['subscriptions_inserted']===1&&$dry['deliveries_imported']===1&&$dry['duplicate_deliveries']===1,'prospective dry-run mapping/duplicate');jm(hash_equals($dbBefore,hash_file('sha256',$root.'/db.sqlite')),'dry-run database mutation');foreach($filesBefore as $name=>$state)jm($state===[hash_file('sha256',$root.'/'.$name),fileperms($root.'/'.$name)&0777],'dry-run filesystem mutation');jm(count(glob($root.'/*.backup-*'))===0,'dry-run backup');
$apply=push_migrate_legacy($db,$root,true);jm($apply['subscriptions_inserted']===1&&$apply['deliveries_imported']===1,'apply counts');jm(count($apply['backups'])===2&&count(glob($root.'/*.backup-*'))===2,'backups');foreach($apply['backups'] as $backup){$path=$root.'/'.$backup['file'];jm(hash_equals($backup['sha256'],hash_file('sha256',$path)),'backup checksum');}jm(((fileperms($root.'/subscriptions.json')&0777)===0400),'legacy read-only');jm(push_migrate_legacy($db,$root,true)['already_complete'],'second apply idempotent');
// Same owner maps; a different owner is isolated and cannot import delivery rows.
$root2=$root.'/collision';mkdir($root2);$db->prepare("INSERT INTO push_subscriptions(user_id,endpoint_hash,endpoint_encrypted,p256dh_encrypted,auth_encrypted,device_label,status,created_at,updated_at) VALUES(?,?,?,?,?,'Canonical','active',?,?)")->execute([$u1,$hash,push_encrypt($endpoint),push_encrypt(str_repeat('A',44)),push_encrypt(str_repeat('B',22)),$now,$now]);file_put_contents($root2.'/subscriptions.json',json_encode([$legacy(20,$u1,$endpoint,$hash),$legacy(21,$u2,$endpoint,$hash)]));file_put_contents($root2.'/deliveries.json',json_encode([['notification_id'=>$nid,'subscription_id'=>20],['notification_id'=>$nid,'subscription_id'=>21]]));$collision=push_migrate_legacy($db,$root2,false);jm($collision['subscriptions_existing']===1&&$collision['ownership_conflicts']===1&&$collision['deliveries_imported']===1,'ownership collision');
file_put_contents($root2.'/subscriptions.json','{bad');$bad=push_migrate_legacy($db,$root2,false);jm($bad['malformed_json']===1,'malformed JSON');file_put_contents($root2.'/subscriptions.json',json_encode([$legacy(30,$u1,$endpoint,str_repeat('0',64))]));$bad=push_migrate_legacy($db,$root2,false);jm($bad['malformed_envelopes']===1,'endpoint hash validation');putenv('PUSH_SUBSCRIPTION_ENCRYPTION_KEY='.base64_encode(str_repeat('z',32)));$bad=push_migrate_legacy($db,$root2,false);jm($bad['malformed_envelopes']===1,'wrong-key validation');
echo "push JSON migration tests passed\n";
