<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/bootstrap.php';require_once __DIR__.'/../includes/push_worker.php';
function wcok(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
final class FakePushTransport implements PushDeliveryTransport{public array $seen=[];public function __construct(private array $outcomes){}public function send(array $delivery,array $payload):array{$id=(int)$delivery['id'];$this->seen[]=$id;$out=$this->outcomes[$id]??['success'=>false,'status'=>0,'category'=>'no_report'];if($out==='throw')throw new RuntimeException('fake');return $out;}}
$root=sys_get_temp_dir().'/push-worker-'.bin2hex(random_bytes(5));mkdir($root);$db=new PDO('sqlite:'.$root.'/db',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);initialize_schema($db);seed_defaults($db);canonical_work_initialize_schema($db);task_notification_initialize_schema($db);push_initialize_schema($db);$role=(int)$db->query("SELECT id FROM roles WHERE name='employee'")->fetchColumn();$db->prepare("INSERT INTO users(full_name,email,username,password_hash,role_id,status) VALUES('Worker','w@test','w','x',?,'active')")->execute([$role]);$uid=(int)$db->lastInsertId();$now=gmdate('Y-m-d H:i:s');$db->prepare("INSERT INTO push_subscriptions(user_id,endpoint_hash,endpoint_encrypted,p256dh_encrypted,auth_encrypted,device_label,status,created_at,updated_at) VALUES(?,?,?,?,?,'Browser','active',?,?)")->execute([$uid,str_repeat('a',64),'x','x','x',$now,$now]);$sid=(int)$db->lastInsertId();$ids=[];foreach(['assigned','assigned','assigned'] as $type){$db->prepare("INSERT INTO portal_notifications(audience,tone,title,message,created_at,notification_type) VALUES('employee','info','Private','Private',?,?)")->execute([$now,$type]);$nid=(int)$db->lastInsertId();$db->prepare("INSERT INTO portal_notification_status(notification_id,user_id,status,updated_at,unread_at) VALUES(?,?,'unread',?,?)")->execute([$nid,$uid,$now,$now]);$db->prepare("INSERT INTO push_deliveries(notification_id,subscription_id,status,next_attempt_at,created_at,updated_at) VALUES(?,?,'pending',?,?,?)")->execute([$nid,$sid,$now,$now,$now]);$ids[]=(int)$db->lastInsertId();}
$fake=new FakePushTransport([$ids[0]=>['success'=>true,'status'=>201],$ids[1]=>['success'=>false,'status'=>503],$ids[2]=>['success'=>false,'status'=>410]]);$report=push_worker_run($db,$fake,3);$states=$db->query('SELECT id,status,claim_token FROM push_deliveries ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);wcok($states[0]['status']==='sent'&&$states[1]['status']==='skipped'&&$states[2]['status']==='invalid','mixed exact outcomes and safe expiry cleanup');wcok($db->query('SELECT status FROM push_subscriptions WHERE id='.$sid)->fetchColumn()==='expired','subscription expiry');wcok($report['claimed']===3&&$report['sent']===1&&$report['temporary_failures']===1&&$report['invalidated']===1,'worker report');wcok(count(array_unique($fake->seen))===3,'per-delivery correlation');$statusCount=$db->prepare("SELECT COUNT(*) FROM portal_notification_status WHERE user_id=? AND status='unread'");$statusCount->execute([$uid]);wcok((int)$statusCount->fetchColumn()===3,'in-app state retained');
$a='a';$b='b';wcok(push_worker_lease_acquire($db,$a,300),'lease acquire');wcok(!push_worker_lease_acquire($db,$b,300),'one lease winner');wcok(push_worker_lease_renew($db,$a,300)&&push_worker_lease_owned($db,$a),'lease renewal');$db->exec("UPDATE push_worker_leases SET lease_expires_at=datetime('now','-1 second')");wcok(!push_worker_lease_owned($db,$a)&&push_worker_lease_acquire($db,$b,300),'expired takeover/old rejection');push_worker_lease_release($db,$a);wcok(push_worker_lease_owned($db,$b),'old token cannot release new lease');push_worker_lease_release($db,$b);
echo "push worker lease, claim and mixed transport tests passed\n";
