<?php
declare(strict_types=1);
$root=sys_get_temp_dir().'/dentweb_963_'.bin2hex(random_bytes(4));putenv('DOCUMENTS_BASE_DIR='.$root.'/documents');putenv('LEGACY_BILLING_BASE_DIR='.$root.'/legacy');
require_once __DIR__.'/../admin/includes/documents_helpers.php';
$inventoryFixtures=[];foreach([documents_inventory_tax_profiles_path(),documents_inventory_components_path(),documents_inventory_component_variants_path()] as $path)$inventoryFixtures[$path]=is_file($path)?file_get_contents($path):null;
$n=0;function issue963(bool $ok,string $message):void{global $n;$n++;if(!$ok)throw new RuntimeException($message);}
try{
 documents_ensure_structure();$settings=documents_settings_dir();file_put_contents($settings.'/numbering_rules.json',json_encode(['fy_start_month'=>4,'rules'=>[['doc_type'=>'invoice_public','segment'=>'RES','active'=>true,'prefix'=>'INV','format'=>'{{prefix}}/{{segment}}/{{fy}}/{{seq}}','seq_start'=>1,'seq_current'=>1,'seq_digits'=>4]]]));
 $created=documents_create_standalone_invoice();issue963($created['ok'],'standalone creation');$invoice=documents_get_invoice($created['invoice_id']);issue963(is_array($invoice),'stored invoice');issue963(str_starts_with((string)$invoice['invoice_no'],'INV/RES/'),'normal numbering');issue963(($invoice['commercial_ref']['type']??'')==='standalone_invoice','explicit source');issue963(($invoice['commercial_ref']['id']??'')===$invoice['id'],'stable standalone reference');issue963(($invoice['quotation_id']??'')===''&&($invoice['linked_quote_id']??'')==='','no fake quotation');issue963((glob(documents_quotations_dir().'/*.json')?:[])===[],'no quote file');issue963((glob($root.'/legacy/LEG-*.json')?:[])===[],'no legacy project');issue963(!documents_invoice_has_quotation_reference($invoice),'no false quote pricing');
 $invoice['invoice_no']='MANUAL/77';$invoice['invoice_date']='2026-08-01';$invoice['manual_reference']=['quotation_no'=>'DE/OLD/123','quotation_date'=>'2020-01-02','external_reference'=>'BOOK-9','quotation_amount'=>null];
 json_save(documents_inventory_tax_profiles_path(),[['id'=>'solar-split','name'=>'Solar split','mode'=>'split','slabs'=>[['share_pct'=>70,'rate_pct'=>5],['share_pct'=>30,'rate_pct'=>18]]]]);json_save(documents_inventory_components_path(),[['id'=>'panel','name'=>'Panel','description'=>'Master description','hsn'=>'8541','default_unit'=>'Nos','tax_profile_id'=>'solar-split']]);json_save(documents_inventory_component_variants_path(),[['id'=>'panel-500','component_id'=>'panel','display_name'=>'500Wp','brand'=>'Master Brand','model_no'=>'M500']]);
 $master=documents_standalone_apply_master_items($invoice,[['type'=>'component','component_id'=>'panel','variant_id'=>'panel-500','quantity'=>2,'unit_price_incl_gst'=>590]]);issue963($master['ok'],'Items Master line accepted');issue963(($master['invoice']['commercial_items'][0]['name']??'')==='Panel (500Wp)'&&($master['invoice']['commercial_items'][0]['hsn']??'')==='8541','master name, variant and HSN snapshotted '.json_encode($master['invoice']['commercial_items'][0]??[]));issue963(count($master['invoice']['commercial_items'][0]['slabs']??[])===2,'master split tax profile applied');$forged=documents_standalone_apply_master_items($invoice,[['type'=>'component','component_id'=>'missing','quantity'=>1,'unit_price_incl_gst'=>1]]);issue963(!$forged['ok'],'unknown master selection rejected');
 $items=documents_standalone_apply_items($invoice,[['name'=>'Panel service','description'=>'Manual line','hsn'=>'9983','quantity'=>2,'unit'=>'Nos','unit_price_incl_gst'=>590,'gst_rate'=>18],['name'=>'Cable','hsn'=>'8544','quantity'=>1,'unit'=>'Lot','unit_price_incl_gst'=>118,'gst_rate'=>18]]);issue963($items['ok'],'manual lines accepted');$invoice=$items['invoice'];issue963(documents_invoice_final_total($invoice)===1298.0,'line gross total');$tax=documents_invoice_tax_summary($invoice);issue963(abs($tax['taxable']+$tax['gst']-$tax['gross'])<.01,'tax reconciliation');issue963(documents_save_invoice($invoice)['ok'],'draft saves');$loaded=documents_get_invoice($invoice['id']);issue963($loaded['invoice_no']==='MANUAL/77'&&documents_invoice_authoritative_date($loaded)==='2026-08-01','draft number/date editable');issue963(($loaded['manual_reference']['quotation_no']??'')==='DE/OLD/123'&&($loaded['quotation_id']??'')==='','manual reference is metadata');
 $store=new CustomerFsStore($root.'/customers');$add=$store->addCustomer(['name'=>'Portal Owner','mobile'=>'9876543210','address'=>'Saved address','city'=>'Ranchi']);issue963($add['success'],'customer fixture');$match=documents_standalone_match_customer($loaded,'+91 98765 43210',$store,true);$linked=$match['invoice'];issue963($match['linked']&&($linked['customer_ref']['type']??'')==='customer_user','mobile links customer');issue963(($linked['customer_snapshot']['name']??'')==='Portal Owner','customer prefills');$original=$store->findByMobile('9876543210');$linked['customer_snapshot']['name']='Invoice-only name';issue963(($store->findByMobile('9876543210')['name']??'')===($original['name']??''),'invoice snapshot does not overwrite customer');$unmatched=documents_standalone_match_customer($linked,'9999999999',$store);issue963(!$unmatched['linked']&&empty($unmatched['invoice']['customer_ref']),'mobile change safely unlinks');$relinked=documents_standalone_match_customer($unmatched['invoice'],'9876543210',$store);issue963($relinked['linked'],'mobile change safely relinks');$linked=$relinked['invoice'];documents_save_invoice($linked);
 $pay=documents_add_standalone_invoice_payment($linked,['amount'=>'500','date_received'=>'2026-08-01','mode'=>'UPI','transaction_reference'=>'TX1','receipt_number'=>'R-1'],['id'=>'1']);issue963($pay['ok'],'canonical receipt saved');$summary=documents_invoice_payment_summary($linked);issue963($summary['total_received']===500.0&&$summary['outstanding']===798.0,'payment summary');documents_add_standalone_invoice_payment($linked,['amount'=>'1000','date_received'=>'2026-08-01']);$summary=documents_invoice_payment_summary($linked);issue963($summary['overpayment']===202.0&&$summary['payment_status']==='overpaid','overpayment');
 $other=documents_create_standalone_invoice()['invoice'];$other=documents_standalone_apply_items($other,[['name'=>'Other','quantity'=>1,'unit_price_incl_gst'=>100,'gst_rate'=>0]])['invoice'];issue963(documents_invoice_payment_summary($other)['total_received']===0.0,'payments cannot cross allocate');issue963(documents_standalone_invoice_owned_by_customer($linked,$original),'owner authorized');issue963(!documents_standalone_invoice_owned_by_customer($linked,['id'=>'other','mobile'=>'9000000000']),'other customer denied');issue963(documents_customer_visible_standalone_invoice($linked),'active draft visible');$arch=documents_set_archived($linked,['id'=>'1']);issue963(!documents_customer_visible_standalone_invoice($arch),'archived hidden');
 $final=documents_invoice_finalize($linked,['id'=>'1']);issue963($final['ok'],'finalize');$revision=documents_invoice_start_revision($final['invoice'],['id'=>'1'],'Correction');issue963($revision['ok'],'revision');$cancel=documents_invoice_cancel($revision['invoice'],['id'=>'1'],'Cancelled manually');issue963($cancel['ok'],'cancel');
 $admin=file_get_contents(__DIR__.'/../admin-invoices.php');$dash=file_get_contents(__DIR__.'/../customer-dashboard.php');$view=file_get_contents(__DIR__.'/../invoice-view.php');issue963(str_contains($admin,'Create Invoice')&&str_contains($admin,'documents_create_standalone_invoice'),'admin entry point');issue963(str_contains($admin,"safe_text(\$_GET['action'] ?? '') === 'search_customers'")&&str_contains($admin,'if (count($matches) >= 20)'),'customer lookup uses bounded endpoint instead of embedding full store');issue963(str_contains($dash,'Standalone Invoices'),'dashboard section');issue963(str_contains($view,'Standalone invoice'),'current renderer source label');
 echo "standalone_invoice_test passed ($n assertions)\n";
}finally{foreach($inventoryFixtures as $path=>$contents){if($contents===null){if(is_file($path))unlink($path);}else file_put_contents($path,$contents);}$it=is_dir($root)?new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST):null;if($it)foreach($it as $f){$f->isDir()?rmdir($f->getPathname()):unlink($f->getPathname());}if(is_dir($root))rmdir($root);}
