<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/task_workflow.php';
function ok(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function rejects(callable $fn,string $part):void{try{$fn();throw new RuntimeException('accepted invalid operation');}catch(TaskWorkflowException $e){ok(str_contains($e->getMessage(),$part),$e->getMessage());}}
function lastPayload(PDO $db,int $id):array{$q=$db->prepare('SELECT event_data FROM task_events WHERE task_id=? ORDER BY id DESC LIMIT 1');$q->execute([$id]);return json_decode((string)$q->fetchColumn(),true,512,JSON_THROW_ON_ERROR);}
function recipientIs(array $p,string $type,?int $uid=null):bool{foreach($p['intended_recipients'] as $r)if($r['type']===$type&&($uid===null||($r['user_id']??null)===$uid))return true;return false;}
$root=sys_get_temp_dir().'/workflow-'.bin2hex(random_bytes(4));mkdir($root,0770,true);$db=new PDO('sqlite:'.$root.'/test.sqlite',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);initialize_schema($db);seed_defaults($db);canonical_work_initialize_schema($db);
$roles=[];foreach($db->query('SELECT id,name FROM roles') as $r)$roles[$r['name']]=$r['id'];$add=$db->prepare('INSERT INTO users(full_name,email,username,password_hash,role_id,status) VALUES(?,?,?,?,?,?)');foreach([['Admin','a@x.test','a','x','admin'],['Employee One','e1@x.test','e1','x','employee'],['Employee Two','e2@x.test','e2','x','employee']] as $u)$add->execute([$u[0],$u[1],$u[2],$u[3],$roles[$u[4]],'active']);$admin=['id'=>(int)$db->query("SELECT id FROM users WHERE username='a'")->fetchColumn(),'role_name'=>'admin'];$e1=['id'=>(int)$db->query("SELECT id FROM users WHERE username='e1'")->fetchColumn(),'role_name'=>'employee'];$e2=['id'=>(int)$db->query("SELECT id FROM users WHERE username='e2'")->fetchColumn(),'role_name'=>'employee'];$clock=static fn()=>new DateTimeImmutable('2026-08-01 12:00:00',new DateTimeZone('Asia/Kolkata'));$asAdmin=new TaskWorkflowService($db,$admin,$root.'/files',$clock);$asE1=new TaskWorkflowService($db,$e1,$root.'/files',$clock);$asE2=new TaskWorkflowService($db,$e2,$root.'/files',$clock);
$initialTaskCount=(int)$db->query('SELECT COUNT(*) FROM portal_tasks')->fetchColumn();
$base=['title'=>'Inspect site','description'=>'Detailed instructions','expected_outcome'=>'Signed report','assignee_id'=>$e1['id'],'priority'=>'urgent','frequency_type'=>'weekly','due_date'=>'2026-08-01'];
rejects(fn()=>$asE1->create($base),'Only an administrator');$t=$asAdmin->create($base);ok($t['workflow_status']==='assigned'&&$t['status']==='todo'&&$t['responsibility']==='employee','create projection/routing');rejects(fn()=>$asE2->detail((int)$t['id']),'only your assigned');rejects(fn()=>$asE1->transition((int)$t['id'],1,'approve'),'not permitted');rejects(fn()=>$asE1->transition((int)$t['id'],0,'acknowledge'),'version is required');
$t=$asE1->transition((int)$t['id'],1,'acknowledge');$t=$asE1->transition((int)$t['id'],2,'start');$t=$asE1->post((int)$t['id'],3,'progress','Half complete');ok($t['responsibility']==='admin','employee message routes admin');$t=$asAdmin->post((int)$t['id'],4,'reply','Continue');ok($t['responsibility']==='employee','admin reply routes employee');$t=$asE1->transition((int)$t['id'],5,'block','Need site key');ok($t['workflow_status']==='blocked'&&$t['responsibility']==='admin','block flow');$t=$asAdmin->transition((int)$t['id'],6,'blocker_resolve','Key arranged');$t=$asE1->transition((int)$t['id'],7,'submit','Work complete');ok($t['workflow_status']==='submitted'&&$t['status']==='in_progress','submit compatibility');$before=(int)$db->query('SELECT COUNT(*) FROM portal_tasks')->fetchColumn();ok($before===$initialTaskCount+1,'submission created recurrence');$t=$asAdmin->transition((int)$t['id'],8,'correction','Add meter photo');$t=$asE1->transition((int)$t['id'],9,'correction_resume');$t=$asE1->transition((int)$t['id'],10,'submit','Corrected report');$t=$asAdmin->transition((int)$t['id'],11,'approve','Accepted');ok($t['workflow_status']==='completed'&&$t['status']==='done'&&$t['responsibility']==='none','approval final state');ok((int)$db->query('SELECT COUNT(*) FROM portal_tasks')->fetchColumn()===$initialTaskCount+2,'approval did not create one recurrence');
$next=$db->query('SELECT * FROM portal_tasks WHERE parent_task_id='.(int)$t['id'])->fetch();ok($next&&$next['workflow_status']==='assigned'&&$next['due_date']==='2026-08-08','on-time weekly recurrence lineage/date');ok(recipientIs(lastPayload($db,(int)$next['id']),'user',$e1['id']),'recurrence assignment recipient');$t=$asAdmin->transition((int)$t['id'],12,'reopen','Audit discrepancy');ok($t['workflow_status']==='in_progress','reopen');$t=$asAdmin->transition((int)$t['id'],13,'cancel','No longer required');$t=$asAdmin->archive((int)$t['id'],14,true);ok((int)$t['archived_flag']===1,'archive');rejects(fn()=>$asE1->archive((int)$t['id'],15,false),'Only an administrator');
$proof=$asAdmin->create($base+['title'=>'Proof task','proof_required'=>1,'frequency_type'=>'once']);$proof=$asE1->transition((int)$proof['id'],1,'acknowledge');$proof=$asE1->transition((int)$proof['id'],2,'start');rejects(fn()=>$asE1->transition((int)$proof['id'],3,'submit','Done'),'Proof attachment');$tmp=$root.'/proof.txt';file_put_contents($tmp,'evidence');$proof=$asE1->upload((int)$proof['id'],3,['name'=>'proof.txt','tmp_name'=>$tmp,'size'=>8,'error'=>0,'_test'=>true]);$attachment=$proof['attachments'][0];ok(recipientIs(lastPayload($db,(int)$proof['id']),'audience'),'employee proof recipient');rejects(fn()=>$asE2->attachment((int)$attachment['id']),'access denied');ok(is_file($asE1->attachment((int)$attachment['id'])['path']),'authorized attachment');$bad=$root.'/bad.php';file_put_contents($bad,'<?php');rejects(fn()=>$asE1->upload((int)$proof['id'],4,['name'=>'bad.php','tmp_name'=>$bad,'size'=>5,'error'=>0,'_test'=>true]),'Unsupported');$proof=$asE1->transition((int)$proof['id'],4,'submit','Evidence supplied');rejects(fn()=>$asAdmin->transition((int)$proof['id'],4,'approve'),'updated');
$reassign=$asAdmin->create($base+['title'=>'Reassign','frequency_type'=>'once']);$reassign=$asAdmin->reassign((int)$reassign['id'],1,$e2['id']);ok((int)$reassign['assignee_id']===$e2['id']&&$reassign['workflow_status']==='assigned','reassignment');rejects(fn()=>$asE1->detail((int)$reassign['id']),'only your assigned');
$events=(int)$db->query('SELECT COUNT(*) FROM task_events')->fetchColumn();try{$db->exec('UPDATE task_events SET event_type="tampered"');throw new RuntimeException('events mutable');}catch(PDOException $e){}ok((int)$db->query('SELECT COUNT(*) FROM task_events')->fetchColumn()===$events,'events lost');

// #920 validation and routing regressions.
$add->execute(['Inactive','off@x.test','off','x',$roles['employee'],'inactive']);
$add->execute(['Customer','c@x.test','c','x',$roles['customer'],'active']);
foreach(['abc',0,$admin['id'],(int)$db->query("SELECT id FROM users WHERE username='off'")->fetchColumn(),(int)$db->query("SELECT id FROM users WHERE username='c'")->fetchColumn(),999999] as $badAssignee)rejects(fn()=>$asAdmin->create(array_merge($base,['assignee_id'=>$badAssignee,'frequency_type'=>'once'])),'valid active employee');
rejects(fn()=>$asAdmin->create(array_merge($base,['start_date'=>'2026-08-02','due_date'=>'2026-08-01'])),'after due');
rejects(fn()=>$asAdmin->create(array_merge($base,['due_time'=>'25:61'])),'due time');
rejects(fn()=>$asAdmin->create(array_merge($base,['linked_entity_type'=>'lead'])),'linked entity');
rejects(fn()=>$asAdmin->create(array_merge($base,['frequency_type'=>'custom','custom_every_n_days'=>0])),'at least one day');
$direct=$asAdmin->create(array_merge($base,['title'=>'Direct start','frequency_type'=>'once']));$direct=$asE1->transition((int)$direct['id'],1,'start');ok($direct['acknowledged_at']&&$direct['started_at'],'direct start did not audit acknowledgement/start');
$direct=$asE1->transition((int)$direct['id'],2,'block','Waiting for access');ok($direct['responsibility']==='admin'&&$direct['attention_owner_id']===null,'admin audience incorrectly has a user owner');
$direct=$asAdmin->transition((int)$direct['id'],3,'blocker_respond','Still investigating');ok($direct['workflow_status']==='blocked'&&$direct['responsibility']==='admin','keep-blocked response failed');
$direct=$asAdmin->transition((int)$direct['id'],4,'blocker_resolve','Access restored');ok($direct['workflow_status']==='in_progress'&&(int)$direct['attention_owner_id']===$e1['id'],'resolution did not route to assignee');
$direct=$asE1->transition((int)$direct['id'],5,'submit','First result');ok($direct['submitted_at']!==null,'submission timestamp missing');$firstSubmitted=$direct['submitted_at'];
$direct=$asAdmin->transition((int)$direct['id'],6,'correction','Correct readings');$direct=$asE1->transition((int)$direct['id'],7,'correction_resume');ok($direct['correction_acknowledged_at']!==null,'correction acknowledgement missing');$direct=$asE1->transition((int)$direct['id'],8,'submit','Corrected result');$direct=$asAdmin->transition((int)$direct['id'],9,'approve','Accepted');ok($direct['approved_at']&&$direct['approved_by']==$admin['id']&&$direct['completed_at']&&$direct['last_completed_at'],'approval timestamp projection incomplete');ok($direct['responsibility']==='none'&&$direct['attention_owner_id']===null,'closed routing inconsistent');
$catalog=[];foreach($direct['events'] as $event){$payload=json_decode($event['event_data'],true);foreach(['task_id','occurrence_number','series_id','event_type','actor','old_workflow_state','new_workflow_state','old_assignee_id','new_assignee_id','responsibility','intended_recipients','occurred_at','task_version','deep_links'] as $key)ok(array_key_exists($key,$payload),'event contract missing '.$key);$catalog[]=$event['event_type'];}foreach(['assigned','started','blocker_reported','blocker_response','blocker_resolved','submitted','correction_requested','correction_resumed','approved'] as $type)ok(in_array($type,$catalog,true),'event catalog missing '.$type);
$direct=$asAdmin->transition((int)$direct['id'],10,'reopen','Post-approval audit');ok($direct['approved_at']===null&&$direct['completed_at']===null&&$direct['submitted_at']===null&&$direct['last_completed_at']!==null,'reopen timestamp clearing/history failed');
// Deterministic merged timeline and legacy contradictory-row backfill.
$last='';foreach($direct['timeline'] as $entry){ok($entry['created_at']>=$last,'timeline is not chronological');$last=$entry['created_at'];}
$db->prepare("UPDATE portal_tasks SET responsibility='admin',attention_owner_id=? WHERE id=?")->execute([$e1['id'],$direct['id']]);canonical_work_initialize_schema($db);ok($db->query('SELECT attention_owner_id FROM portal_tasks WHERE id='.(int)$direct['id'])->fetchColumn()===false||$db->query('SELECT attention_owner_id FROM portal_tasks WHERE id='.(int)$direct['id'])->fetchColumn()===null,'contradictory admin routing not backfilled');

// Post-merge #920 event routing, links, recurrence, reset, and closed-state audit.
ok(TaskWorkflowService::taskLink('employee',['id'=>7,'workflow_status'=>'completed','archived_flag'=>0])==='employee-tasks.php?view=completed&task=7#task-7','completed employee link');
ok(TaskWorkflowService::taskLink('admin',['id'=>8,'workflow_status'=>'cancelled','archived_flag'=>0])==='admin-tasks.php?view=cancelled&task=8#task-8','cancelled admin link');
ok(TaskWorkflowService::taskLink('employee',['id'=>9,'workflow_status'=>'completed','archived_flag'=>1])==='employee-tasks.php?view=archived&task=9#task-9','archived employee link');
$route=$asAdmin->create($base+['title'=>'Recipient audit','frequency_type'=>'once']);$p=lastPayload($db,(int)$route['id']);ok(recipientIs($p,'user',$e1['id'])&&str_contains($p['deep_links'][0],'employee-tasks.php?view=active'),'assignment recipient/link');
$route=$asE1->transition((int)$route['id'],1,'acknowledge');ok(recipientIs(lastPayload($db,(int)$route['id']),'audience'),'ack recipient');
$route=$asE1->transition((int)$route['id'],2,'start');ok(recipientIs(lastPayload($db,(int)$route['id']),'audience'),'start recipient');
$route=$asE1->post((int)$route['id'],3,'reply','Question');ok(recipientIs(lastPayload($db,(int)$route['id']),'audience'),'employee reply recipient');
$route=$asAdmin->post((int)$route['id'],4,'reply','Answer');ok(recipientIs(lastPayload($db,(int)$route['id']),'user',$e1['id']),'admin reply recipient');
$route=$asE1->post((int)$route['id'],5,'progress','Update');ok(recipientIs(lastPayload($db,(int)$route['id']),'audience'),'progress recipient');
$route=$asE1->transition((int)$route['id'],6,'block','Blocked');ok(recipientIs(lastPayload($db,(int)$route['id']),'audience'),'block report recipient');
$route=$asAdmin->transition((int)$route['id'],7,'blocker_respond','Wait');$p=lastPayload($db,(int)$route['id']);ok($p['responsibility']==='admin'&&recipientIs($p,'user',$e1['id']),'responsibility/recipient separation');
$route=$asAdmin->transition((int)$route['id'],8,'blocker_resolve','Fixed');ok(recipientIs(lastPayload($db,(int)$route['id']),'user',$e1['id']),'block resolution recipient');
$route=$asE1->transition((int)$route['id'],9,'submit','Submit');ok(recipientIs(lastPayload($db,(int)$route['id']),'audience'),'submission recipient');
$route=$asAdmin->transition((int)$route['id'],10,'correction','Fix');ok(recipientIs(lastPayload($db,(int)$route['id']),'user',$e1['id']),'correction recipient');
$route=$asE1->transition((int)$route['id'],11,'correction_resume');ok(recipientIs(lastPayload($db,(int)$route['id']),'audience'),'correction resume recipient');
$route=$asE1->transition((int)$route['id'],12,'submit','Resubmit');ok(lastPayload($db,(int)$route['id'])['event_type']==='resubmitted'&&recipientIs(lastPayload($db,(int)$route['id']),'audience'),'resubmission contract');
$route=$asAdmin->transition((int)$route['id'],13,'approve','Approved');$p=lastPayload($db,(int)$route['id']);ok($p['responsibility']==='none'&&recipientIs($p,'user',$e1['id'])&&str_contains($p['deep_links'][0],'view=completed'),'approval notification/link');
rejects(fn()=>$asAdmin->reassign((int)$route['id'],14,$e2['id']),'Closed or archived');rejects(fn()=>$asAdmin->revise((int)$route['id'],14,'2026-09-01',null,'high'),'Closed or archived');
$tmpClosed=$root.'/closed.txt';file_put_contents($tmpClosed,'closed');rejects(fn()=>$asE1->upload((int)$route['id'],14,['name'=>'closed.txt','tmp_name'=>$tmpClosed,'size'=>6,'error'=>0,'_test'=>true]),'Closed or archived');
$route=$asAdmin->transition((int)$route['id'],14,'reopen','Reopen');ok(recipientIs(lastPayload($db,(int)$route['id']),'user',$e1['id']),'reopen recipient');
$route=$asAdmin->transition((int)$route['id'],15,'cancel','Cancel');$p=lastPayload($db,(int)$route['id']);ok(recipientIs($p,'user',$e1['id'])&&str_contains($p['deep_links'][0],'view=cancelled'),'cancel recipient/link');
$route=$asAdmin->archive((int)$route['id'],16,true);$p=lastPayload($db,(int)$route['id']);ok($p['intended_recipients']===[]&&TaskWorkflowService::taskLink('admin',$route)==='admin-tasks.php?view=archived&task='.$route['id'].'#task-'.$route['id'],'archive no-recipient/link');
$route=$asAdmin->archive((int)$route['id'],17,false);ok(lastPayload($db,(int)$route['id'])['event_type']==='unarchived','unarchive event');
$stale=$asAdmin->create($base+['title'=>'Reset projections','frequency_type'=>'once']);$stale=$asE1->transition((int)$stale['id'],1,'start');$stale=$asE1->transition((int)$stale['id'],2,'submit','Old submission');$stale=$asAdmin->reassign((int)$stale['id'],3,$e2['id']);foreach(['acknowledged_at','started_at','submitted_at','submission_summary','correction_acknowledged_at','approved_at','approved_by','approval_note','completed_at','cancelled_at','archived_at','closed_reason'] as $field)ok($stale[$field]===null,'reassign did not clear '.$field);ok(recipientIs(lastPayload($db,(int)$stale['id']),'user',$e2['id']),'reassignment recipient');
$stale=$asAdmin->revise((int)$stale['id'],4,'2026-09-01',null,'high');ok(recipientIs(lastPayload($db,(int)$stale['id']),'user',$e2['id']),'revision recipient');
foreach([['weekly',0,7],['monthly',0,28],['custom',10,10]] as [$frequency,$custom,$minimum]){$oldDue=$frequency==='weekly'?'2025-01-01':'2026-01-01';$rec=$asAdmin->create($base+['title'=>'Late '.$frequency,'frequency_type'=>$frequency,'custom_every_n_days'=>$custom,'due_date'=>$oldDue]);$rec=$asE1->transition((int)$rec['id'],1,'start');$rec=$asE1->transition((int)$rec['id'],2,'submit','done');$rec=$asAdmin->transition((int)$rec['id'],3,'approve','ok');$child=$db->query('SELECT * FROM portal_tasks WHERE parent_task_id='.(int)$rec['id'])->fetch();ok($child['due_date']>'2026-08-01','late '.$frequency.' recurrence is not future');$count=(int)$db->query('SELECT COUNT(*) FROM portal_tasks WHERE parent_task_id='.(int)$rec['id'])->fetchColumn();rejects(fn()=>$asAdmin->transition((int)$rec['id'],3,'approve','retry'),'updated');ok((int)$db->query('SELECT COUNT(*) FROM portal_tasks WHERE parent_task_id='.(int)$rec['id'])->fetchColumn()===$count,'duplicate recurrence');}

echo "task workflow tests passed\n";
