<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/task_workflow.php';
function ok(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function rejects(callable $fn,string $part):void{try{$fn();throw new RuntimeException('accepted invalid operation');}catch(TaskWorkflowException $e){ok(str_contains($e->getMessage(),$part),$e->getMessage());}}
$root=sys_get_temp_dir().'/workflow-'.bin2hex(random_bytes(4));mkdir($root,0770,true);$db=new PDO('sqlite:'.$root.'/test.sqlite',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);initialize_schema($db);seed_defaults($db);canonical_work_initialize_schema($db);
$roles=[];foreach($db->query('SELECT id,name FROM roles') as $r)$roles[$r['name']]=$r['id'];$add=$db->prepare('INSERT INTO users(full_name,email,username,password_hash,role_id,status) VALUES(?,?,?,?,?,?)');foreach([['Admin','a@x.test','a','x','admin'],['Employee One','e1@x.test','e1','x','employee'],['Employee Two','e2@x.test','e2','x','employee']] as $u)$add->execute([$u[0],$u[1],$u[2],$u[3],$roles[$u[4]],'active']);$admin=['id'=>(int)$db->query("SELECT id FROM users WHERE username='a'")->fetchColumn(),'role_name'=>'admin'];$e1=['id'=>(int)$db->query("SELECT id FROM users WHERE username='e1'")->fetchColumn(),'role_name'=>'employee'];$e2=['id'=>(int)$db->query("SELECT id FROM users WHERE username='e2'")->fetchColumn(),'role_name'=>'employee'];$asAdmin=new TaskWorkflowService($db,$admin,$root.'/files');$asE1=new TaskWorkflowService($db,$e1,$root.'/files');$asE2=new TaskWorkflowService($db,$e2,$root.'/files');
$initialTaskCount=(int)$db->query('SELECT COUNT(*) FROM portal_tasks')->fetchColumn();
$base=['title'=>'Inspect site','description'=>'Detailed instructions','expected_outcome'=>'Signed report','assignee_id'=>$e1['id'],'priority'=>'urgent','frequency_type'=>'weekly','due_date'=>'2026-08-01'];
rejects(fn()=>$asE1->create($base),'Only an administrator');$t=$asAdmin->create($base);ok($t['workflow_status']==='assigned'&&$t['status']==='todo'&&$t['responsibility']==='employee','create projection/routing');rejects(fn()=>$asE2->detail((int)$t['id']),'only your assigned');rejects(fn()=>$asE1->transition((int)$t['id'],1,'approve'),'not permitted');rejects(fn()=>$asE1->transition((int)$t['id'],0,'acknowledge'),'version is required');
$t=$asE1->transition((int)$t['id'],1,'acknowledge');$t=$asE1->transition((int)$t['id'],2,'start');$t=$asE1->post((int)$t['id'],3,'progress','Half complete');ok($t['responsibility']==='admin','employee message routes admin');$t=$asAdmin->post((int)$t['id'],4,'reply','Continue');ok($t['responsibility']==='employee','admin reply routes employee');$t=$asE1->transition((int)$t['id'],5,'block','Need site key');ok($t['workflow_status']==='blocked'&&$t['responsibility']==='admin','block flow');$t=$asAdmin->transition((int)$t['id'],6,'admin_response','Key arranged');$t=$asE1->transition((int)$t['id'],7,'submit','Work complete');ok($t['workflow_status']==='submitted'&&$t['status']==='in_progress','submit compatibility');$before=(int)$db->query('SELECT COUNT(*) FROM portal_tasks')->fetchColumn();ok($before===$initialTaskCount+1,'submission created recurrence');$t=$asAdmin->transition((int)$t['id'],8,'correction','Add meter photo');$t=$asE1->transition((int)$t['id'],9,'start');$t=$asE1->transition((int)$t['id'],10,'submit','Corrected report');$t=$asAdmin->transition((int)$t['id'],11,'approve','Accepted');ok($t['workflow_status']==='completed'&&$t['status']==='done'&&$t['responsibility']==='none','approval final state');ok((int)$db->query('SELECT COUNT(*) FROM portal_tasks')->fetchColumn()===$initialTaskCount+2,'approval did not create one recurrence');
$next=$db->query('SELECT * FROM portal_tasks WHERE parent_task_id='.(int)$t['id'])->fetch();ok($next&&$next['workflow_status']==='assigned','recurrence lineage');$t=$asAdmin->transition((int)$t['id'],12,'reopen','Audit discrepancy');ok($t['workflow_status']==='in_progress','reopen');$t=$asAdmin->transition((int)$t['id'],13,'cancel','No longer required');$t=$asAdmin->archive((int)$t['id'],14,true);ok((int)$t['archived_flag']===1,'archive');rejects(fn()=>$asE1->archive((int)$t['id'],15,false),'Only an administrator');
$proof=$asAdmin->create($base+['title'=>'Proof task','proof_required'=>1,'frequency_type'=>'once']);$proof=$asE1->transition((int)$proof['id'],1,'acknowledge');$proof=$asE1->transition((int)$proof['id'],2,'start');rejects(fn()=>$asE1->transition((int)$proof['id'],3,'submit','Done'),'Proof attachment');$tmp=$root.'/proof.txt';file_put_contents($tmp,'evidence');$proof=$asE1->upload((int)$proof['id'],3,['name'=>'proof.txt','tmp_name'=>$tmp,'size'=>8,'error'=>0,'_test'=>true]);$attachment=$proof['attachments'][0];rejects(fn()=>$asE2->attachment((int)$attachment['id']),'access denied');ok(is_file($asE1->attachment((int)$attachment['id'])['path']),'authorized attachment');$bad=$root.'/bad.php';file_put_contents($bad,'<?php');rejects(fn()=>$asE1->upload((int)$proof['id'],4,['name'=>'bad.php','tmp_name'=>$bad,'size'=>5,'error'=>0,'_test'=>true]),'Unsupported');$proof=$asE1->transition((int)$proof['id'],4,'submit','Evidence supplied');rejects(fn()=>$asAdmin->transition((int)$proof['id'],4,'approve'),'changed');
$reassign=$asAdmin->create($base+['title'=>'Reassign','frequency_type'=>'once']);$reassign=$asAdmin->reassign((int)$reassign['id'],1,$e2['id']);ok((int)$reassign['assignee_id']===$e2['id']&&$reassign['workflow_status']==='assigned','reassignment');rejects(fn()=>$asE1->detail((int)$reassign['id']),'only your assigned');
$events=(int)$db->query('SELECT COUNT(*) FROM task_events')->fetchColumn();try{$db->exec('UPDATE task_events SET event_type="tampered"');throw new RuntimeException('events mutable');}catch(PDOException $e){}ok((int)$db->query('SELECT COUNT(*) FROM task_events')->fetchColumn()===$events,'events lost');
echo "task workflow tests passed\n";
