<?php
declare(strict_types=1);require_once __DIR__.'/../includes/task_workflow.php';
function concurrency_db(string $path):PDO{$db=new PDO('sqlite:'.$path,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_TIMEOUT=>5]);$db->exec('PRAGMA busy_timeout=5000');return $db;}
if(($argv[1]??'')==='worker'){$db=concurrency_db($argv[3]);while(!is_file($argv[4]))usleep(1000);$mode=$argv[2];for($attempt=0;$attempt<3;$attempt++){try{if($mode==='fallback')echo task_notification_fallback($db)?'winner':'loser';elseif($mode==='reminder'){task_notification_generate_reminders($db,new DateTimeImmutable('2030-01-01',new DateTimeZone('Asia/Kolkata')),20);echo 'ok';}elseif($mode==='pending'){task_notification_project_pending($db,20);echo 'ok';}else{task_notification_project_event($db,(int)$argv[5]);echo 'ok';}exit(0);}catch(PDOException $e){if(!str_contains(strtolower($e->getMessage()),'locked')||$attempt===2)throw $e;usleep(100000);}}}
function concurrency_assert(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function race(string|array $mode,string $dbPath,string $event='0'):array{$gate=sys_get_temp_dir().'/notification-gate-'.bin2hex(random_bytes(4));$procs=[];foreach([0,1] as $index){$workerMode=is_array($mode)?$mode[$index]:$mode;$procs[]=proc_open(['php',__FILE__,'worker',$workerMode,$dbPath,$gate,$event],[['pipe','r'],['pipe','w'],['pipe','w']],$pipes);$streams[]=$pipes;}file_put_contents($gate,'go');$out=[];foreach($procs as $i=>$proc){$out[]=stream_get_contents($streams[$i][1]);$error=stream_get_contents($streams[$i][2]);concurrency_assert(proc_close($proc)===0,(is_array($mode)?implode('/',$mode):$mode).' child failed: '.$error);}@unlink($gate);return $out;}
$path=sys_get_temp_dir().'/notification-race-'.bin2hex(random_bytes(4)).'.sqlite';$db=concurrency_db($path);initialize_schema($db);seed_defaults($db);canonical_work_initialize_schema($db);task_notification_initialize_schema($db);$roles=[];foreach($db->query('SELECT id,name FROM roles') as $r)$roles[$r['name']]=$r['id'];$q=$db->prepare('INSERT INTO users(full_name,email,username,password_hash,role_id,status) VALUES(?,?,?,?,?,?)');$q->execute(['Race Admin','race-admin@test','race-admin','x',$roles['admin'],'active']);$admin=(int)$db->lastInsertId();$q->execute(['Race Employee','race-employee@test','race-employee','x',$roles['employee'],'active']);$employee=(int)$db->lastInsertId();$service=new TaskWorkflowService($db,['id'=>$admin,'role_name'=>'admin'],dirname($path));$task=$service->create(['title'=>'Race reminder','description'=>'x','expected_outcome'=>'x','assignee_id'=>$employee,'priority'=>'high','frequency_type'=>'once','due_date'=>'2020-01-01']);
$db->exec('DELETE FROM notification_leases');$results=race('fallback',$path);sort($results);concurrency_assert($results===['loser','winner'],'two fallback processes elect one lease winner');
$db->exec('DELETE FROM notification_leases');$db->prepare("DELETE FROM portal_notification_status WHERE notification_id IN (SELECT id FROM portal_notifications WHERE source_task_id=? AND category='reminder')")->execute([$task['id']]);$db->prepare("DELETE FROM portal_notifications WHERE source_task_id=? AND category='reminder'")->execute([$task['id']]);race('reminder',$path);$s=$db->prepare("SELECT n.id,COUNT(s.notification_id) statuses FROM portal_notifications n LEFT JOIN portal_notification_status s ON s.notification_id=n.id WHERE n.source_task_id=? AND n.notification_type='overdue_employee' GROUP BY n.id");$s->execute([$task['id']]);$rows=$s->fetchAll();concurrency_assert(count($rows)===1&&(int)$rows[0]['statuses']===1,'racing reminder workers create one canonical row and one status');
$event=(int)$db->query('SELECT MIN(id) FROM task_events')->fetchColumn();$db->prepare('DELETE FROM task_notification_projection WHERE task_event_id=?')->execute([$event]);$db->prepare('DELETE FROM portal_notification_status WHERE notification_id IN (SELECT id FROM portal_notifications WHERE source_task_event_id=?)')->execute([$event]);$db->prepare('DELETE FROM portal_notifications WHERE source_task_event_id=?')->execute([$event]);race(['project','pending'],$path,(string)$event);$s=$db->prepare('SELECT n.id,COUNT(s.notification_id) statuses FROM portal_notifications n LEFT JOIN portal_notification_status s ON s.notification_id=n.id WHERE n.source_task_event_id=? GROUP BY n.id');$s->execute([$event]);$rows=$s->fetchAll();concurrency_assert(count($rows)===1&&(int)$rows[0]['statuses']===1,'exact projection and recovery race has no orphan or duplicate');
@unlink($path);echo "task notification concurrency tests passed\n";
