<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/task_workflow.php';
function ok(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function rejects(callable $fn,string $part):void{try{$fn();throw new RuntimeException('accepted invalid operation');}catch(TaskWorkflowException $e){ok(str_contains($e->getMessage(),$part),$e->getMessage());}}
$root=sys_get_temp_dir().'/workflow-'.bin2hex(random_bytes(4));mkdir($root,0770,true);$db=new PDO('sqlite:'.$root.'/test.sqlite',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);initialize_schema($db);seed_defaults($db);canonical_work_initialize_schema($db);
$roles=[];foreach($db->query('SELECT id,name FROM roles') as $r)$roles[$r['name']]=$r['id'];$add=$db->prepare('INSERT INTO users(full_name,email,username,password_hash,role_id,status) VALUES(?,?,?,?,?,?)');foreach([['Admin','a@x.test','a','x','admin'],['Employee One','e1@x.test','e1','x','employee'],['Employee Two','e2@x.test','e2','x','employee']] as $u)$add->execute([$u[0],$u[1],$u[2],$u[3],$roles[$u[4]],'active']);$admin=['id'=>(int)$db->query("SELECT id FROM users WHERE username='a'")->fetchColumn(),'role_name'=>'admin'];$e1=['id'=>(int)$db->query("SELECT id FROM users WHERE username='e1'")->fetchColumn(),'role_name'=>'employee'];$e2=['id'=>(int)$db->query("SELECT id FROM users WHERE username='e2'")->fetchColumn(),'role_name'=>'employee'];$asAdmin=new TaskWorkflowService($db,$admin,$root.'/files');$asE1=new TaskWorkflowService($db,$e1,$root.'/files');$asE2=new TaskWorkflowService($db,$e2,$root.'/files');
$initialTaskCount=(int)$db->query('SELECT COUNT(*) FROM portal_tasks')->fetchColumn();
$base=['title'=>'Inspect site','description'=>'Detailed instructions','expected_outcome'=>'Signed report','assignee_id'=>$e1['id'],'priority'=>'urgent','frequency_type'=>'weekly','due_date'=>'2026-08-01'];
rejects(fn()=>$asE1->create($base),'Only an administrator');$t=$asAdmin->create($base);ok($t['workflow_status']==='assigned'&&$t['status']==='todo'&&$t['responsibility']==='employee','create projection/routing');rejects(fn()=>$asE2->detail((int)$t['id']),'only your assigned');rejects(fn()=>$asE1->transition((int)$t['id'],1,'approve'),'not permitted');rejects(fn()=>$asE1->transition((int)$t['id'],0,'acknowledge'),'version is required');
$t=$asE1->transition((int)$t['id'],1,'acknowledge');$t=$asE1->transition((int)$t['id'],2,'start');$t=$asE1->post((int)$t['id'],3,'progress','Half complete');ok($t['responsibility']==='admin','employee message routes admin');$t=$asAdmin->post((int)$t['id'],4,'reply','Continue');ok($t['responsibility']==='employee','admin reply routes employee');$t=$asE1->transition((int)$t['id'],5,'block','Need site key');ok($t['workflow_status']==='blocked'&&$t['responsibility']==='admin','block flow');$t=$asAdmin->transition((int)$t['id'],6,'blocker_resolve','Key arranged');$t=$asE1->transition((int)$t['id'],7,'submit','Work complete');ok($t['workflow_status']==='submitted'&&$t['status']==='in_progress','submit compatibility');$before=(int)$db->query('SELECT COUNT(*) FROM portal_tasks')->fetchColumn();ok($before===$initialTaskCount+1,'submission created recurrence');$t=$asAdmin->transition((int)$t['id'],8,'correction','Add meter photo');$t=$asE1->transition((int)$t['id'],9,'correction_resume');$t=$asE1->transition((int)$t['id'],10,'submit','Corrected report');$t=$asAdmin->transition((int)$t['id'],11,'approve','Accepted');ok($t['workflow_status']==='completed'&&$t['status']==='done'&&$t['responsibility']==='none','approval final state');ok((int)$db->query('SELECT COUNT(*) FROM portal_tasks')->fetchColumn()===$initialTaskCount+2,'approval did not create one recurrence');
$next=$db->query('SELECT * FROM portal_tasks WHERE parent_task_id='.(int)$t['id'])->fetch();ok($next&&$next['workflow_status']==='assigned','recurrence lineage');$t=$asAdmin->transition((int)$t['id'],12,'reopen','Audit discrepancy');ok($t['workflow_status']==='in_progress','reopen');$t=$asAdmin->transition((int)$t['id'],13,'cancel','No longer required');$t=$asAdmin->archive((int)$t['id'],14,true);ok((int)$t['archived_flag']===1,'archive');rejects(fn()=>$asE1->archive((int)$t['id'],15,false),'Only an administrator');
$proof=$asAdmin->create($base+['title'=>'Proof task','proof_required'=>1,'frequency_type'=>'once']);$proof=$asE1->transition((int)$proof['id'],1,'acknowledge');$proof=$asE1->transition((int)$proof['id'],2,'start');rejects(fn()=>$asE1->transition((int)$proof['id'],3,'submit','Done'),'Proof attachment');$tmp=$root.'/proof.txt';file_put_contents($tmp,'evidence');$proof=$asE1->upload((int)$proof['id'],3,['name'=>'proof.txt','tmp_name'=>$tmp,'size'=>8,'error'=>0,'_test'=>true]);$attachment=$proof['attachments'][0];rejects(fn()=>$asE2->attachment((int)$attachment['id']),'access denied');ok(is_file($asE1->attachment((int)$attachment['id'])['path']),'authorized attachment');$bad=$root.'/bad.php';file_put_contents($bad,'<?php');rejects(fn()=>$asE1->upload((int)$proof['id'],4,['name'=>'bad.php','tmp_name'=>$bad,'size'=>5,'error'=>0,'_test'=>true]),'Unsupported');$proof=$asE1->transition((int)$proof['id'],4,'submit','Evidence supplied');rejects(fn()=>$asAdmin->transition((int)$proof['id'],4,'approve'),'updated');
$reassign=$asAdmin->create($base+['title'=>'Reassign','frequency_type'=>'once']);$reassign=$asAdmin->reassign((int)$reassign['id'],1,$e2['id']);ok((int)$reassign['assignee_id']===$e2['id']&&$reassign['workflow_status']==='assigned','reassignment');rejects(fn()=>$asE1->detail((int)$reassign['id']),'only your assigned');
$events=(int)$db->query('SELECT COUNT(*) FROM task_events')->fetchColumn();try{$db->exec('UPDATE task_events SET event_type="tampered"');throw new RuntimeException('events mutable');}catch(PDOException $e){}ok((int)$db->query('SELECT COUNT(*) FROM task_events')->fetchColumn()===$events,'events lost');

// #920 validation and routing regressions.
$add->execute(['Inactive','off@x.test','off','x',$roles['employee'],'inactive']);
$add->execute(['Customer','c@x.test','c','x',$roles['customer'],'active']);
foreach(['abc',0,$admin['id'],(int)$db->query("SELECT id FROM users WHERE username='off'")->fetchColumn(),(int)$db->query("SELECT id FROM users WHERE username='c'")->fetchColumn(),999999] as $badAssignee)rejects(fn()=>$asAdmin->create(array_merge($base,['assignee_id'=>$badAssignee,'frequency_type'=>'once'])),'valid active employee');
rejects(fn()=>$asAdmin->create(array_merge($base,['start_date'=>'2026-08-02','due_date'=>'2026-08-01'])),'after due');
rejects(fn()=>$asAdmin->create(array_merge($base,['due_time'=>'25:61'])),'due time');
rejects(fn()=>$asAdmin->create(array_merge($base,['linked_entity_type'=>'lead'])),'linked entity');
rejects(fn()=>$asAdmin->create(array_merge($base,['frequency_type'=>'custom','custom_every_n_days'=>0])),'at least one day');
$direct=$asAdmin->create(array_merge($base,['title'=>'Direct start','frequency_type'=>'once']));$direct=$asE1->transition((int)$direct['id'],1,'start');ok($direct['acknowledged_at']&&$direct['started_at'],'direct start did not audit acknowledgement/start');
$direct=$asE1->transition((int)$direct['id'],2,'block','Waiting for access');ok($direct['responsibility']==='admin'&&$direct['attention_owner_id']===null,'admin audience incorrectly has a user owner');
$direct=$asAdmin->transition((int)$direct['id'],3,'blocker_respond','Still investigating');ok($direct['workflow_status']==='blocked'&&$direct['responsibility']==='admin','keep-blocked response failed');
$direct=$asAdmin->transition((int)$direct['id'],4,'blocker_resolve','Access restored');ok($direct['workflow_status']==='in_progress'&&(int)$direct['attention_owner_id']===$e1['id'],'resolution did not route to assignee');
$direct=$asE1->transition((int)$direct['id'],5,'submit','First result');ok($direct['submitted_at']!==null,'submission timestamp missing');$firstSubmitted=$direct['submitted_at'];
$direct=$asAdmin->transition((int)$direct['id'],6,'correction','Correct readings');$direct=$asE1->transition((int)$direct['id'],7,'correction_resume');ok($direct['correction_acknowledged_at']!==null,'correction acknowledgement missing');$direct=$asE1->transition((int)$direct['id'],8,'submit','Corrected result');$direct=$asAdmin->transition((int)$direct['id'],9,'approve','Accepted');ok($direct['approved_at']&&$direct['approved_by']==$admin['id']&&$direct['completed_at']&&$direct['last_completed_at'],'approval timestamp projection incomplete');ok($direct['responsibility']==='none'&&$direct['attention_owner_id']===null,'closed routing inconsistent');
$catalog=[];foreach($direct['events'] as $event){$payload=json_decode($event['event_data'],true);foreach(['task_id','occurrence_number','series_id','event_type','actor','old_workflow_state','new_workflow_state','old_assignee_id','new_assignee_id','responsibility','intended_recipient','occurred_at','task_version','deep_link'] as $key)ok(array_key_exists($key,$payload),'event contract missing '.$key);$catalog[]=$event['event_type'];}foreach(['assigned','started','blocker_reported','blocker_response','blocker_resolved','submitted','correction_requested','correction_resumed','approved'] as $type)ok(in_array($type,$catalog,true),'event catalog missing '.$type);
$direct=$asAdmin->transition((int)$direct['id'],10,'reopen','Post-approval audit');ok($direct['approved_at']===null&&$direct['completed_at']===null&&$direct['submitted_at']===null&&$direct['last_completed_at']!==null,'reopen timestamp clearing/history failed');
// Deterministic merged timeline and legacy contradictory-row backfill.
$last='';foreach($direct['timeline'] as $entry){ok($entry['created_at']>=$last,'timeline is not chronological');$last=$entry['created_at'];}
$db->prepare("UPDATE portal_tasks SET responsibility='admin',attention_owner_id=? WHERE id=?")->execute([$e1['id'],$direct['id']]);canonical_work_initialize_schema($db);ok($db->query('SELECT attention_owner_id FROM portal_tasks WHERE id='.(int)$direct['id'])->fetchColumn()===false||$db->query('SELECT attention_owner_id FROM portal_tasks WHERE id='.(int)$direct['id'])->fetchColumn()===null,'contradictory admin routing not backfilled');

echo "task workflow tests passed\n";
