<?php
declare(strict_types=1);require_once __DIR__.'/../includes/task_workflow.php';
function na(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
$root=sys_get_temp_dir().'/notify-'.bin2hex(random_bytes(4));mkdir($root);$db=new PDO('sqlite:'.$root.'/db',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);initialize_schema($db);seed_defaults($db);canonical_work_initialize_schema($db);task_notification_initialize_schema($db);
$roles=[];foreach($db->query('SELECT id,name FROM roles') as $r)$roles[$r['name']]=$r['id'];$add=$db->prepare('INSERT INTO users(full_name,email,username,password_hash,role_id,status) VALUES(?,?,?,?,?,?)');foreach([['Admin Active','a@n','a','x','admin','active'],['Admin Off','ao@n','ao','x','admin','inactive'],['Employee One','e@n','e','x','employee','active'],['Employee Two','e2@n','e2','x','employee','active']] as $u)$add->execute([$u[0],$u[1],$u[2],$u[3],$roles[$u[4]],$u[5]]);$id=fn($n)=>(int)$db->query("SELECT id FROM users WHERE username='$n'")->fetchColumn();$admin=['id'=>$id('a'),'role_name'=>'admin'];$employee=['id'=>$id('e'),'role_name'=>'employee'];$other=$id('e2');$a=new TaskWorkflowService($db,$admin,$root);$e=new TaskWorkflowService($db,$employee,$root);
$task=$a->create(['title'=>'<b>Safe survey</b>','description'=>'Private instructions','expected_outcome'=>'Report','assignee_id'=>$employee['id'],'priority'=>'high','frequency_type'=>'once','due_date'=>'2026-08-01']);$event=(int)$db->query('SELECT MAX(id) FROM task_events')->fetchColumn();$r=task_notification_project_event($db,$event);na($r['created']===0&&$r['skipped']===1,'assignment projected immediately');na(task_notification_unread_count($db,$employee['id'])===1&&task_notification_unread_count($db,$other)===0,'exact recipient');na(task_notification_project_event($db,$event)['skipped']===1,'event idempotency');$row=task_notification_list($db,$employee['id'])[0];na(!str_contains($row['message'],'<b>')&&!str_contains($row['message'],'Private'),'safe text');na(task_notification_validate_link($row['link'],'employee',(int)$task['id']),'valid link');foreach(['https://evil.test','//evil.test','admin-tasks.php?view=active&task='.$task['id'].'#task-'.$task['id'],'employee-tasks.php?view=active&task=999#task-999'] as $bad)na(!task_notification_validate_link($bad,'employee',(int)$task['id']),'unsafe link accepted');
task_notification_mutate($db,$employee['id'],'read',(int)$row['id']);na(task_notification_unread_count($db,$employee['id'])===0,'mark read');task_notification_mutate($db,$employee['id'],'unread',(int)$row['id']);na(task_notification_unread_count($db,$employee['id'])===1,'mark unread');try{task_notification_mutate($db,$other,'dismiss',(int)$row['id']);throw new RuntimeException('ownership bypass');}catch(OutOfBoundsException $x){}task_notification_mutate($db,$employee['id'],'dismiss',(int)$row['id']);na(task_notification_list($db,$employee['id'])===[],'per-user dismiss');
$task=$e->transition((int)$task['id'],1,'acknowledge');$adminEvent=(int)$db->query('SELECT MAX(id) FROM task_events')->fetchColumn();task_notification_project_event($db,$adminEvent);na(task_notification_unread_count($db,$admin['id'])===1&&task_notification_unread_count($db,$id('ao'))===0,'active admin fanout');task_notification_mutate($db,$admin['id'],'read-all');na(task_notification_unread_count($db,$admin['id'])===0,'mark all');
$cancel=$a->create(['title'=>'Cancel recipient','description'=>'x','expected_outcome'=>'x','assignee_id'=>$employee['id'],'priority'=>'medium','frequency_type'=>'once']);$cancel=$a->transition((int)$cancel['id'],1,'cancel','stop');$cancelEvent=(int)$db->query('SELECT MAX(id) FROM task_events')->fetchColumn();task_notification_project_event($db,$cancelEvent);na(task_notification_unread_count($db,$employee['id'])>=1,'cancellation with responsibility none');
$now=new DateTimeImmutable('2026-08-01 12:00:00',new DateTimeZone('Asia/Kolkata'));$report=task_notification_generate_reminders($db,$now);$again=task_notification_generate_reminders($db,$now);na($report['created']>0&&$again['created']===0&&$again['deduplicated']>0,'reminder deduplication');na((int)$db->query("SELECT COUNT(*) FROM portal_notifications WHERE message LIKE '%Private instructions%'")->fetchColumn()===0,'privacy leak');
echo "task notification tests passed\n";
// Corrective #924 boundaries and invariants.
$state=$db->prepare('SELECT status,read_at,unread_at,dismissed_at FROM portal_notification_status WHERE notification_id=? AND user_id=?');
$owned=(int)$db->query('SELECT notification_id FROM portal_notification_status WHERE user_id='.$admin['id'].' LIMIT 1')->fetchColumn();
task_notification_mutate($db,$admin['id'],'unread',$owned);$state->execute([$owned,$admin['id']]);$x=$state->fetch();na($x['status']==='unread'&&$x['read_at']===null&&$x['dismissed_at']===null&&$x['unread_at']!==null,'unread invariant');
task_notification_mutate($db,$admin['id'],'read',$owned);$state->execute([$owned,$admin['id']]);$x=$state->fetch();na($x['status']==='read'&&$x['read_at']!==null&&$x['unread_at']!==null&&$x['dismissed_at']===null,'read retains unread history');
task_notification_mutate($db,$admin['id'],'dismiss',$owned);$state->execute([$owned,$admin['id']]);$x=$state->fetch();na($x['status']==='dismissed'&&$x['dismissed_at']!==null&&$x['read_at']!==null,'dismiss retains history');
task_notification_mutate($db,$admin['id'],'dismiss',$owned); // idempotent
try{task_notification_mutate($db,$admin['id'],'read',999999);throw new RuntimeException('forged id accepted');}catch(OutOfBoundsException $ok){}

$old=$a->create(['title'=>'Old reassignment','description'=>'x','expected_outcome'=>'x','assignee_id'=>$employee['id'],'priority'=>'medium','frequency_type'=>'once']);
$db->prepare("UPDATE portal_tasks SET created_at='2020-01-01 00:00:00',assigned_at='2020-01-01 00:00:00' WHERE id=?")->execute([$old['id']]);
$old=$a->reassign((int)$old['id'],1,$other);$assigned=$db->query('SELECT assigned_at FROM portal_tasks WHERE id='.(int)$old['id'])->fetchColumn();na($assigned!=='2020-01-01 00:00:00','reassignment resets assigned_at');
$soon=new DateTimeImmutable((string)$assigned,new DateTimeZone('Asia/Kolkata'));$before=task_notification_generate_reminders($db,$soon->modify('+23 hours'));na((int)$db->query("SELECT COUNT(*) FROM portal_notifications WHERE source_task_id=".(int)$old['id']." AND notification_type LIKE 'unacknowledged%'")->fetchColumn()===0,'new reassignment is not prematurely unacknowledged');
task_notification_generate_reminders($db,$soon->modify('+24 hours'));na((int)$db->query("SELECT COUNT(*) FROM portal_notifications WHERE source_task_id=".(int)$old['id']." AND notification_type='unacknowledged_employee'")->fetchColumn()===1,'unacknowledged threshold uses assignment');

$db->prepare('DELETE FROM portal_notification_status WHERE user_id=?')->execute([$other]);
for($i=0;$i<21;$i++){$key='page-'.$i;$db->prepare("INSERT INTO portal_notifications(audience,tone,title,message,created_at,deduplication_key) VALUES('employee','info','Page','Page','2026-08-01 10:00:00',?)")->execute([$key]);$nid=(int)$db->lastInsertId();$db->prepare("INSERT INTO portal_notification_status(notification_id,user_id,status,updated_at,unread_at) VALUES(?,?,'unread','2026-08-01 10:00:00','2026-08-01 10:00:00')")->execute([$nid,$other]);}
$page1=task_notification_page($db,$other,'unread',1,20);na(count($page1['notifications'])===20&&$page1['has_more'],'more-than-page pagination');$db->prepare("UPDATE portal_notification_status SET status='dismissed',dismissed_at='2026-08-01 11:00:00' WHERE user_id=? AND notification_id=(SELECT MIN(notification_id) FROM portal_notification_status WHERE user_id=?)")->execute([$other,$other]);$page1=task_notification_page($db,$other,'unread',1,20);na(count($page1['notifications'])===20&&!$page1['has_more'],'exact full page has no more');na($page1['notifications'][0]['id']>$page1['notifications'][1]['id'],'identical timestamps order by id');

echo "task notification corrective tests passed\n";
