<?php
declare(strict_types=1);require_once __DIR__.'/../includes/task_workflow.php';
function fallback_assert(bool $value,string $message):void{if(!$value)throw new RuntimeException($message);}
$path=sys_get_temp_dir().'/notification-fallback-'.bin2hex(random_bytes(4)).'.sqlite';$db=new PDO('sqlite:'.$path,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$db->exec('PRAGMA busy_timeout=5000');initialize_schema($db);seed_defaults($db);canonical_work_initialize_schema($db);task_notification_initialize_schema($db);
$role=[];foreach($db->query('SELECT id,name FROM roles') as $row)$role[$row['name']]=$row['id'];$insert=$db->prepare('INSERT INTO users(full_name,email,username,password_hash,role_id,status) VALUES(?,?,?,?,?,?)');$insert->execute(['Admin','admin@example.test','admin-test','x',$role['admin'],'active']);$adminId=(int)$db->lastInsertId();$insert->execute(['Worker','worker@example.test','worker','x',$role['employee'],'active']);$employee=(int)$db->lastInsertId();$insert->execute(['Inactive','inactive@example.test','inactive','x',$role['employee'],'inactive']);$inactive=(int)$db->lastInsertId();$admin=['id'=>$adminId,'role_name'=>'admin'];$service=new TaskWorkflowService($db,$admin,dirname($path));
$task=$service->create(['title'=>'Dashboard fallback due','description'=>'x','expected_outcome'=>'x','assignee_id'=>$employee,'priority'=>'high','frequency_type'=>'once','due_date'=>'2020-01-01']);
$db->exec('DELETE FROM notification_leases');$before=task_notification_unread_count($db,$employee);fallback_assert(task_notification_authenticated_fallback($db,['id'=>$employee,'role_name'=>'employee']),'dashboard shell wins lease');fallback_assert(task_notification_unread_count($db,$employee)>$before,'ordinary shell generates reminder without notification centre');
fallback_assert(!task_notification_authenticated_fallback($db,['id'=>$employee,'role_name'=>'employee']),'lease interval prevents repeat');
$db->exec("UPDATE notification_leases SET lease_until='2000-01-01 00:00:00'");fallback_assert(task_notification_authenticated_fallback($db,['id'=>$employee,'role_name'=>'employee']),'expired lease permits another bounded cycle');
fallback_assert(!task_notification_authenticated_fallback($db,['id'=>$inactive,'role_name'=>'employee']),'inactive user cannot trigger');fallback_assert(!task_notification_authenticated_fallback($db,['id'=>$employee,'role_name'=>'customer']),'unsupported role cannot trigger');
$count=task_notification_unread_count($db,$employee);$other=new PDO('sqlite:'.$path,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$other->exec('PRAGMA busy_timeout=50');$other->beginTransaction();$other->query('SELECT * FROM notification_leases')->fetchAll();fallback_assert(task_notification_unread_count($db,$employee)===$count,'count remains scoped and correct while another connection holds lease');$other->rollBack();
$pending=$service->create(['title'=>'Pending projection','description'=>'x','expected_outcome'=>'x','assignee_id'=>$employee,'priority'=>'medium','frequency_type'=>'once']);$event=(int)$db->query('SELECT MAX(id) FROM task_events')->fetchColumn();$db->prepare('DELETE FROM task_notification_projection WHERE task_event_id=?')->execute([$event]);task_notification_project_pending($db,20);fallback_assert((int)$db->query('SELECT COUNT(*) FROM task_notification_projection WHERE task_event_id='.$event)->fetchColumn()===1,'pending event recovery works');
foreach([['Personal',0,'assigned',0],['Completed',1,'completed',0],['Cancelled',1,'cancelled',0],['Archived',1,'assigned',1]] as [$title,$official,$status,$archived]){$t=$service->create(['title'=>$title,'description'=>'x','expected_outcome'=>'x','assignee_id'=>$employee,'priority'=>'high','frequency_type'=>'once','due_date'=>'2020-01-01']);$db->prepare('UPDATE portal_tasks SET official_flag=?,workflow_status=?,archived_flag=? WHERE id=?')->execute([$official,$status,$archived,$t['id']]);task_notification_generate_reminders($db,new DateTimeImmutable('2030-01-01',new DateTimeZone('Asia/Kolkata')),20);$q=$db->prepare("SELECT COUNT(*) FROM portal_notifications WHERE source_task_id=? AND category='reminder'");$q->execute([$t['id']]);fallback_assert((int)$q->fetchColumn()===0,$title.' excluded');}
$broken=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);initialize_schema($broken);seed_defaults($broken);canonical_work_initialize_schema($broken);task_notification_initialize_schema($broken);$broken->exec('DROP TABLE portal_tasks');fallback_assert(!task_notification_fallback($broken),'failed worker is silent');$until=$broken->query("SELECT lease_until FROM notification_leases WHERE lease_key='fallback'")->fetchColumn();fallback_assert(is_string($until)&&$until!=='','failed worker lease expires safely');
@unlink($path);echo "task notification fallback tests passed\n";
