<?php
declare(strict_types=1);

function challan_public_safe(string $value): string { return htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); }
function render_public_challan(array $c, array $company = []): void
{
    $name = trim((string)($company['brand_name'] ?? $company['company_name'] ?? '')) ?: 'Dakshayani Enterprises';
    $address = trim((string)($company['address'] ?? $company['registered_address'] ?? ''));
    $customer = is_array($c['customer_snapshot'] ?? null) ? $c['customer_snapshot'] : [];
    $items = documents_challan_public_items($c);
    ?>
    <article class="document">
      <header class="document-header"><div><?php if(trim((string)($company['logo_path']??''))!==''):?><img class="company-logo" src="<?=challan_public_safe((string)$company['logo_path'])?>" alt="<?=challan_public_safe($name)?> logo"><?php endif;?><h1><?=challan_public_safe($name)?></h1><p>Dakshayani Enterprises</p><?php if($address!==''):?><p><?=challan_public_safe($address)?></p><?php endif;?><p><?=challan_public_safe((string)($company['phone_primary']??''))?><?php if(!empty($company['email_primary'])):?> · <?=challan_public_safe((string)$company['email_primary'])?><?php endif;?></p><p><?php if(!empty($company['gstin'])):?>GSTIN: <?=challan_public_safe((string)$company['gstin'])?><?php endif;?><?php if(!empty($company['website'])):?> · <?=challan_public_safe((string)$company['website'])?><?php endif;?></p></div><div class="document-title"><h2>Delivery Challan</h2><strong><?=challan_public_safe((string)($c['challan_no'] ?: $c['dc_number']))?></strong><p>Status <?=challan_public_safe((string)$c['status'])?></p></div></header>
      <section class="meta"><p><b>Date / version</b><br><?=challan_public_safe((string)($c['delivery_date']??$c['created_at']??''))?> / v<?=challan_public_safe((string)($c['version_no']??$c['revision_no']??1))?></p><p><b>Quotation</b><br><?=challan_public_safe((string)($c['linked_quote_no']??''))?></p><p><b>Agreement</b><br><?=challan_public_safe((string)($c['agreement_no']??$c['agreement_id']??''))?></p><p><b>Dispatch Advice</b><br><?=challan_public_safe((string)($c['dispatch_advice_no']??''))?><br><?=challan_public_safe((string)($c['dispatch_advice_acceptance_ref']??''))?></p><p><b>Delivery date</b><br><?=challan_public_safe((string)($c['delivery_date']??''))?></p></section>
      <?php if(trim((string)($c['vehicle_no']??$c['driver_name']??''))!==''):?><section class="meta"><p><b>Vehicle</b><br><?=challan_public_safe((string)($c['vehicle_no']??''))?></p><p><b>Driver</b><br><?=challan_public_safe((string)($c['driver_name']??''))?></p></section><?php endif;?><section class="meta meta-two"><p><b>Customer</b><br><?=challan_public_safe((string)($customer['name']??$c['customer_name_snapshot']??''))?><br><?=challan_public_safe(customer_acceptance_mask_mobile((string)($customer['mobile']??$c['customer_mobile']??'')))?></p><p><b>Delivery address</b><br><?=nl2br(challan_public_safe((string)($c['delivery_address']??$customer['address']??'')))?></p></section>
      <table><thead><tr><th>#</th><th>Actual delivered item</th><th>Brand / model</th><th>Qty</th><th>Remarks</th></tr></thead><tbody><?php foreach($items as $i=>$r):?><tr><td><?=$i+1?></td><td><strong><?=challan_public_safe((string)$r['name'])?></strong><br><?=challan_public_safe((string)$r['description'])?></td><td><?=challan_public_safe((string)($r['brand_model']??''))?></td><td><?=challan_public_safe((string)$r['qty'])?> <?=challan_public_safe((string)$r['unit'])?></td><td><?=challan_public_safe((string)$r['remarks'])?></td></tr><?php endforeach;?></tbody></table>
      <?php $receipt=(array)($c['customer_receipt'] ?: ($c['customer_acceptance'] ?? [])); ?><section class="meta meta-two"><p><b>Customer receipt confirmation</b><br><?=!empty($receipt['confirmed_at'])?'Confirmed':'Pending'?><?php if(!empty($receipt['acceptance_ref'])):?> · <?=challan_public_safe((string)$receipt['acceptance_ref'])?><?php endif;?></p><p><b>Customer/admin remarks</b><br><?=challan_public_safe((string)(($receipt['customer_remarks']??'')?:($c['delivery_notes']??'Customer confirmed receipt with no remarks'))) ?></p></section><p class="disclaimer"><strong>Privacy note:</strong> This customer copy intentionally excludes warehouse, stock location, batch, lot, purchase-cost, cut-plan, and internal inventory details.</p>
      <footer>For Dakshayani Enterprises — Authorised Signatory</footer>
    </article><?php
}
