<?php
declare(strict_types=1);

require_once __DIR__ . '/../admin/includes/documents_helpers.php';

/** File-only DISCOM workflow. Customer data is copied once and never read through after sending. */
function discom_storage_dir(): string { return defined('DISCOM_STORAGE_DIR') ? (string) DISCOM_STORAGE_DIR : __DIR__ . '/../storage/discom_requests'; }
function discom_contacts_path(): string { return discom_storage_dir() . '/contacts.json'; }
function discom_records_dir(): string { return discom_storage_dir() . '/records'; }
function discom_artifacts_dir(): string { return discom_storage_dir() . '/artifacts'; }
function discom_init(): void { foreach ([discom_storage_dir(),discom_records_dir(),discom_artifacts_dir()] as $d) if (!is_dir($d)) @mkdir($d,0775,true); if(!is_file(discom_contacts_path())) discom_atomic_json(discom_contacts_path(),[]); }
function discom_atomic_json(string $path, array $value): bool { $dir=dirname($path); if(!is_dir($dir)) @mkdir($dir,0775,true); $tmp=tempnam($dir,'.tmp-'); if($tmp===false)return false; $ok=file_put_contents($tmp,json_encode($value,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),LOCK_EX)!==false && @rename($tmp,$path); if(!$ok)@unlink($tmp); return $ok; }
function discom_clean(string $v): string { return trim((string)preg_replace('/\s+/u',' ',$v)); }
function discom_normalize_group(string $v): string { return mb_strtolower(discom_clean($v),'UTF-8'); }
function discom_allowed_roles(): array { return ['admin','employee']; }
function discom_authorized(array $actor): bool { return in_array((string)($actor['role_name']??$actor['role']??''),discom_allowed_roles(),true); }

/** Exact resolution: normalized quotation mobile plus name/context conflict detection. */
function discom_validate_project(array $quote, ?CustomerFsStore $store=null): array {
    $qid=discom_clean((string)($quote['id']??'')); $issues=[]; $customer=null;
    if($qid==='' || (string)($quote['status']??'')!=='accepted' || empty($quote['is_current_version'])) $issues[]='Project is not an eligible current accepted quotation.';
    $link=documents_project_customer_user_link($quote,$store);
    if(in_array((string)$link['state'],['existing','created'],true)) $customer=is_array($link['customer']??null)?$link['customer']:null;
    else $issues[]=$link['state']==='conflict'?'Customer User conflict: '.(string)$link['error']:'Exact Customer User could not be resolved.';
    $fieldMap=['application_id'=>'Application ID','division_name'=>'division','sub_division_name'=>'subdivision','jbvnl_account_number'=>'JBVNL account number','solar_plant_installation_date'=>'solar installation date'];
    $data=['quotation_id'=>$qid,'quotation_reference'=>discom_clean((string)($quote['quote_no']??$qid)),'customer_name'=>discom_clean((string)($customer['name']??'')),'registered_mobile'=>documents_normalize_mobile((string)($customer['mobile']??'')),'address'=>discom_clean((string)($customer['address']??'')),'installed_capacity'=>discom_clean((string)($customer['installed_pv_module_capacity_kwp']??''))];
    foreach($fieldMap as $key=>$label){$data[$key]=discom_clean((string)($customer[$key]??''));if($data[$key]==='')$issues[]='Missing '.$label.'.';}
    if($data['customer_name']==='')$issues[]='Missing customer name.';
    return ['quotation_id'=>$qid,'complete'=>$issues===[],'issues'=>$issues,'data'=>$data,'customer_mobile'=>(string)($link['mobile']??''),'customer_user'=>$customer];
}
function discom_validate_ids(array $ids, array $actor): array {
    $out=['complete'=>[],'blocked'=>[],'invalid'=>[]]; if(!discom_authorized($actor)){ $out['error']='Permission denied.'; return $out; }
    foreach(array_values(array_unique(array_filter(array_map('strval',$ids)))) as $id){$q=documents_get_quote($id);if(!is_array($q)){$out['invalid'][$id]='Project was not found.';continue;}$v=discom_validate_project($q);$out[$v['complete']?'complete':'blocked'][$id]=$v;}
    return $out;
}
function discom_group_projects(array $validated, bool $combine=false): array { $groups=[]; foreach($validated as $row){if(empty($row['complete']))continue;$d=$row['data'];$key=$combine?'combined':discom_normalize_group($d['division_name']).'|'.discom_normalize_group($d['sub_division_name']);$groups[$key][]=$d;} return $groups; }
function discom_default_columns(): array { return ['serial','customer_name','application_id','division_name','sub_division_name','jbvnl_account_number','solar_plant_installation_date']; }
function discom_column_labels(): array { return ['serial'=>'S.No.','customer_name'=>'Customer name','application_id'=>'Application ID','division_name'=>'Division','sub_division_name'=>'Subdivision','jbvnl_account_number'=>'JBVNL account number','solar_plant_installation_date'=>'Installation date','registered_mobile'=>'Registered mobile','installed_capacity'=>'Installed capacity','address'=>'Address','quotation_reference'=>'Quotation / project reference']; }
function discom_project_rows(array $snapshot,array $columns=[]): array {$columns=$columns?:discom_default_columns();$rows=[];foreach(array_values($snapshot) as $i=>$d){$r=[];foreach($columns as $c)$r[$c]=$c==='serial'?(string)($i+1):discom_clean((string)($d[$c]??''));$rows[]=$r;}return $rows;}
function discom_html_table(array $snapshot,array $columns=[]): string {$columns=$columns?:discom_default_columns();$labels=discom_column_labels();$h='<div class="discom-table-wrap"><table class="discom-outgoing-table"><thead><tr>';foreach($columns as $c)$h.='<th>'.htmlspecialchars($labels[$c]??$c,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</th>';$h.='</tr></thead><tbody>';foreach(discom_project_rows($snapshot,$columns) as $r){$h.='<tr>';foreach($columns as $c)$h.='<td>'.htmlspecialchars((string)$r[$c],ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</td>';$h.='</tr>';}$h.='</tbody></table></div>';return $h;}
function discom_csv(array $snapshot,array $columns=[]): string {$columns=$columns?:discom_default_columns();$f=fopen('php://temp','w+b');fputcsv($f,array_map(fn($c)=>discom_column_labels()[$c]??$c,$columns));foreach(discom_project_rows($snapshot,$columns) as $r)fputcsv($f,array_map(fn($c)=>$r[$c],$columns));rewind($f);$s=stream_get_contents($f);fclose($f);return "\xEF\xBB\xBF".$s;}
function discom_pdf(array $request): string { $lines=[(string)($request['subject']??'DISCOM Request'),'Batch: '.(string)($request['display_number']??''),(string)($request['message']??'')];foreach(discom_project_rows((array)($request['snapshot']??[])) as $r)$lines[]=implode(' | ',$r);$text=implode("\n",$lines);$safe=str_replace(['\\','(',')',"\r"],["\\\\",'\\(','\\)',''],$text);$stream="BT /F1 9 Tf 36 800 Td 11 TL (".str_replace("\n",") Tj T* (",$safe).") Tj ET";$objects=["1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj","2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj","3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>endobj","4 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj","5 0 obj<< /Length ".strlen($stream)." >>stream\n$stream\nendstream endobj"];$pdf="%PDF-1.4\n";$offset=[0];foreach($objects as $o){$offset[]=strlen($pdf);$pdf.=$o."\n";}$xref=strlen($pdf);$pdf.="xref\n0 6\n0000000000 65535 f \n";for($i=1;$i<=5;$i++)$pdf.=sprintf('%010d 00000 n ', $offset[$i])."\n";return $pdf."trailer<< /Size 6 /Root 1 0 R >>\nstartxref\n$xref\n%%EOF"; }
function discom_contacts(): array { discom_init();$r=json_decode((string)@file_get_contents(discom_contacts_path()),true);return is_array($r)?$r:[]; }
function discom_contact_for(string $division,string $subdivision): ?array {foreach(discom_contacts() as $c)if(!empty($c['active'])&&discom_normalize_group((string)($c['division']??''))===discom_normalize_group($division)&&discom_normalize_group((string)($c['subdivision']??''))===discom_normalize_group($subdivision))return $c;return null;}
function discom_email_list(string|array $raw): array {$parts=is_array($raw)?$raw:preg_split('/[,;\s]+/',$raw,-1,PREG_SPLIT_NO_EMPTY);$valid=[];$invalid=[];foreach($parts as $v){$v=trim((string)$v);if(filter_var($v,FILTER_VALIDATE_EMAIL))$valid[]=$v;else $invalid[]=$v;}return ['valid'=>array_values(array_unique($valid)),'invalid'=>array_values(array_unique($invalid))];}
function discom_save(array $r): bool {discom_init();return discom_atomic_json(discom_records_dir().'/'.safe_filename((string)$r['id']).'.json',$r);}
function discom_get(string $id): ?array {$p=discom_records_dir().'/'.safe_filename($id).'.json';$r=is_file($p)?json_decode((string)file_get_contents($p),true):null;return is_array($r)&&hash_equals((string)($r['id']??''),$id)?$r:null;}
function discom_all(): array {discom_init();$out=[];foreach(glob(discom_records_dir().'/*.json')?:[] as $p){$r=json_decode((string)file_get_contents($p),true);if(is_array($r))$out[]=$r;}usort($out,fn($a,$b)=>strcmp((string)($b['created_at']??''),(string)($a['created_at']??'')));return $out;}
function discom_status_for_project(string $quotationId): string { foreach(discom_all() as $r) if(in_array($quotationId,(array)($r['quotation_ids']??[]),true)) return (string)($r['status']??'Draft'); return ''; }
function discom_create(array $projects,array $input,array $actor,?string $replaces=null): array {if(!discom_authorized($actor))return ['ok'=>false,'error'=>'Permission denied.'];$valid=discom_validate_ids($projects,$actor);if(empty($valid['complete']))return ['ok'=>false,'error'=>'No complete projects can be requested.','validation'=>$valid];$groups=discom_group_projects($valid['complete'],!empty($input['combine_groups']));if(count($groups)>1)return ['ok'=>false,'error'=>'Separate Division + Subdivision groups must be created separately.','groups'=>$groups,'validation'=>$valid];$snapshot=array_values(array_map(fn($v)=>$v['data'],$valid['complete']));$now=date('c');$id='discom_'.date('Ymd_His').'_'.bin2hex(random_bytes(3));$r=['id'=>$id,'display_number'=>'DR-'.date('Y').'-'.strtoupper(substr(hash('sha256',$id),0,6)),'revision_of'=>$replaces,'request_type'=>in_array(($input['request_type']??''),['installation_inspection','net_metering','both'],true)?$input['request_type']:'both','division'=>$snapshot[0]['division_name'],'subdivision'=>$snapshot[0]['sub_division_name'],'quotation_ids'=>array_column($snapshot,'quotation_id'),'snapshot'=>$snapshot,'columns'=>(array)($input['columns']??discom_default_columns()),'request_date'=>(string)($input['request_date']??date('Y-m-d')),'requested_timeline'=>discom_clean((string)($input['requested_timeline']??'')),'follow_up_date'=>(string)($input['follow_up_date']??''),'subject'=>discom_clean((string)($input['subject']??'Solar installation inspection / net-metering request')),'message'=>trim((string)($input['message']??'')),'email_body'=>trim((string)($input['email_body']??'')),'signatory'=>discom_clean((string)($input['signatory']??'')),'internal_notes'=>trim((string)($input['internal_notes']??'')),'contact'=>discom_contact_for($snapshot[0]['division_name'],$snapshot[0]['sub_division_name']),'status'=>'Draft','channels'=>['email'=>['status'=>'Not sent','attempts'=>[]],'whatsapp'=>['status'=>'Not shared']],'created_by'=>['id'=>(string)($actor['id']??''),'role'=>(string)($actor['role_name']??$actor['role']??'')],'created_at'=>$now,'audit'=>[['event'=>'created','at'=>$now,'actor_id'=>(string)($actor['id']??'')]]];$pdf=discom_pdf($r);$csv=discom_csv($snapshot,$r['columns']);$r['artifacts']=['pdf'=>$id.'.pdf','csv'=>$id.'.csv'];file_put_contents(discom_artifacts_dir().'/'.$r['artifacts']['pdf'],$pdf,LOCK_EX);file_put_contents(discom_artifacts_dir().'/'.$r['artifacts']['csv'],$csv,LOCK_EX);discom_save($r);return ['ok'=>true,'request'=>$r,'validation'=>$valid];}
function discom_transition(array $r,string $to,array $actor,string $reason=''): array {$allowed=['Draft'=>['Ready','Cancelled'],'Ready'=>['Sent','Cancelled'],'Sent'=>['Acknowledged','Inspection Scheduled','Inspection Completed','Net Metering Pending','Net Meter Installed','Closed','Cancelled'],'Acknowledged'=>['Inspection Scheduled','Inspection Completed','Net Metering Pending','Net Meter Installed','Closed','Cancelled'],'Inspection Scheduled'=>['Inspection Completed','Cancelled'],'Inspection Completed'=>['Net Metering Pending','Net Meter Installed','Closed'],'Net Metering Pending'=>['Net Meter Installed','Closed','Cancelled'],'Net Meter Installed'=>['Closed'],'Closed'=>[],'Cancelled'=>[]];$from=(string)($r['status']??'Draft');if(!discom_authorized($actor)||!in_array($to,$allowed[$from]??[],true)||(in_array($to,['Closed','Cancelled'],true)&&trim($reason)===''))return ['ok'=>false,'error'=>'Transition is not permitted or a reason is required.'];$r['status']=$to;$r['audit'][]=['event'=>'status_changed','from'=>$from,'to'=>$to,'reason'=>discom_clean($reason),'at'=>date('c'),'actor_id'=>(string)($actor['id']??'')];discom_save($r);return ['ok'=>true,'request'=>$r];}
function discom_mark_whatsapp_shared(array $r,array $actor): array {if(!discom_authorized($actor))return ['ok'=>false];$r['channels']['whatsapp']=['status'=>'Shared','shared_at'=>date('c'),'shared_by'=>(string)($actor['id']??'')];$r['audit'][]=['event'=>'whatsapp_shared_confirmed','at'=>date('c'),'actor_id'=>(string)($actor['id']??'')];discom_save($r);return ['ok'=>true,'request'=>$r];}
function discom_whatsapp_message(array $r): string {return "नमस्कार / Namaskar,\n".(string)$r['subject']."\nBatch: ".(string)$r['display_number']."\nकृपया संलग्न PDF की समीक्षा करें। / Please review the attached PDF.\nRequested timeline is a follow-up target, not a guaranteed DISCOM date.";}
function discom_send_email(array $r,array $actor,?callable $sender=null): array {if(!discom_authorized($actor))return ['ok'=>false,'error'=>'Permission denied.'];$contact=(array)($r['contact']??[]);$to=discom_email_list((array)($contact['email_to']??[]));$cc=discom_email_list((array)($contact['email_cc']??[]));if($to['invalid']!==[]||$cc['invalid']!==[]||$to['valid']===[])return ['ok'=>false,'error'=>'Recipients contain invalid addresses or To is empty.'];$payload=['to'=>$to['valid'],'cc'=>$cc['valid'],'subject'=>$r['subject'],'html'=>(string)$r['email_body'].discom_html_table((array)$r['snapshot'],(array)$r['columns']),'attachment'=>discom_artifacts_dir().'/'.(string)$r['artifacts']['pdf']];$result=$sender?$sender($payload):['ok'=>false,'error'=>'Email provider is not configured.'];$attempt=['at'=>date('c'),'ok'=>!empty($result['ok']),'provider_id'=>discom_clean((string)($result['provider_id']??$result['message_id']??'')),'error_code'=>discom_clean((string)($result['error_code']??''))];$r['channels']['email']['attempts'][]=$attempt;if($attempt['ok']){$r['channels']['email']['status']='Sent';$r['channels']['email']['sent_at']=$attempt['at'];$r['sent_at']=$attempt['at'];if(in_array($r['status'],['Draft','Ready'],true))$r['status']='Sent';}else $r['channels']['email']['status']='Failed';$r['audit'][]=['event'=>$attempt['ok']?'email_sent':'email_failed','at'=>$attempt['at'],'provider_id'=>$attempt['provider_id'],'actor_id'=>(string)($actor['id']??'')];discom_save($r);return ['ok'=>$attempt['ok'],'request'=>$r,'error'=>(string)($result['error']??'')];}
