<?php
declare(strict_types=1);

function documents_quote_import_batches_dir(): string { $dir = dirname(documents_quotations_dir()) . '/quotation_import_batches'; documents_ensure_dir($dir); return $dir; }
function documents_quote_import_batch_path(string $batchId): string { return documents_quote_import_batches_dir() . '/' . safe_filename($batchId) . '.json'; }
function documents_quote_import_now(): string { return date('c'); }
function documents_quote_import_admin_snapshot(): array { $u = function_exists('current_user') ? current_user() : ['id'=>'test','name'=>'Test User','role_name'=>'admin']; return ['id'=>(string)($u['id']??''),'name'=>(string)($u['name']??$u['username']??$u['full_name']??''),'role'=>(string)($u['role_name']??'')]; }
function documents_quote_import_required_columns(): array { return ['import_key','customer_name','customer_mobile','party_type','template_set','system_type','selected_model_number','main_solar_kwp','non_dcr_kwp','quotation_date','valid_until','scenario_price_self_funded','scenario_price_loan_upto_2_lacs','scenario_price_loan_above_2_lacs']; }
function documents_quote_import_optional_columns(): array { return ['consumer_account_no','billing_address','site_address','district','city','state','pin','meter_number','meter_serial_number','area_or_locality','sanctioned_load_kw','phase','average_monthly_units','shadow_free_area_sqft','monthly_bill_rs','unit_rate_rs_per_kwh','annual_generation_per_kw','subsidy_amount','transportation_amount','discount_amount','special_requests_text','email','gstin','pan','pricing_mode','place_of_supply_state','tax_profile_id','show_tax_breakup','primary_finance_scenario','loan_upto_2_lacs_margin_money_rs','loan_upto_2_lacs_loan_amount_rs','loan_upto_2_lacs_interest_pct','loan_upto_2_lacs_tenure_years','loan_above_2_lacs_margin_money_rs','loan_above_2_lacs_loan_amount_rs','loan_above_2_lacs_interest_pct','loan_above_2_lacs_tenure_years']; }
function documents_quote_import_template_headers(): array { return array_merge(documents_quote_import_required_columns(), documents_quote_import_optional_columns()); }
function documents_quote_import_safe_csv_cell($value): string { $v=(string)$value; return preg_match('/^[=+\-@]/',$v) ? "'".$v : $v; }
function documents_quote_import_row_hash(array $row): string { ksort($row); return hash('sha256', json_encode($row, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); }
function documents_quote_import_normalize_mobile(string $mobile): string { return documents_normalize_whatsapp_mobile($mobile) ?: preg_replace('/\D+/', '', $mobile); }
function documents_quote_import_batches(): array { $rows=[]; foreach (glob(documents_quote_import_batches_dir().'/*.json') ?: [] as $file) { $r=json_load($file,[]); if(is_array($r)) $rows[]=$r; } usort($rows, fn($a,$b)=>strcmp((string)($b['created_at']??''),(string)($a['created_at']??''))); return $rows; }
function documents_quote_import_load_batch(string $batchId): ?array { $p=documents_quote_import_batch_path($batchId); if(!is_file($p)) return null; $r=json_load($p,[]); return is_array($r)?$r:null; }
function documents_quote_import_save_batch(array $batch): array { $id=safe_filename((string)($batch['batch_id']??'')); if($id==='') return ['ok'=>false,'error'=>'Missing batch ID']; return json_save(documents_quote_import_batch_path($id), $batch); }
function documents_quote_import_existing_identities(): array { $keys=[];$hashes=[];$likely=[]; foreach (documents_list_quotes() as $q) { $m=is_array($q['import_metadata']??null)?$q['import_metadata']:[]; if((string)($m['import_key']??'')!=='') $keys[(string)$m['import_key']] = (string)($q['id']??''); if((string)($m['row_hash']??'')!=='') $hashes[(string)$m['row_hash']] = (string)($q['id']??''); $mob=documents_quote_import_normalize_mobile((string)($q['customer_mobile']??'')); $date=(string)($q['quotation_date']??''); $model=(string)($q['selected_model_number']??''); $amt=(string)round((float)($q['input_total_gst_inclusive']??$q['calc']['grand_total']??0),2); if($mob!==''&&$date!==''&&$model!==''&&$amt!=='0') $likely[$mob.'|'.$date.'|'.$model.'|'.$amt]=(string)($q['id']??''); } return ['keys'=>$keys,'hashes'=>$hashes,'likely'=>$likely]; }


function documents_quote_import_normalize_name(string $value): string { return trim(preg_replace('/\s+/', ' ', strtolower($value)) ?? strtolower($value)); }
function documents_quote_import_annexure_labels(): array { return ['cover_notes'=>'Cover Notes','system_inclusions'=>'System Inclusions','payment_terms'=>'Payment Terms','warranty'=>'Warranty','system_type_explainer'=>'System Type Explainer','transportation'=>'Transportation','terms_conditions'=>'Terms and Conditions','pm_subsidy_info'=>'PM Subsidy Information','completion_milestones'=>'Completion Milestones','next_steps'=>'Next Steps']; }
function documents_quote_import_template_display_name(array $tpl): string { $name=trim((string)($tpl['display_name']??$tpl['name']??'')); $seg=trim((string)($tpl['segment']??'')); return trim($name.($seg!=='' && !str_contains(strtoupper($name), '('.strtoupper($seg).')') ? ' ('.$seg.')' : '')); }
function documents_quote_import_attachment_count(array $attachments): int { $n=0; foreach(['include_ongrid_diagram','include_hybrid_diagram','include_offgrid_diagram'] as $k) if(!empty($attachments[$k])) $n++; foreach(['ongrid_diagram_media_id','hybrid_diagram_media_id','offgrid_diagram_media_id'] as $k) if(trim((string)($attachments[$k]??''))!=='') $n++; if(is_array($attachments['additional_media_ids']??null)) $n+=count(array_filter($attachments['additional_media_ids'], static fn($v)=>trim((string)$v)!=='')); return $n; }
function documents_quote_import_attachment_rows(array $attachments): array { $rows=[]; foreach($attachments as $k=>$v){ if(is_bool($v) && $v) $rows[]=['id'=>$k,'name'=>$k,'notes'=>'Automatic built-in diagram flag']; elseif(is_string($v) && trim($v)!=='') $rows[]=['id'=>safe_text($v),'name'=>$k,'notes'=>'Safe media identifier']; elseif(is_array($v)) foreach($v as $id) if(trim((string)$id)!=='') $rows[]=['id'=>safe_text((string)$id),'name'=>'additional_media','notes'=>'Safe media identifier']; } return $rows; }
function documents_quote_import_resolve_template(string $value, array $context = []): array {
    $raw=trim($value); $warnings=[]; if($raw==='') return ['ok'=>false,'errors'=>[['field'=>'template_set','message'=>'template_set is required.']],'warnings'=>[]];
    $all=json_load(documents_templates_dir().'/template_sets.json',[]); $all=is_array($all)?$all:[]; $active=[]; $archived=[]; foreach($all as $tpl){ if(!is_array($tpl)) continue; $id=safe_text((string)($tpl['id']??'')); if($id==='') continue; if(!empty($tpl['archived_flag']) || !empty($tpl['inactive_flag'])) $archived[$id]=$tpl; else $active[$id]=$tpl; }
    if(isset($active[$raw])) $tpl=$active[$raw]; else { if(isset($archived[$raw])) return ['ok'=>false,'errors'=>[['field'=>'template_set','message'=>'Template '.$raw.' is inactive or archived.']],'warnings'=>[]]; $norm=documents_quote_import_normalize_name($raw); $matches=[]; foreach($active as $id=>$t){ if(documents_quote_import_normalize_name((string)($t['name']??''))===$norm) $matches[$id]=$t; } if(count($matches)!==1){ if(count($matches)>1) return ['ok'=>false,'errors'=>[['field'=>'template_set','message'=>'Ambiguous active template name: '.$raw.'. Use exact template ID.']],'warnings'=>[]]; $matches=[]; foreach($active as $id=>$t){ if(documents_quote_import_normalize_name(documents_quote_import_template_display_name($t))===$norm || documents_quote_import_normalize_name((string)($t['display_name']??''))===$norm) $matches[$id]=$t; } if(count($matches)!==1) return ['ok'=>false,'errors'=>[['field'=>'template_set','message'=>count($matches)>1?'Ambiguous active template display name: '.$raw.'. Use exact template ID.':'Active template not found: '.$raw.'.']],'warnings'=>[]]; } $tpl=reset($matches); }
    $id=safe_text((string)($tpl['id']??'')); $blocks=documents_get_template_blocks(); if(!array_key_exists($id,$blocks)) return ['ok'=>false,'errors'=>[['field'=>'template_set','message'=>'Template block entry missing for '.$id.'; configuration repair is required.']],'warnings'=>[]];
    $ann=documents_quote_annexure_from_template($blocks,$id); $keys=array_keys(array_filter($ann,static fn($v)=>trim((string)$v)!=='')); if(!$keys) $warnings[]=['field'=>'template_set','message'=>'Resolved template contains zero non-empty annexure blocks.'];
    $att=is_array($blocks[$id]['attachments']??null)?$blocks[$id]['attachments']:documents_template_attachment_defaults();
    return ['ok'=>true,'template_id'=>$id,'template'=>$tpl,'template_name'=>(string)($tpl['name']??''),'display_name'=>documents_quote_import_template_display_name($tpl),'segment'=>safe_text((string)($tpl['segment']??'RES'))?:'RES','annexures'=>$ann,'attachments'=>$att,'annexure_keys_present'=>$keys,'warnings'=>$warnings,'errors'=>[]];
}
function documents_quote_import_apply_resolved_template(array $quote, array $resolved): array { $quote['template_set_id']=(string)$resolved['template_id']; $quote['segment']=(string)$resolved['segment']; $quote['annexures_overrides']=is_array($resolved['annexures']??null)?$resolved['annexures']:documents_template_block_defaults(); $quote['cover_notes_html_snapshot']=trim((string)($quote['annexures_overrides']['cover_notes']??'')); $quote['template_attachments']=is_array($resolved['attachments']??null)?$resolved['attachments']:documents_template_attachment_defaults(); return $quote; }
function documents_quote_import_generate_sample_row(): array {
    $templates=json_load(documents_templates_dir().'/template_sets.json',[]); $tplId=''; $seg='RES'; foreach((array)$templates as $tpl){ if(is_array($tpl)&&empty($tpl['archived_flag'])&&safe_text((string)($tpl['id']??''))!==''){ $tplId=safe_text((string)$tpl['id']); $seg=safe_text((string)($tpl['segment']??'RES'))?:'RES'; break; } }
    if($tplId==='') return ['error'=>'No active quotation template is configured. Create an active template set before downloading the import template.'];
    $qd=load_quote_defaults(); $model=null; $stype='Ongrid'; foreach(['on_grid'=>'Ongrid','hybrid'=>'Hybrid'] as $key=>$label){ foreach((array)($qd['rate_chart'][$key]??[]) as $row){ if(is_array($row)&&safe_text((string)($row['model_number']??''))!==''){ $model=$row; $stype=$label; break 2; } } }
    if(!is_array($model)) return ['error'=>'No selectable rate-chart model is configured. Add a current model before downloading the import template.'];
    $cap=(float)($model['solar_size_kwp']??$model['total_system_size_kwp']??3); if($cap<=0)$cap=3.0; $non=(float)($model['complimentary_non_dcr_kwp']??$model['non_dcr_size_kwp']??0); $main=max(0.1,$cap-$non);
    $sample=array_fill_keys(documents_quote_import_template_headers(), '');
    $sample=array_merge($sample,['import_key'=>'SAMPLE-'.date('Ymd-His'),'customer_name'=>'Sample Customer','customer_mobile'=>'9876543210','party_type'=>'lead','template_set'=>$tplId,'system_type'=>$stype,'selected_model_number'=>(string)$model['model_number'],'main_solar_kwp'=>(string)$main,'non_dcr_kwp'=>(string)$non,'quotation_date'=>date('Y-m-d'),'valid_until'=>date('Y-m-d',strtotime('+7 days')),'scenario_price_self_funded'=>(string)($model['self_funded_price']??180000),'scenario_price_loan_upto_2_lacs'=>(string)($model['loan_upto_2_lacs_price']??$model['self_funded_price']??180000),'scenario_price_loan_above_2_lacs'=>(string)($model['loan_above_2_lacs_price']??$model['self_funded_price']??180000),'billing_address'=>'Sample billing address','site_address'=>'Sample site address','district'=>'Ranchi','city'=>'Ranchi','state'=>'Jharkhand','pin'=>'834001','phase'=>(string)($model['phase']??$model['hybrid_phase']??'single'),'subsidy_amount'=>'0','transportation_amount'=>'0','discount_amount'=>'0','email'=>'sample@example.com','pricing_mode'=>'solar_split_70_30','place_of_supply_state'=>'Jharkhand','show_tax_breakup'=>'1','primary_finance_scenario'=>'self_funded','loan_upto_2_lacs_interest_pct'=>'7','loan_upto_2_lacs_tenure_years'=>'5','loan_above_2_lacs_interest_pct'=>'9','loan_above_2_lacs_tenure_years'=>'7']);
    return $sample;
}

function documents_quote_import_enum_values(): array { $bool=['1'=>'true','0'=>'false','true'=>'true','false'=>'false','yes'=>'true','no'=>'false','y'=>'true','n'=>'false','on'=>'true','off'=>'false','enabled'=>'true','disabled'=>'false','enable'=>'true','disable'=>'false']; return ['party_type'=>['customer'=>'Customer record','lead'=>'Lead/prospect; RES/COM/IND/INST are segment codes, not party types.'],'system_type'=>['Ongrid'=>'On-grid solar','Hybrid'=>'Hybrid solar','ongrid'=>'Normalized on-grid','hybrid'=>'Normalized hybrid'],'pricing_mode'=>['solar_split_70_30'=>'Canonical solar split','flat_5'=>'Flat 5% GST','itemized'=>'Reserved/validated by UI'],'show_tax_breakup'=>$bool,'primary_finance_scenario'=>['self_funded'=>'Self funded','loan_upto_2_lacs'=>'Loan up to ₹2 lacs','loan_above_2_lacs'=>'Loan above ₹2 lacs'],'phase'=>['single'=>'Single phase','three'=>'Three phase','1'=>'Single phase','3'=>'Three phase']]; }
function documents_quote_import_field_definitions(): array { $defs=[]; foreach(documents_quote_import_template_headers() as $h){ $defs[$h]=['label'=>ucwords(str_replace('_',' ',$h)),'required'=>in_array($h,documents_quote_import_required_columns(),true),'data_type'=>'text','format'=>'','unit'=>'','default'=>'','calculated'=>false,'source'=>'CSV import header registry','example'=>'','notes'=>'Supported quotation import field.']; } $special=['import_key'=>['notes'=>'Unique idempotency key supplied by the user. It must not be reused.'],'template_set'=>['notes'=>'Exact active template ID or exact unique active name/display name. Automatically supplies segment, annexures and attachments.'],'selected_model_number'=>['notes'=>'Must match a current selectable rate-chart model for the normalized system type.'],'non_dcr_kwp'=>['unit'=>'kWp','notes'=>'Maps to canonical complimentary_non_dcr_kwp.'],'quotation_date'=>['format'=>'YYYY-MM-DD'],'valid_until'=>['format'=>'YYYY-MM-DD'],'scenario_price_self_funded'=>['unit'=>'rupees','notes'=>'GST-inclusive business price input used by the canonical quotation engine.'],'scenario_price_loan_upto_2_lacs'=>['unit'=>'rupees','notes'=>'GST-inclusive business price input used by the canonical quotation engine.'],'scenario_price_loan_above_2_lacs'=>['unit'=>'rupees','notes'=>'GST-inclusive business price input used by the canonical quotation engine.'],'tax_profile_id'=>['notes'=>'Blank means canonical kit/default tax-profile resolution.'],'show_tax_breakup'=>['default'=>'enabled','notes'=>'Blank defaults to enabled; see allowed_value rows.'],'subsidy_amount'=>['unit'=>'rupees','notes'=>'Subsidy expected reduces customer payable in canonical calculations.'],'transportation_amount'=>['unit'=>'rupees','notes'=>'Transportation is added to gross payable.'],'discount_amount'=>['unit'=>'rupees','notes'=>'Discount reduces gross payable after system and transportation.']]; foreach($defs as $h=>&$d){ foreach($special[$h]??[] as $k=>$v)$d[$k]=$v; if(str_contains($h,'interest_pct')){$d['unit']='percentage';$d['notes']='Loan interest percentage.';} if(str_contains($h,'tenure_years')){$d['unit']='years';$d['notes']='Loan tenure in years.';} if(str_contains($h,'loan_amount')||str_contains($h,'margin_money')){$d['unit']='rupees';} } return $defs; }

function documents_quote_bool_from_csv($value, bool $default = true): bool { $v=strtolower(trim((string)$value)); if($v==='') return $default; if(in_array($v, ['0','false','no','n','off','disabled','disable'], true)) return false; return in_array($v, ['1','true','yes','y','on','enabled','enable'], true); }
function documents_quote_import_segment_codes(): array { return array_fill_keys(array_keys(documents_quotation_segments()), true); }
function documents_quote_import_normalize_input(array $input): array {
    $out=$input;
    $map=['non_dcr_kwp'=>'complimentary_non_dcr_kwp','sanctioned_load_kw'=>'sanction_load_kwp','subsidy_amount'=>'subsidy_expected_rs','transportation_amount'=>'transportation_rs','discount_amount'=>'discount_rs','phase'=>'hybrid_phase'];
    foreach($map as $from=>$to){ if(array_key_exists($from,$out) && !array_key_exists($to,$out)) $out[$to]=$out[$from]; }
    if(!array_key_exists('complimentary_non_dcr_kwp',$out)) $out['complimentary_non_dcr_kwp']='0';
    $pt=strtolower(trim((string)($out['party_type']??'lead')));
    $segHint='';
    $upper=strtoupper(trim((string)($out['party_type']??'')));
    if(isset(documents_quote_import_segment_codes()[$upper])) { $segHint=$upper; $pt='lead'; }
    $out['party_type']=in_array($pt,['customer','lead'],true)?$pt:'lead';
    if($segHint!=='' && trim((string)($out['segment']??''))==='') $out['segment']=$segHint;
    if(trim((string)($out['show_tax_breakup']??''))==='') $out['show_tax_breakup']='1';
    if(trim((string)($out['pricing_mode']??''))==='') $out['pricing_mode']='solar_split_70_30';
    if(trim((string)($out['place_of_supply_state']??''))==='') $out['place_of_supply_state']='Jharkhand';
    if(trim((string)($out['primary_finance_scenario']??''))==='') $out['primary_finance_scenario']='self_funded';
    return $out;
}
function documents_validate_quote_draft_input(array $input, array $context = []): array {
    $input=documents_quote_import_normalize_input($input);
    $messages=[]; $warnings=[]; $required=documents_quote_import_required_columns();
    foreach($required as $col){ if(trim((string)($input[$col]??''))==='') $messages[]=['field'=>$col,'message'=>'Required field is missing.']; }
    $rawParty=strtoupper(trim((string)($input['_raw_party_type']??$context['raw_party_type']??'')));
    if($rawParty==='' && isset($context['source']) && ($context['source']==='csv')) $rawParty=strtoupper(trim((string)($_POST['party_type']??'')));
    $origParty=strtoupper(trim((string)($context['original_party_type']??'')));
    $partyCheck=$origParty!==''?$origParty:strtoupper(trim((string)($input['party_type_original']??$input['party_type_raw']??'')));
    if($partyCheck!=='' && isset(documents_quote_import_segment_codes()[$partyCheck])) $warnings[]=['field'=>'party_type','message'=>'Legacy segment code '.$partyCheck.' was treated as a segment hint; party_type was normalized to lead.'];
    if(!in_array((string)($input['party_type']??''), ['customer','lead'], true)) $messages[]=['field'=>'party_type','message'=>'party_type must be customer or lead.'];
    foreach(['quotation_date','valid_until'] as $d){ $v=(string)($input[$d]??''); if($v!=='' && !preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)) $messages[]=['field'=>$d,'message'=>'Use ISO date YYYY-MM-DD.']; }
    $main=(float)($input['main_solar_kwp']??0); $non=(float)($input['complimentary_non_dcr_kwp']??$input['non_dcr_kwp']??0); if($main<0||$non<0||($main+$non)<=0) $messages[]=['field'=>'main_solar_kwp','message'=>'Total capacity must be greater than zero.'];
    $mobile=documents_quote_import_normalize_mobile((string)($input['customer_mobile']??'')); if($mobile==='') $messages[]=['field'=>'customer_mobile','message'=>'Valid mobile is required.'];
    $templateResolved=documents_quote_import_resolve_template((string)($input['template_set']??''), $context);
    if(empty($templateResolved['ok'])) { foreach((array)($templateResolved['errors']??[]) as $e) $messages[]=$e; }
    foreach((array)($templateResolved['warnings']??[]) as $w) $warnings[]=$w;
    $hint=strtoupper(trim((string)($input['segment']??''))); if(!empty($templateResolved['ok']) && $hint!=='' && isset(documents_quote_import_segment_codes()[$hint]) && $hint!==(string)$templateResolved['segment']) $warnings[]=['field'=>'segment','message'=>'Legacy segment hint '.$hint.' conflicts with resolved template segment '.$templateResolved['segment'].'; template segment is authoritative.'];
    $hash=documents_quote_import_row_hash($input); $ids=documents_quote_import_existing_identities(); $key=(string)($input['import_key']??'');
    if($key!=='' && isset($ids['keys'][$key])) $messages[]=['field'=>'import_key','message'=>'Import key already committed in quotation '.$ids['keys'][$key].'.'];
    if(isset($ids['hashes'][$hash])) $messages[]=['field'=>'row_hash','message'=>'This exact row was already committed in quotation '.$ids['hashes'][$hash].'.'];
    $likelyKey=$mobile.'|'.(string)($input['quotation_date']??'').'|'.(string)($input['selected_model_number']??'').'|'.(string)round((float)($input['scenario_price_self_funded']??0),2); if(isset($ids['likely'][$likelyKey])) $warnings[]=['field'=>'duplicate','message'=>'Likely duplicate of quotation '.$ids['likely'][$likelyKey].'.'];
    $preview=documents_build_quote_draft_from_input($input, ['dry_run'=>true]+$context);
    if(!empty($preview['system_reconcile_error'])) $warnings[]=['field'=>'kit','message'=>(string)$preview['system_reconcile_error']];
    return ['ok'=>$messages===[],'status'=>$messages? 'Error' : ($warnings?'Warning':'Valid'),'messages'=>array_merge($messages,$warnings),'errors'=>$messages,'warnings'=>$warnings,'row_hash'=>$hash,'normalized_mobile'=>$mobile,'preview'=>documents_quote_import_preview_from_quote($preview),'normalized_input'=>$input];
}
function documents_quote_import_preview_from_quote(array $q): array { $calc=is_array($q['calc']??null)?$q['calc']:[]; $tb=is_array($q['tax_breakdown']??null)?$q['tax_breakdown']:[]; $ann=is_array($q['annexures_overrides']??null)?$q['annexures_overrides']:[]; $annKeys=array_keys(array_filter($ann,static fn($v)=>trim((string)$v)!=='')); return ['template_id'=>(string)($q['template_set_id']??''),'template_name'=>(string)($q['template_name_snapshot']??''),'template_display_name'=>(string)($q['template_display_name_snapshot']??''),'segment'=>(string)($q['segment']??''),'annexure_count'=>count($annKeys),'annexure_keys'=>$annKeys,'attachment_count'=>documents_quote_import_attachment_count(is_array($q['template_attachments']??null)?$q['template_attachments']:[]),'template_warnings'=>(array)($q['template_warnings']??[]),'system_type'=>(string)($q['system_type']??''),'model_number'=>(string)($q['rate_chart_snapshot']['model_number']??$q['selected_model_number']??''),'kit'=>(string)($q['quote_items'][0]['name_snapshot']??$q['quote_items'][0]['name']??''),'item_count'=>count((array)($q['quote_items']??[])),'basic_amount'=>(float)($tb['basic_total']??$calc['basic_total']??0),'gst'=>(float)($tb['gst_total']??0),'tax_mode'=>(string)($tb['mode']??$q['gst_mode_snapshot']??''),'subsidy'=>(float)($calc['subsidy_expected_rs']??0),'transportation'=>(float)($calc['transportation_rs']??0),'discount'=>(float)($calc['discount_rs']??0),'final_payable'=>(float)($calc['gross_payable']??$calc['grand_total']??0)]; }
function documents_build_quote_draft_from_input(array $input, array $context = []): array {
    $input=documents_quote_import_normalize_input($input); $q=documents_quote_defaults(); $now=documents_quote_import_now(); $admin=documents_quote_import_admin_snapshot();
    $q['id']=(string)($context['preserve_id']??('quote_'.date('Ymd_His').'_'.bin2hex(random_bytes(4)))); $q['quote_no']=(string)($context['preserve_quote_no']??''); $q['status']='Draft'; $q['created_at']=(string)($context['preserve_created_at']??$now); $q['updated_at']=$now; $q['created_by_type']='admin'; $q['created_by_id']=$admin['id']; $q['created_by_name']=$admin['name'];
    $q['party_type']=(string)$input['party_type']; $q['segment']=(string)($input['segment']??'RES');
    $resolvedTemplate=documents_quote_import_resolve_template((string)($input['template_set']??''), $context);
    if(!empty($resolvedTemplate['ok'])) { $q=documents_quote_import_apply_resolved_template($q,$resolvedTemplate); $q['template_name_snapshot']=(string)$resolvedTemplate['template_name']; $q['template_display_name_snapshot']=(string)$resolvedTemplate['display_name']; $q['template_warnings']=(array)($resolvedTemplate['warnings']??[]); }
    foreach(['customer_name','customer_mobile','consumer_account_no','billing_address','site_address','district','city','state','pin','meter_number','meter_serial_number','quotation_date','valid_until','special_requests_text','tax_profile_id','place_of_supply_state','pricing_mode','primary_finance_scenario','sanction_load_kwp'] as $f) if(array_key_exists($f,$input)) $q[$f]=(string)$input[$f];
    $q['customer_mobile']=documents_quote_import_normalize_mobile((string)$q['customer_mobile']); $q['system_type']=documents_quote_normalize_system_type((string)($input['system_type']??'ongrid')); $q['selected_model_number']=safe_text((string)($input['selected_model_number']??''));
    $q['main_solar_kwp']=(string)(float)($input['main_solar_kwp']??0); $q['complimentary_non_dcr_kwp']=(string)(float)($input['complimentary_non_dcr_kwp']??0); $q['capacity_kwp']=(string)((float)$q['main_solar_kwp']+(float)$q['complimentary_non_dcr_kwp']); $q['system_capacity_kwp']=(float)$q['capacity_kwp'];
    $q['show_tax_breakup']=documents_quote_bool_from_csv($input['show_tax_breakup']??'', true); $company=load_company_profile(); $q['tax_type']=strtolower((string)$q['place_of_supply_state'])===strtolower((string)($company['state']??'Jharkhand'))?'CGST_SGST':'IGST';
    $priceSelf=round(max(0,(float)($input['scenario_price_self_funded']??0)),2); $priceUp=round(max(0,(float)($input['scenario_price_loan_upto_2_lacs']??0)),2); $priceAbove=round(max(0,(float)($input['scenario_price_loan_above_2_lacs']??0)),2);
    $sub=round(max(0,(float)($input['subsidy_expected_rs']??0)),2); $trans=round(max(0,(float)($input['transportation_rs']??0)),2); $disc=round(max(0,(float)($input['discount_rs']??0)),2); $q['discount_rs']=$disc;
    $q['scenario_prices']=['self_funded'=>['price'=>$priceSelf],'loan_upto_2_lacs'=>['price'=>$priceUp],'loan_above_2_lacs'=>['price'=>$priceAbove]];
    $primary=(string)$q['primary_finance_scenario']; $price=$primary==='loan_above_2_lacs'?$priceAbove:($primary==='loan_upto_2_lacs'?$priceUp:$priceSelf); if($price<=0) $price=$priceSelf;
    $q['input_total_gst_inclusive']=$price; $q['rate_chart_snapshot']=['system_type'=>$q['system_type'],'model_number'=>$q['selected_model_number'],'solar_size_kwp'=>(float)$q['capacity_kwp'],'dcr_size_kwp'=>(float)$q['main_solar_kwp'],'non_dcr_size_kwp'=>(float)$q['complimentary_non_dcr_kwp'],'total_system_size_kwp'=>(float)$q['capacity_kwp'],'hybrid_phase'=>solar_finance_normalize_phase_label((string)($input['hybrid_phase']??'')),'hybrid_inverter_kva'=>(float)($input['hybrid_inverter_kva']??0),'hybrid_battery_count'=>(int)($input['hybrid_battery_count']??0),'self_funded_price'=>$priceSelf,'loan_upto_2_lacs_price'=>$priceUp,'loan_above_2_lacs_price'=>$priceAbove,'captured_at'=>$now];
    $q=documents_quote_reconcile_system_configuration($q); if(function_exists('solar_finance_sync_hybrid_summary_into_quote_items')) $q=solar_finance_sync_hybrid_summary_into_quote_items($q);
    $settings=load_quote_defaults(); $q['calc']=documents_calc_quote_pricing_with_tax_profile($q,$trans,$sub,$price,is_array($settings)?$settings:[]); $q['tax_breakdown']=is_array($q['calc']['tax_breakdown']??null)?$q['calc']['tax_breakdown']:['basic_total'=>0,'gst_total'=>0,'gross_incl_gst'=>0,'slabs'=>[]]; $q['gst_mode_snapshot']=(string)($q['tax_breakdown']['mode']??'single'); $q['gst_slabs_snapshot']=is_array($q['tax_breakdown']['slabs']??null)?$q['tax_breakdown']['slabs']:[];
    $q['finance_inputs']=['monthly_bill_rs'=>(string)($input['monthly_bill_rs']??''),'unit_rate_rs_per_kwh'=>(string)($input['unit_rate_rs_per_kwh']??''),'annual_generation_per_kw'=>(string)($input['annual_generation_per_kw']??''),'subsidy_expected_rs'=>(string)$sub,'transportation_rs'=>(string)$trans,'discount_rs'=>(string)$disc,'loan'=>['enabled'=>str_starts_with($primary,'loan_')]];
    $q['finance_scenarios']=['self_funded'=>['price'=>$priceSelf,'subsidy'=>$sub,'gross_payable'=>$priceSelf,'applicable'=>true],'loan_upto_2_lacs'=>['price'=>$priceUp,'subsidy'=>$sub,'gross_payable'=>$priceUp,'applicable'=>true,'margin_money_rs'=>(float)($input['loan_upto_2_lacs_margin_money_rs']??0),'loan_amount_rs'=>(float)($input['loan_upto_2_lacs_loan_amount_rs']??0),'interest_pct'=>(float)($input['loan_upto_2_lacs_interest_pct']??0),'tenure_years'=>(float)($input['loan_upto_2_lacs_tenure_years']??0)],'loan_above_2_lacs'=>['price'=>$priceAbove,'subsidy'=>$sub,'gross_payable'=>$priceAbove,'applicable'=>true,'margin_money_rs'=>(float)($input['loan_above_2_lacs_margin_money_rs']??0),'loan_amount_rs'=>(float)($input['loan_above_2_lacs_loan_amount_rs']??0),'interest_pct'=>(float)($input['loan_above_2_lacs_interest_pct']??0),'tenure_years'=>(float)($input['loan_above_2_lacs_tenure_years']??0)]];
    $q['customer_snapshot']=array_merge(documents_customer_snapshot_defaults(),['mobile'=>$q['customer_mobile'],'name'=>$q['customer_name'],'address'=>$q['site_address']?:$q['billing_address'],'city'=>$q['city'],'district'=>$q['district'],'pin_code'=>$q['pin'],'state'=>$q['state'],'consumer_account_no'=>$q['consumer_account_no'],'sanction_load_kwp'=>$q['sanction_load_kwp']]);
    $q['public_share_enabled']=false; $q['locked_flag']=false; return $q;
}
function documents_commit_quote_draft(array $validated, array $context = []): array {
    if(empty($validated['ok']) && !in_array((string)($validated['status']??''), ['Valid','Warning'], true)) return ['ok'=>false,'error'=>'Row is invalid.'];
    $input=is_array($validated['normalized_input']??null)?$validated['normalized_input']:(is_array($validated['input']??null)?$validated['input']:$validated); $quote=documents_build_quote_draft_from_input($input,$context); $seg=(string)($quote['segment']??'RES'); if((string)($quote['quote_no']??'')===''){ $num=documents_generate_quote_number($seg); if(empty($num['ok'])) return ['ok'=>false,'error'=>(string)($num['error']??'Numbering failed')]; $quote['quote_no']=(string)$num['quote_no']; }
    $quote['import_metadata']=['batch_id'=>(string)($context['batch_id']??''),'import_key'=>(string)($input['import_key']??''),'source_row'=>(int)($context['source_row']??0),'source_filename'=>safe_filename((string)($context['source_filename']??'')),'row_hash'=>(string)($validated['row_hash']??documents_quote_import_row_hash($input)),'importing_admin'=>documents_quote_import_admin_snapshot(),'imported_at'=>documents_quote_import_now()];
    $hashQuote=$quote; unset($hashQuote['import_metadata']['post_import_hash']); $quote['import_metadata']['post_import_hash']=hash('sha256', json_encode($hashQuote, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); $saved=documents_save_quote($quote); return !empty($saved['ok']) ? ['ok'=>true,'quote'=>$quote,'quote_id'=>$quote['id']] : ['ok'=>false,'error'=>(string)($saved['error']??'Save failed')];
}
function documents_quote_repair_imported_batch(array $batch): array { $repaired=0;$skipped=0;$failed=0;$reasons=[]; foreach((array)($batch['created_quotation_ids']??[]) as $qid){ $q=documents_get_quote((string)$qid); if(!$q){$skipped++;$reasons[$qid]='Quotation not found';continue;} $st=strtolower((string)($q['status']??'draft')); if($st!=='draft'||!empty($q['accepted_at'])||!empty($q['workflow']['agreement_id'])||!empty($q['workflow']['invoice_id'])){$skipped++;$reasons[$qid]='Not an eligible untouched draft';continue;} $meta=is_array($q['import_metadata']??null)?$q['import_metadata']:[]; $row=null; foreach((array)($batch['rows']??[]) as $r){ if((string)($r['commit_result']??'')!=='' && str_contains((string)$r['commit_result'],(string)$qid)){$row=$r;break;} if((string)($r['input']['import_key']??'')===(string)($meta['import_key']??'')){$row=$r;break;} } if(!$row||!is_array($row['input']??null)){$skipped++;$reasons[$qid]='Saved import input missing';continue;} $before=$q; $new=documents_build_quote_draft_from_input($row['input'],['preserve_id'=>$q['id'],'preserve_quote_no'=>$q['quote_no'],'preserve_created_at'=>$q['created_at']]); $new['import_metadata']=$meta; $new['public_token']=$q['public_token']??''; $new['public_share_token']=$q['public_share_token']??''; $new['public_url']=$q['public_url']??''; $new['repair_metadata']=['batch_id'=>(string)($batch['batch_id']??''),'actor'=>documents_quote_import_admin_snapshot(),'time'=>documents_quote_import_now(),'pre_repair_snapshot'=>$before,'before_hash'=>hash('sha256',json_encode($before,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)),'after_hash'=>hash('sha256',json_encode($new,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))]; $save=documents_save_quote($new); if(!empty($save['ok']))$repaired++;else{$failed++;$reasons[$qid]='Save failed';} } return ['repaired'=>$repaired,'skipped'=>$skipped,'failed'=>$failed,'reasons'=>$reasons,'actor'=>documents_quote_import_admin_snapshot(),'time'=>documents_quote_import_now()]; }
