<?php
declare(strict_types=1);

function documents_quote_reference_export_headers(): array
{
    return ['record_type','field_name','display_label','required','data_type','format','unit','allowed_value','reference_id','reference_name','segment','system_type','model_number','default_value','auto_calculated','source','example_value','annexure_key','annexure_label','annexure_present','character_count','attachment_name','notes','content'];
}
function documents_quote_reference_blank_row(string $type): array { return array_fill_keys(documents_quote_reference_export_headers(), '') + ['record_type'=>$type]; }
function documents_quote_reference_stream_csv($out): void
{
    $headers=documents_quote_reference_export_headers(); fputcsv($out,$headers);
    $emit=function(array $row) use ($out,$headers): void { $base=documents_quote_reference_blank_row((string)($row['record_type']??'')); foreach($row as $k=>$v){ if(array_key_exists($k,$base)) $base[$k]=is_array($v)?json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):(string)$v; } fputcsv($out,array_map('documents_quote_import_safe_csv_cell',array_map(static fn($h)=>(string)($base[$h]??''),$headers))); };
    $emit(['record_type'=>'metadata','field_name'=>'schema_version','reference_name'=>'quotation_reference_catalogue','default_value'=>'1','source'=>'current saved application configuration','notes'=>'Generated '.date('c').'; no customer or quotation records are included.']);
    foreach(documents_quote_import_field_definitions() as $name=>$def){ $emit(['record_type'=>'field_definition','field_name'=>$name,'display_label'=>$def['label']??$name,'required'=>!empty($def['required'])?'yes':'no','data_type'=>$def['data_type']??'text','format'=>$def['format']??'','unit'=>$def['unit']??'','default_value'=>$def['default']??'','auto_calculated'=>!empty($def['calculated'])?'yes':'no','source'=>$def['source']??'CSV import','example_value'=>$def['example']??'','notes'=>$def['notes']??'']); }
    foreach(documents_quote_import_enum_values() as $field=>$values){ foreach($values as $value=>$note){ $emit(['record_type'=>'allowed_value','field_name'=>$field,'allowed_value'=>(string)$value,'source'=>'CSV parser','notes'=>(string)$note]); } }
    $templatesRaw=json_load(documents_templates_dir().'/template_sets.json',[]); $templates=is_array($templatesRaw)?$templatesRaw:[]; $blocks=documents_sync_template_block_entries($templates); $labels=documents_quote_import_annexure_labels();
    foreach($templates as $tpl){ if(!is_array($tpl)) continue; $arch=!empty($tpl['archived_flag']); $id=safe_text((string)($tpl['id']??'')); if($id==='') continue; $res=documents_quote_import_resolve_template($id); $ann=is_array($res['annexures']??null)?$res['annexures']:documents_quote_annexure_from_template($blocks,$id); $keys=array_keys(array_filter($ann,static fn($v)=>trim((string)$v)!=='')); $att=is_array($res['attachments']??null)?$res['attachments']:(is_array($blocks[$id]['attachments']??null)?$blocks[$id]['attachments']:[]); $emit(['record_type'=>'template_set','reference_id'=>$id,'reference_name'=>(string)($tpl['name']??''),'display_label'=>documents_quote_import_template_display_name($tpl),'segment'=>(string)($tpl['segment']??''),'source'=>'template_sets.json + template_blocks.json','annexure_present'=>count($keys)>0?'yes':'no','character_count'=>(string)count($keys),'attachment_name'=>(string)documents_quote_import_attachment_count($att),'notes'=>($arch?'Archived/inactive; not selectable.':'Active/selectable; selecting template_set automatically applies annexures and attachments.')]); if(!$arch){ foreach($labels as $key=>$label){ $txt=(string)($ann[$key]??''); $emit(['record_type'=>'template_annexure','reference_id'=>$id,'reference_name'=>(string)($tpl['name']??''),'display_label'=>documents_quote_import_template_display_name($tpl),'segment'=>(string)($tpl['segment']??''),'annexure_key'=>$key,'annexure_label'=>$label,'annexure_present'=>trim($txt)!==''?'yes':'no','character_count'=>(string)strlen($txt),'source'=>'template_blocks.json','notes'=>'Automatically applied from template_set.','content'=>$txt]); } foreach(documents_quote_import_attachment_rows($att) as $a){ $emit(['record_type'=>'template_attachment','reference_id'=>$id,'reference_name'=>(string)($tpl['name']??''),'segment'=>(string)($tpl['segment']??''),'attachment_name'=>$a['name'],'allowed_value'=>$a['id'],'source'=>'template_blocks.json/media library','notes'=>$a['notes']]); } } }
    $qd=load_quote_defaults(); foreach(['on_grid'=>'ongrid','hybrid'=>'hybrid'] as $key=>$stype){ foreach((array)($qd['rate_chart'][$key]??[]) as $r){ if(!is_array($r)) continue; $emit(['record_type'=>'rate_chart','system_type'=>$stype,'model_number'=>(string)($r['model_number']??''),'reference_id'=>(string)($r['kit_id']??$r['configuration_id']??''),'reference_name'=>(string)($r['kit_name']??$r['configuration_name']??''),'default_value'=>(string)($r['self_funded_price']??''),'allowed_value'=>(string)($r['loan_upto_2_lacs_price']??''),'example_value'=>(string)($r['loan_above_2_lacs_price']??''),'format'=>'DCR '.($r['solar_size_kwp']??'').' + Non-DCR '.($r['complimentary_non_dcr_kwp']??$r['non_dcr_size_kwp']??'0').' kWp; phase '.($r['phase']??$r['hybrid_phase']??''),'notes'=>'Current selectable rate-chart model when active. '.json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]); } }
    if(function_exists('documents_inventory_list_kits')) foreach(documents_inventory_list_kits(false) as $kit){ if(is_array($kit)) $emit(['record_type'=>'system_kit','reference_id'=>(string)($kit['id']??''),'reference_name'=>(string)($kit['name']??''),'system_type'=>(string)($kit['system_type']??''),'source'=>'inventory kits','notes'=>'Kit reference; tax profile '.($kit['tax_profile_id']??'')]); }
    if(function_exists('documents_inventory_list_components')) foreach(documents_inventory_list_components(false) as $c){ if(is_array($c)) $emit(['record_type'=>'component_variant','reference_id'=>(string)($c['id']??''),'reference_name'=>(string)($c['name']??''),'unit'=>(string)($c['default_unit']??''),'source'=>'inventory components','notes'=>'Component HSN '.($c['hsn']??'')]); }
    if(function_exists('documents_inventory_list_variants')) foreach(documents_inventory_list_variants(false) as $v){ if(is_array($v)) $emit(['record_type'=>'component_variant','reference_id'=>(string)($v['id']??''),'reference_name'=>(string)($v['display_name']??$v['name']??''),'source'=>'inventory variants','notes'=>'Variant for component '.($v['component_id']??'')]); }
    foreach((array)($qd['tax_profiles']??[]) as $p){ if(is_array($p)) $emit(['record_type'=>'tax_profile','reference_id'=>(string)($p['id']??''),'reference_name'=>(string)($p['name']??''),'source'=>'quote defaults tax profiles','notes'=>json_encode($p,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]); }
    foreach(['self_funded'=>'Self funded','loan_upto_2_lacs'=>'Loan up to ₹2 lacs','loan_above_2_lacs'=>'Loan above ₹2 lacs'] as $k=>$n) $emit(['record_type'=>'finance_scenario','reference_id'=>$k,'reference_name'=>$n,'unit'=>'rupees/percentage/years','source'=>'CSV import finance scenarios','notes'=>'Amount fields rupees; interest fields percentage; tenure fields years.']);
    $company=load_company_profile(); $emit(['record_type'=>'place_of_supply_rule','field_name'=>'place_of_supply_state','reference_name'=>(string)($company['state']??'Jharkhand'),'source'=>'canonical tax logic','notes'=>'If place_of_supply_state equals company state CGST/SGST applies; otherwise IGST applies.']);
}
