<?php
declare(strict_types=1);

function documents_quote_import_batches_dir(): string { $dir = dirname(documents_quotations_dir()) . '/quotation_import_batches'; documents_ensure_dir($dir); return $dir; }
function documents_quote_import_batch_path(string $batchId): string { return documents_quote_import_batches_dir() . '/' . safe_filename($batchId) . '.json'; }
function documents_quote_import_now(): string { return date('c'); }
function documents_quote_import_admin_snapshot(): array { $u = function_exists('current_user') ? current_user() : ['id'=>'test','name'=>'Test User','role_name'=>'admin']; return ['id'=>(string)($u['id']??''),'name'=>(string)($u['name']??$u['username']??$u['full_name']??''),'role'=>(string)($u['role_name']??'')]; }
function documents_quote_import_required_columns(): array { return ['import_key','customer_name','customer_mobile','party_type','template_set','system_type','selected_model_number','main_solar_kwp','non_dcr_kwp','quotation_date','valid_until','scenario_price_self_funded','scenario_price_loan_upto_2_lacs','scenario_price_loan_above_2_lacs']; }
function documents_quote_import_optional_columns(): array { return ['consumer_account_no','billing_address','site_address','district','city','state','pin','meter_number','meter_serial_number','area_or_locality','sanctioned_load_kw','phase','average_monthly_units','shadow_free_area_sqft','monthly_bill_rs','unit_rate_rs_per_kwh','annual_generation_per_kw','subsidy_amount','transportation_amount','discount_amount','special_requests_text','email','gstin','pan','pricing_mode','place_of_supply_state','tax_profile_id','show_tax_breakup','primary_finance_scenario','loan_upto_2_lacs_margin_money_rs','loan_upto_2_lacs_loan_amount_rs','loan_upto_2_lacs_interest_pct','loan_upto_2_lacs_tenure_years','loan_above_2_lacs_margin_money_rs','loan_above_2_lacs_loan_amount_rs','loan_above_2_lacs_interest_pct','loan_above_2_lacs_tenure_years']; }
function documents_quote_import_template_headers(): array { return array_merge(documents_quote_import_required_columns(), documents_quote_import_optional_columns()); }
function documents_quote_import_safe_csv_cell($value): string { $v=(string)$value; return preg_match('/^[=+\-@]/',$v) ? "'".$v : $v; }
function documents_quote_import_row_hash(array $row): string { ksort($row); return hash('sha256', json_encode($row, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); }
function documents_quote_import_normalize_mobile(string $mobile): string { return documents_normalize_whatsapp_mobile($mobile) ?: preg_replace('/\D+/', '', $mobile); }
function documents_quote_import_batches(): array { $rows=[]; foreach (glob(documents_quote_import_batches_dir().'/*.json') ?: [] as $file) { $r=json_load($file,[]); if(is_array($r)) $rows[]=$r; } usort($rows, fn($a,$b)=>strcmp((string)($b['created_at']??''),(string)($a['created_at']??''))); return $rows; }
function documents_quote_import_load_batch(string $batchId): ?array { $p=documents_quote_import_batch_path($batchId); if(!is_file($p)) return null; $r=json_load($p,[]); return is_array($r)?$r:null; }
function documents_quote_import_save_batch(array $batch): array { $id=safe_filename((string)($batch['batch_id']??'')); if($id==='') return ['ok'=>false,'error'=>'Missing batch ID']; return json_save(documents_quote_import_batch_path($id), $batch); }
function documents_quote_import_existing_identities(): array { $keys=[];$hashes=[];$likely=[]; foreach (documents_list_quotes() as $q) { $m=is_array($q['import_metadata']??null)?$q['import_metadata']:[]; if((string)($m['import_key']??'')!=='') $keys[(string)$m['import_key']] = (string)($q['id']??''); if((string)($m['row_hash']??'')!=='') $hashes[(string)$m['row_hash']] = (string)($q['id']??''); $mob=documents_quote_import_normalize_mobile((string)($q['customer_mobile']??'')); $date=(string)($q['quotation_date']??''); $model=(string)($q['selected_model_number']??''); $amt=(string)round((float)($q['input_total_gst_inclusive']??$q['calc']['grand_total']??0),2); if($mob!==''&&$date!==''&&$model!==''&&$amt!=='0') $likely[$mob.'|'.$date.'|'.$model.'|'.$amt]=(string)($q['id']??''); } return ['keys'=>$keys,'hashes'=>$hashes,'likely'=>$likely]; }

function documents_quote_bool_from_csv($value, bool $default = true): bool { $v=strtolower(trim((string)$value)); if($v==='') return $default; return in_array($v, ['1','true','yes','y','on','enabled','enable'], true); }
function documents_quote_import_segment_codes(): array { return ['RES'=>true,'COM'=>true,'IND'=>true,'INST'=>true]; }
function documents_quote_import_normalize_input(array $input): array {
    $out=$input;
    $map=['non_dcr_kwp'=>'complimentary_non_dcr_kwp','sanctioned_load_kw'=>'sanction_load_kwp','subsidy_amount'=>'subsidy_expected_rs','transportation_amount'=>'transportation_rs','discount_amount'=>'discount_rs','phase'=>'hybrid_phase'];
    foreach($map as $from=>$to){ if(array_key_exists($from,$out) && !array_key_exists($to,$out)) $out[$to]=$out[$from]; }
    if(!array_key_exists('complimentary_non_dcr_kwp',$out)) $out['complimentary_non_dcr_kwp']='0';
    $pt=strtolower(trim((string)($out['party_type']??'lead')));
    $segHint='';
    $upper=strtoupper(trim((string)($out['party_type']??'')));
    if(isset(documents_quote_import_segment_codes()[$upper])) { $segHint=$upper; $pt='lead'; }
    $out['party_type']=in_array($pt,['customer','lead'],true)?$pt:'lead';
    if($segHint!=='' && trim((string)($out['segment']??''))==='') $out['segment']=$segHint;
    if(trim((string)($out['show_tax_breakup']??''))==='') $out['show_tax_breakup']='1';
    if(trim((string)($out['pricing_mode']??''))==='') $out['pricing_mode']='solar_split_70_30';
    if(trim((string)($out['place_of_supply_state']??''))==='') $out['place_of_supply_state']='Jharkhand';
    if(trim((string)($out['primary_finance_scenario']??''))==='') $out['primary_finance_scenario']='self_funded';
    return $out;
}
function documents_validate_quote_draft_input(array $input, array $context = []): array {
    $input=documents_quote_import_normalize_input($input);
    $messages=[]; $warnings=[]; $required=documents_quote_import_required_columns();
    foreach($required as $col){ if(trim((string)($input[$col]??''))==='') $messages[]=['field'=>$col,'message'=>'Required field is missing.']; }
    $rawParty=strtoupper(trim((string)($input['_raw_party_type']??$context['raw_party_type']??'')));
    if($rawParty==='' && isset($context['source']) && ($context['source']==='csv')) $rawParty=strtoupper(trim((string)($_POST['party_type']??'')));
    $origParty=strtoupper(trim((string)($context['original_party_type']??'')));
    $partyCheck=$origParty!==''?$origParty:strtoupper(trim((string)($input['party_type_original']??$input['party_type_raw']??'')));
    if($partyCheck!=='' && isset(documents_quote_import_segment_codes()[$partyCheck])) $warnings[]=['field'=>'party_type','message'=>'Legacy segment code '.$partyCheck.' was treated as a segment hint; party_type was normalized to lead.'];
    if(!in_array((string)($input['party_type']??''), ['customer','lead'], true)) $messages[]=['field'=>'party_type','message'=>'party_type must be customer or lead.'];
    foreach(['quotation_date','valid_until'] as $d){ $v=(string)($input[$d]??''); if($v!=='' && !preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)) $messages[]=['field'=>$d,'message'=>'Use ISO date YYYY-MM-DD.']; }
    $main=(float)($input['main_solar_kwp']??0); $non=(float)($input['complimentary_non_dcr_kwp']??$input['non_dcr_kwp']??0); if($main<0||$non<0||($main+$non)<=0) $messages[]=['field'=>'main_solar_kwp','message'=>'Total capacity must be greater than zero.'];
    $mobile=documents_quote_import_normalize_mobile((string)($input['customer_mobile']??'')); if($mobile==='') $messages[]=['field'=>'customer_mobile','message'=>'Valid mobile is required.'];
    $hash=documents_quote_import_row_hash($input); $ids=documents_quote_import_existing_identities(); $key=(string)($input['import_key']??'');
    if($key!=='' && isset($ids['keys'][$key])) $messages[]=['field'=>'import_key','message'=>'Import key already committed in quotation '.$ids['keys'][$key].'.'];
    if(isset($ids['hashes'][$hash])) $messages[]=['field'=>'row_hash','message'=>'This exact row was already committed in quotation '.$ids['hashes'][$hash].'.'];
    $likelyKey=$mobile.'|'.(string)($input['quotation_date']??'').'|'.(string)($input['selected_model_number']??'').'|'.(string)round((float)($input['scenario_price_self_funded']??0),2); if(isset($ids['likely'][$likelyKey])) $warnings[]=['field'=>'duplicate','message'=>'Likely duplicate of quotation '.$ids['likely'][$likelyKey].'.'];
    $preview=documents_build_quote_draft_from_input($input, ['dry_run'=>true]+$context);
    if(!empty($preview['system_reconcile_error'])) $warnings[]=['field'=>'kit','message'=>(string)$preview['system_reconcile_error']];
    return ['ok'=>$messages===[],'status'=>$messages? 'Error' : ($warnings?'Warning':'Valid'),'messages'=>array_merge($messages,$warnings),'errors'=>$messages,'warnings'=>$warnings,'row_hash'=>$hash,'normalized_mobile'=>$mobile,'preview'=>documents_quote_import_preview_from_quote($preview),'normalized_input'=>$input];
}
function documents_quote_import_preview_from_quote(array $q): array { $calc=is_array($q['calc']??null)?$q['calc']:[]; $tb=is_array($q['tax_breakdown']??null)?$q['tax_breakdown']:[]; return ['system_type'=>(string)($q['system_type']??''),'model_number'=>(string)($q['rate_chart_snapshot']['model_number']??$q['selected_model_number']??''),'kit'=>(string)($q['quote_items'][0]['name_snapshot']??$q['quote_items'][0]['name']??''),'item_count'=>count((array)($q['quote_items']??[])),'basic_amount'=>(float)($tb['basic_total']??$calc['basic_total']??0),'gst'=>(float)($tb['gst_total']??0),'tax_mode'=>(string)($tb['mode']??$q['gst_mode_snapshot']??''),'subsidy'=>(float)($calc['subsidy_expected_rs']??0),'transportation'=>(float)($calc['transportation_rs']??0),'discount'=>(float)($calc['discount_rs']??0),'final_payable'=>(float)($calc['gross_payable']??$calc['grand_total']??0)]; }
function documents_build_quote_draft_from_input(array $input, array $context = []): array {
    $input=documents_quote_import_normalize_input($input); $q=documents_quote_defaults(); $now=documents_quote_import_now(); $admin=documents_quote_import_admin_snapshot();
    $q['id']=(string)($context['preserve_id']??('quote_'.date('Ymd_His').'_'.bin2hex(random_bytes(4)))); $q['quote_no']=(string)($context['preserve_quote_no']??''); $q['status']='Draft'; $q['created_at']=(string)($context['preserve_created_at']??$now); $q['updated_at']=$now; $q['created_by_type']='admin'; $q['created_by_id']=$admin['id']; $q['created_by_name']=$admin['name'];
    $q['party_type']=(string)$input['party_type']; $q['segment']=(string)($input['segment']??'RES');
    foreach(['customer_name','customer_mobile','consumer_account_no','billing_address','site_address','district','city','state','pin','meter_number','meter_serial_number','quotation_date','valid_until','special_requests_text','tax_profile_id','place_of_supply_state','pricing_mode','primary_finance_scenario','sanction_load_kwp'] as $f) if(array_key_exists($f,$input)) $q[$f]=(string)$input[$f];
    $q['customer_mobile']=documents_quote_import_normalize_mobile((string)$q['customer_mobile']); $q['system_type']=documents_quote_normalize_system_type((string)($input['system_type']??'ongrid')); $q['selected_model_number']=safe_text((string)($input['selected_model_number']??''));
    $q['main_solar_kwp']=(string)(float)($input['main_solar_kwp']??0); $q['complimentary_non_dcr_kwp']=(string)(float)($input['complimentary_non_dcr_kwp']??0); $q['capacity_kwp']=(string)((float)$q['main_solar_kwp']+(float)$q['complimentary_non_dcr_kwp']); $q['system_capacity_kwp']=(float)$q['capacity_kwp'];
    $q['show_tax_breakup']=documents_quote_bool_from_csv($input['show_tax_breakup']??'', true); $company=load_company_profile(); $q['tax_type']=strtolower((string)$q['place_of_supply_state'])===strtolower((string)($company['state']??'Jharkhand'))?'CGST_SGST':'IGST';
    $priceSelf=round(max(0,(float)($input['scenario_price_self_funded']??0)),2); $priceUp=round(max(0,(float)($input['scenario_price_loan_upto_2_lacs']??0)),2); $priceAbove=round(max(0,(float)($input['scenario_price_loan_above_2_lacs']??0)),2);
    $sub=round(max(0,(float)($input['subsidy_expected_rs']??0)),2); $trans=round(max(0,(float)($input['transportation_rs']??0)),2); $disc=round(max(0,(float)($input['discount_rs']??0)),2); $q['discount_rs']=$disc;
    $q['scenario_prices']=['self_funded'=>['price'=>$priceSelf],'loan_upto_2_lacs'=>['price'=>$priceUp],'loan_above_2_lacs'=>['price'=>$priceAbove]];
    $primary=(string)$q['primary_finance_scenario']; $price=$primary==='loan_above_2_lacs'?$priceAbove:($primary==='loan_upto_2_lacs'?$priceUp:$priceSelf); if($price<=0) $price=$priceSelf;
    $q['input_total_gst_inclusive']=$price; $q['rate_chart_snapshot']=['system_type'=>$q['system_type'],'model_number'=>$q['selected_model_number'],'solar_size_kwp'=>(float)$q['capacity_kwp'],'dcr_size_kwp'=>(float)$q['main_solar_kwp'],'non_dcr_size_kwp'=>(float)$q['complimentary_non_dcr_kwp'],'total_system_size_kwp'=>(float)$q['capacity_kwp'],'hybrid_phase'=>solar_finance_normalize_phase_label((string)($input['hybrid_phase']??'')),'hybrid_inverter_kva'=>(float)($input['hybrid_inverter_kva']??0),'hybrid_battery_count'=>(int)($input['hybrid_battery_count']??0),'self_funded_price'=>$priceSelf,'loan_upto_2_lacs_price'=>$priceUp,'loan_above_2_lacs_price'=>$priceAbove,'captured_at'=>$now];
    $q=documents_quote_reconcile_system_configuration($q); if(function_exists('solar_finance_sync_hybrid_summary_into_quote_items')) $q=solar_finance_sync_hybrid_summary_into_quote_items($q);
    $settings=load_quote_defaults(); $q['calc']=documents_calc_quote_pricing_with_tax_profile($q,$trans,$sub,$price,is_array($settings)?$settings:[]); $q['tax_breakdown']=is_array($q['calc']['tax_breakdown']??null)?$q['calc']['tax_breakdown']:['basic_total'=>0,'gst_total'=>0,'gross_incl_gst'=>0,'slabs'=>[]]; $q['gst_mode_snapshot']=(string)($q['tax_breakdown']['mode']??'single'); $q['gst_slabs_snapshot']=is_array($q['tax_breakdown']['slabs']??null)?$q['tax_breakdown']['slabs']:[];
    $q['finance_inputs']=['monthly_bill_rs'=>(string)($input['monthly_bill_rs']??''),'unit_rate_rs_per_kwh'=>(string)($input['unit_rate_rs_per_kwh']??''),'annual_generation_per_kw'=>(string)($input['annual_generation_per_kw']??''),'subsidy_expected_rs'=>(string)$sub,'transportation_rs'=>(string)$trans,'discount_rs'=>(string)$disc,'loan'=>['enabled'=>str_starts_with($primary,'loan_')]];
    $q['finance_scenarios']=['self_funded'=>['price'=>$priceSelf,'subsidy'=>$sub,'gross_payable'=>$priceSelf,'applicable'=>true],'loan_upto_2_lacs'=>['price'=>$priceUp,'subsidy'=>$sub,'gross_payable'=>$priceUp,'applicable'=>true,'margin_money_rs'=>(float)($input['loan_upto_2_lacs_margin_money_rs']??0),'loan_amount_rs'=>(float)($input['loan_upto_2_lacs_loan_amount_rs']??0),'interest_pct'=>(float)($input['loan_upto_2_lacs_interest_pct']??0),'tenure_years'=>(float)($input['loan_upto_2_lacs_tenure_years']??0)],'loan_above_2_lacs'=>['price'=>$priceAbove,'subsidy'=>$sub,'gross_payable'=>$priceAbove,'applicable'=>true,'margin_money_rs'=>(float)($input['loan_above_2_lacs_margin_money_rs']??0),'loan_amount_rs'=>(float)($input['loan_above_2_lacs_loan_amount_rs']??0),'interest_pct'=>(float)($input['loan_above_2_lacs_interest_pct']??0),'tenure_years'=>(float)($input['loan_above_2_lacs_tenure_years']??0)]];
    $q['customer_snapshot']=array_merge(documents_customer_snapshot_defaults(),['mobile'=>$q['customer_mobile'],'name'=>$q['customer_name'],'address'=>$q['site_address']?:$q['billing_address'],'city'=>$q['city'],'district'=>$q['district'],'pin_code'=>$q['pin'],'state'=>$q['state'],'consumer_account_no'=>$q['consumer_account_no'],'sanction_load_kwp'=>$q['sanction_load_kwp']]);
    $q['public_share_enabled']=false; $q['locked_flag']=false; return $q;
}
function documents_commit_quote_draft(array $validated, array $context = []): array {
    if(empty($validated['ok']) && !in_array((string)($validated['status']??''), ['Valid','Warning'], true)) return ['ok'=>false,'error'=>'Row is invalid.'];
    $input=is_array($validated['normalized_input']??null)?$validated['normalized_input']:(is_array($validated['input']??null)?$validated['input']:$validated); $quote=documents_build_quote_draft_from_input($input,$context); $seg=(string)($quote['segment']??'RES'); if((string)($quote['quote_no']??'')===''){ $num=documents_generate_quote_number($seg); if(empty($num['ok'])) return ['ok'=>false,'error'=>(string)($num['error']??'Numbering failed')]; $quote['quote_no']=(string)$num['quote_no']; }
    $quote['import_metadata']=['batch_id'=>(string)($context['batch_id']??''),'import_key'=>(string)($input['import_key']??''),'source_row'=>(int)($context['source_row']??0),'source_filename'=>safe_filename((string)($context['source_filename']??'')),'row_hash'=>(string)($validated['row_hash']??documents_quote_import_row_hash($input)),'importing_admin'=>documents_quote_import_admin_snapshot(),'imported_at'=>documents_quote_import_now()];
    $hashQuote=$quote; unset($hashQuote['import_metadata']['post_import_hash']); $quote['import_metadata']['post_import_hash']=hash('sha256', json_encode($hashQuote, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); $saved=documents_save_quote($quote); return !empty($saved['ok']) ? ['ok'=>true,'quote'=>$quote,'quote_id'=>$quote['id']] : ['ok'=>false,'error'=>(string)($saved['error']??'Save failed')];
}
function documents_quote_repair_imported_batch(array $batch): array { $repaired=0;$skipped=0;$failed=0;$reasons=[]; foreach((array)($batch['created_quotation_ids']??[]) as $qid){ $q=documents_get_quote((string)$qid); if(!$q){$skipped++;$reasons[$qid]='Quotation not found';continue;} $st=strtolower((string)($q['status']??'draft')); if($st!=='draft'||!empty($q['accepted_at'])||!empty($q['workflow']['agreement_id'])||!empty($q['workflow']['invoice_id'])){$skipped++;$reasons[$qid]='Not an eligible untouched draft';continue;} $meta=is_array($q['import_metadata']??null)?$q['import_metadata']:[]; $row=null; foreach((array)($batch['rows']??[]) as $r){ if((string)($r['commit_result']??'')!=='' && str_contains((string)$r['commit_result'],(string)$qid)){$row=$r;break;} if((string)($r['input']['import_key']??'')===(string)($meta['import_key']??'')){$row=$r;break;} } if(!$row||!is_array($row['input']??null)){$skipped++;$reasons[$qid]='Saved import input missing';continue;} $before=$q; $new=documents_build_quote_draft_from_input($row['input'],['preserve_id'=>$q['id'],'preserve_quote_no'=>$q['quote_no'],'preserve_created_at'=>$q['created_at']]); $new['import_metadata']=$meta; $new['public_token']=$q['public_token']??''; $new['public_share_token']=$q['public_share_token']??''; $new['public_url']=$q['public_url']??''; $new['repair_metadata']=['batch_id'=>(string)($batch['batch_id']??''),'actor'=>documents_quote_import_admin_snapshot(),'time'=>documents_quote_import_now(),'pre_repair_snapshot'=>$before,'before_hash'=>hash('sha256',json_encode($before,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)),'after_hash'=>hash('sha256',json_encode($new,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))]; $save=documents_save_quote($new); if(!empty($save['ok']))$repaired++;else{$failed++;$reasons[$qid]='Save failed';} } return ['repaired'=>$repaired,'skipped'=>$skipped,'failed'=>$failed,'reasons'=>$reasons,'actor'=>documents_quote_import_admin_snapshot(),'time'=>documents_quote_import_now()]; }
