<?php
declare(strict_types=1);

require_once __DIR__ . '/bootstrap.php';
require_once __DIR__ . '/tasks_helpers.php';

class TaskWorkflowException extends RuntimeException {}
final class TaskWorkflowConflict extends TaskWorkflowException {}

/** Canonical transactional state machine for official assigned work. */
final class TaskWorkflowService
{
    public const STATES=['assigned','acknowledged','in_progress','blocked','submitted','correction_required','completed','cancelled'];
    private const TRANSITIONS=[
        'acknowledge'=>['employee',['assigned'], 'acknowledged','employee'],
        'start'=>['employee',['acknowledged','correction_required'], 'in_progress','employee'],
        'block'=>['employee',['acknowledged','in_progress','correction_required'], 'blocked','admin'],
        'admin_response'=>['admin',['blocked'], 'in_progress','employee'],
        'submit'=>['employee',['in_progress'], 'submitted','admin'],
        'correction'=>['admin',['submitted'], 'correction_required','employee'],
        'approve'=>['admin',['submitted'], 'completed','none'],
        'reopen'=>['admin',['completed'], 'in_progress','employee'],
        'cancel'=>['admin',['assigned','acknowledged','in_progress','blocked','submitted','correction_required'], 'cancelled','none'],
    ];

    public function __construct(private PDO $db, private array $actor, private ?string $storageDir=null)
    {
        canonical_work_initialize_schema($db);
        $this->storageDir ??= dirname(__DIR__).'/storage/task-attachments';
    }
    private function actorId():int { $id=(int)($this->actor['id']??0);if($id<1)throw new TaskWorkflowException('Authenticated actor is required.');return $id; }
    private function role():string { $r=(string)($this->actor['role_name']??'');if(!in_array($r,['admin','employee'],true))throw new TaskWorkflowException('Task access is not permitted.');return $r; }
    private function now():string{return (new DateTimeImmutable('now',new DateTimeZone('Asia/Kolkata')))->format('Y-m-d H:i:s');}
    private function task(int $id):array{$s=$this->db->prepare('SELECT * FROM portal_tasks WHERE id=?');$s->execute([$id]);$t=$s->fetch();if(!$t)throw new TaskWorkflowException('Task not found.');return $t;}
    private function authorize(array $task):void{if($this->role()==='employee'&&(int)$task['assignee_id']!==$this->actorId())throw new TaskWorkflowException('You may access only your assigned work.');}
    private function requireVersion(int $version):void{if($version<1)throw new TaskWorkflowException('Task version is required; reload before saving.');}
    private function legacy(string $state):string{return match($state){'in_progress','submitted'=>'in_progress','completed','cancelled'=>'done',default=>'todo'};}
    private function event(int $taskId,string $type,array $data,int $version):void{$s=$this->db->prepare('INSERT INTO task_events(task_id,actor_id,event_type,event_data,task_version,created_at) VALUES(?,?,?,?,?,?)');$s->execute([$taskId,$this->actorId(),$type,json_encode($data,JSON_THROW_ON_ERROR),$version,$this->now()]);}
    private function message(int $taskId,string $type,string $body):?int{if($body==='')return null;$s=$this->db->prepare('INSERT INTO task_messages(task_id,author_id,body,created_at,message_type) VALUES(?,?,?,?,?)');$s->execute([$taskId,$this->actorId(),$body,$this->now(),$type]);return (int)$this->db->lastInsertId();}
    private function atomic(callable $fn):mixed{$this->db->exec('BEGIN IMMEDIATE');try{$v=$fn();$this->db->commit();return $v;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}

    public function create(array $input,array $files=[]):array
    {
        if($this->role()!=='admin')throw new TaskWorkflowException('Only an administrator can assign official work.');
        foreach(['title','description','expected_outcome'] as $f)if(trim((string)($input[$f]??''))==='')throw new TaskWorkflowException(ucwords(str_replace('_',' ',$f)).' is required.');
        $assignee=(int)($input['assignee_id']??0);if($assignee<1)throw new TaskWorkflowException('Employee is required.');
        $priority=(string)($input['priority']??'medium');if(!in_array($priority,['low','medium','high','urgent'],true))throw new TaskWorkflowException('Invalid priority.');
        $frequency=(string)($input['frequency_type']??'once');if(!in_array($frequency,['once','daily','weekly','monthly','custom'],true))throw new TaskWorkflowException('Invalid recurrence.');
        return $this->atomic(function()use($input,$files,$assignee,$priority,$frequency){
            $now=$this->now();$series=bin2hex(random_bytes(16));
            $s=$this->db->prepare("INSERT INTO portal_tasks(title,description,status,priority,workflow_priority,assignee_id,created_at,updated_at,expected_outcome,category,linked_entity_type,linked_entity_id,start_date,due_date,due_time,frequency_type,custom_every_n_days,proof_required,workflow_status,responsibility,attention_owner_id,last_activity_at,recurrence_series_id,created_by,official_flag) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)");
            $s->execute([trim((string)$input['title']),trim((string)$input['description']),'todo',$priority==='urgent'?'high':$priority,$priority,$assignee,$now,$now,trim((string)$input['expected_outcome']),trim((string)($input['category']??'')),($input['linked_entity_type']??'')?:null,($input['linked_entity_id']??'')?:null,($input['start_date']??'')?:null,($input['due_date']??'')?:null,($input['due_time']??'')?:null,$frequency,max(0,(int)($input['custom_every_n_days']??0)),!empty($input['proof_required'])?1:0,'assigned','employee',$assignee,$now,$series,$this->actorId()]);
            $id=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO task_occurrences(task_id,series_id,occurrence_number,scheduled_for,created_at) VALUES(?,?,?,?,?)')->execute([$id,$series,1,($input['due_date']??'')?:null,$now]);
            $mid=$this->message($id,'assignment',trim((string)$input['description']));foreach($files as $file)$this->storeAttachment($id,$mid,$file);
            $this->event($id,'assigned',['assignee_id'=>$assignee],1);return $this->detail($id);
        });
    }

    public function transition(int $id,int $version,string $action,string $body=''):array
    {
        $this->requireVersion($version);if(!isset(self::TRANSITIONS[$action]))throw new TaskWorkflowException('Invalid task action.');
        [$role,$from,$to,$responsibility]=self::TRANSITIONS[$action];if($this->role()!==$role)throw new TaskWorkflowException('This action is not permitted for your role.');
        $mandatory=in_array($action,['block','submit','correction','reopen','cancel'],true);if($mandatory&&trim($body)==='')throw new TaskWorkflowException('An explanation is required.');
        return $this->atomic(function()use($id,$version,$action,$body,$from,$to,$responsibility){$t=$this->task($id);$this->authorize($t);if((int)$t['version']!==$version)throw new TaskWorkflowConflict('This task changed. Reload and try again.');if(!in_array($t['workflow_status'],$from,true))throw new TaskWorkflowException("Cannot $action a {$t['workflow_status']} task.");
            if($action==='submit'&&!empty($t['proof_required'])){$s=$this->db->prepare('SELECT COUNT(*) FROM task_attachments WHERE task_id=?');$s->execute([$id]);if((int)$s->fetchColumn()<1)throw new TaskWorkflowException('Proof attachment is required before submission.');}
            $newVersion=$version+1;$owner=$responsibility==='employee'?(int)$t['assignee_id']:($responsibility==='admin'?$this->actorId():null);$now=$this->now();$submission=$action==='submit'?trim($body):$t['submission_summary'];$approved=$action==='approve'?$now:$t['approved_at'];$approvedBy=$action==='approve'?$this->actorId():$t['approved_by'];$closed=in_array($action,['cancel','reopen'],true)?trim($body):$t['closed_reason'];
            $s=$this->db->prepare('UPDATE portal_tasks SET workflow_status=?,status=?,responsibility=?,attention_owner_id=?,submission_summary=?,approved_at=?,approved_by=?,closed_reason=?,updated_at=?,last_activity_at=?,version=? WHERE id=? AND version=?');$s->execute([$to,$this->legacy($to),$responsibility,$owner,$submission,$approved,$approvedBy,$closed,$now,$now,$newVersion,$id,$version]);if($s->rowCount()!==1)throw new TaskWorkflowConflict('This task changed. Reload and try again.');
            $type=match($action){'block'=>'blocker_request','admin_response'=>'admin_response','submit'=>'completion_submission','correction'=>'correction_instructions','approve'=>'approval',default=>$action};$this->message($id,$type,trim($body));$this->event($id,$type,['from'=>$t['workflow_status'],'to'=>$to,'responsibility'=>$responsibility],$newVersion);if($action==='approve')$this->createNextOccurrence($t,$id,$now);return $this->detail($id);});
    }
    public function post(int $id,int $version,string $type,string $body):array
    {
        $this->requireVersion($version);if(!in_array($type,['reply','progress'],true)||trim($body)==='')throw new TaskWorkflowException('Message is required.');
        return $this->atomic(function()use($id,$version,$type,$body){$t=$this->task($id);$this->authorize($t);if(in_array($t['workflow_status'],['completed','cancelled'],true))throw new TaskWorkflowException('Closed tasks cannot receive messages.');$responsibility=$this->role()==='admin'?'employee':'admin';$owner=$responsibility==='employee'?(int)$t['assignee_id']:$this->actorId();$s=$this->db->prepare('UPDATE portal_tasks SET responsibility=?,attention_owner_id=?,version=version+1,updated_at=?,last_activity_at=? WHERE id=? AND version=?');$now=$this->now();$s->execute([$responsibility,$owner,$now,$now,$id,$version]);if($s->rowCount()!==1)throw new TaskWorkflowConflict('This task changed. Reload and try again.');$this->message($id,$type,trim($body));$this->event($id,$type,['responsibility'=>$responsibility],$version+1);return $this->detail($id);});
    }
    public function reassign(int $id,int $version,int $assignee):array{if($this->role()!=='admin'||$assignee<1)throw new TaskWorkflowException('Only an administrator can reassign work.');$this->requireVersion($version);return $this->atomic(function()use($id,$version,$assignee){$t=$this->task($id);if(in_array($t['workflow_status'],['completed','cancelled'],true))throw new TaskWorkflowException('Closed work cannot be reassigned.');$s=$this->db->prepare("UPDATE portal_tasks SET assignee_id=?,workflow_status='assigned',status='todo',responsibility='employee',attention_owner_id=?,version=version+1,updated_at=?,last_activity_at=? WHERE id=? AND version=?");$n=$this->now();$s->execute([$assignee,$assignee,$n,$n,$id,$version]);if($s->rowCount()!==1)throw new TaskWorkflowConflict('This task changed. Reload and try again.');$this->event($id,'reassigned',['from_assignee_id'=>(int)$t['assignee_id'],'to_assignee_id'=>$assignee],$version+1);return $this->detail($id);});}
    public function revise(int $id,int $version,?string $dueDate,?string $dueTime,string $priority):array{if($this->role()!=='admin')throw new TaskWorkflowException('Only an administrator can revise work.');$this->requireVersion($version);if(!in_array($priority,['low','medium','high','urgent'],true))throw new TaskWorkflowException('Invalid priority.');return $this->atomic(function()use($id,$version,$dueDate,$dueTime,$priority){$t=$this->task($id);if(in_array($t['workflow_status'],['completed','cancelled'],true))throw new TaskWorkflowException('Closed work cannot be revised.');$n=$this->now();$s=$this->db->prepare('UPDATE portal_tasks SET due_date=?,due_time=?,priority=?,workflow_priority=?,version=version+1,updated_at=?,last_activity_at=? WHERE id=? AND version=?');$s->execute([$dueDate?:null,$dueTime?:null,$priority==='urgent'?'high':$priority,$priority,$n,$n,$id,$version]);if($s->rowCount()!==1)throw new TaskWorkflowConflict('This task changed. Reload and try again.');$this->event($id,'schedule_priority_revised',['old_due_date'=>$t['due_date'],'due_date'=>$dueDate,'old_priority'=>$t['workflow_priority'],'priority'=>$priority],$version+1);return $this->detail($id);});}
    public function archive(int $id,int $version,bool $archive):array{if($this->role()!=='admin')throw new TaskWorkflowException('Only an administrator can archive work.');$this->requireVersion($version);return $this->atomic(function()use($id,$version,$archive){$t=$this->task($id);if(!in_array($t['workflow_status'],['completed','cancelled'],true))throw new TaskWorkflowException('Only closed work can be archived.');$n=$this->now();$s=$this->db->prepare('UPDATE portal_tasks SET archived_flag=?,archived_at=?,version=version+1,updated_at=?,last_activity_at=? WHERE id=? AND version=?');$s->execute([$archive?1:0,$archive?$n:null,$n,$n,$id,$version]);if($s->rowCount()!==1)throw new TaskWorkflowConflict('This task changed. Reload and try again.');$this->event($id,$archive?'archived':'unarchived',[],$version+1);return $this->detail($id);});}
    public function upload(int $id,int $version,array $file):array{$this->requireVersion($version);return $this->atomic(function()use($id,$version,$file){$t=$this->task($id);$this->authorize($t);$a=$this->storeAttachment($id,null,$file);$n=$this->now();$s=$this->db->prepare('UPDATE portal_tasks SET version=version+1,updated_at=?,last_activity_at=? WHERE id=? AND version=?');$s->execute([$n,$n,$id,$version]);if($s->rowCount()!==1)throw new TaskWorkflowConflict('This task changed. Reload and try again.');$this->event($id,'attachment_uploaded',['attachment_id'=>$a],$version+1);return $this->detail($id);});}
    private function storeAttachment(int $taskId,?int $messageId,array $f):int{if(($f['error']??UPLOAD_ERR_OK)!==UPLOAD_ERR_OK||!is_uploaded_file((string)($f['tmp_name']??''))&&empty($f['_test']))throw new TaskWorkflowException('Invalid attachment upload.');$size=(int)($f['size']??0);if($size<1||$size>10*1024*1024)throw new TaskWorkflowException('Attachments must be between 1 byte and 10 MB.');$name=basename((string)($f['name']??''));$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));$allowed=['pdf'=>'application/pdf','png'=>'image/png','jpg'=>'image/jpeg','jpeg'=>'image/jpeg','webp'=>'image/webp','txt'=>'text/plain'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file((string)$f['tmp_name']);if(!isset($allowed[$ext])||$allowed[$ext]!==$mime)throw new TaskWorkflowException('Unsupported or mismatched attachment type.');if(!is_dir($this->storageDir)&&!mkdir($this->storageDir,0770,true)&&!is_dir($this->storageDir))throw new TaskWorkflowException('Protected storage is unavailable.');$key=bin2hex(random_bytes(24)).'.'.$ext;$dest=$this->storageDir.'/'.$key;$moved=!empty($f['_test'])?copy((string)$f['tmp_name'],$dest):move_uploaded_file((string)$f['tmp_name'],$dest);if(!$moved)throw new TaskWorkflowException('Attachment could not be stored.');$s=$this->db->prepare('INSERT INTO task_attachments(task_id,message_id,uploaded_by,storage_key,original_name,media_type,byte_size,sha256,created_at) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([$taskId,$messageId,$this->actorId(),$key,$name,$mime,$size,hash_file('sha256',$dest),$this->now()]);return (int)$this->db->lastInsertId();}
    private function createNextOccurrence(array $t,int $id,string $now):void{$frequency=(string)$t['frequency_type'];if($frequency==='once')return;$anchor=max((string)($t['due_date']??''),(new DateTimeImmutable('today',new DateTimeZone('Asia/Kolkata')))->format('Y-m-d'));$next=compute_next_due_date($frequency,$anchor,(int)$t['custom_every_n_days']);$series=(string)$t['recurrence_series_id'];$q=$this->db->prepare('SELECT COALESCE(MAX(occurrence_number),0)+1 FROM task_occurrences WHERE series_id=?');$q->execute([$series]);$num=(int)$q->fetchColumn();$s=$this->db->prepare("INSERT INTO portal_tasks(title,description,status,priority,workflow_priority,assignee_id,created_at,updated_at,expected_outcome,category,linked_entity_type,linked_entity_id,start_date,due_date,due_time,frequency_type,custom_every_n_days,proof_required,workflow_status,responsibility,attention_owner_id,last_activity_at,parent_task_id,recurrence_series_id,created_by,official_flag) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)");$s->execute([$t['title'],$t['description'],'todo',$t['priority'],$t['workflow_priority'],$t['assignee_id'],$now,$now,$t['expected_outcome'],$t['category'],$t['linked_entity_type'],$t['linked_entity_id'],$next,$next,$t['due_time'],$frequency,$t['custom_every_n_days'],$t['proof_required'],'assigned','employee',$t['assignee_id'],$now,$id,$series,$t['created_by']]);$new=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO task_occurrences(task_id,series_id,parent_task_id,occurrence_number,scheduled_for,created_at) VALUES(?,?,?,?,?,?)')->execute([$new,$series,$id,$num,$next,$now]);$this->event($new,'recurrence_created',['approved_task_id'=>$id],1);}
    public function detail(int $id):array{$t=$this->task($id);$this->authorize($t);foreach(['messages'=>'SELECT m.*,u.full_name actor_name FROM task_messages m JOIN users u ON u.id=m.author_id WHERE m.task_id=? ORDER BY m.created_at,m.id','events'=>'SELECT e.*,u.full_name actor_name FROM task_events e LEFT JOIN users u ON u.id=e.actor_id WHERE e.task_id=? ORDER BY e.created_at,e.id','attachments'=>'SELECT id,original_name,media_type,byte_size,uploaded_by,created_at FROM task_attachments WHERE task_id=? ORDER BY id'] as $k=>$sql){$s=$this->db->prepare($sql);$s->execute([$id]);$t[$k]=$s->fetchAll();}$s=$this->db->prepare('SELECT * FROM task_occurrences WHERE task_id=?');$s->execute([$id]);$t['occurrence']=$s->fetch()?:null;return $t;}
    public function attachment(int $attachmentId):array{$s=$this->db->prepare('SELECT a.*,t.assignee_id FROM task_attachments a JOIN portal_tasks t ON t.id=a.task_id WHERE a.id=?');$s->execute([$attachmentId]);$a=$s->fetch();if(!$a)throw new TaskWorkflowException('Attachment not found.');if($this->role()==='employee'&&(int)$a['assignee_id']!==$this->actorId())throw new TaskWorkflowException('Attachment access denied.');if(!preg_match('/\A[a-f0-9]{48}\.(pdf|png|jpg|jpeg|webp|txt)\z/',$a['storage_key']))throw new TaskWorkflowException('Invalid attachment key.');$real=realpath($this->storageDir.'/'.$a['storage_key']);$base=realpath($this->storageDir);if($real===false||$base===false||!str_starts_with($real,$base.DIRECTORY_SEPARATOR))throw new TaskWorkflowException('Attachment is unavailable.');$a['path']=$real;return $a;}
}
